// Curated rack material for Anagrams Race — 14 familiar 7-letter racks.
// Solution lists are generated from the shared wordhunt dictionary
// (public/wordhunt-dict.txt, 3-7 letters) so every buildable word counts.
// Regenerate: for each rack, take all dict words 3-7 letters buildable
// from its letters, sorted by length then A-Z.

export const ANAGRAM_RACK_WORDS = [
  'planets', 'teacher', 'friends', 'gardens', 'oranges', 'painter',
  'monster', 'strange', 'silence', 'closing', 'farmers', 'reading',
  'reactor', 'pockets',
]

export const ANAGRAM_VALID_WORDS = [
  // PLANETS (212)
  'ale', 'alp', 'als', 'alt', 'ane', 'ant', 'ape', 'apt',
  'asp', 'ate', 'eat', 'els', 'ens', 'eta', 'lap', 'las',
  'lat', 'lea', 'let', 'nae', 'nap', 'net', 'pal', 'pan',
  'pas', 'pat', 'pea', 'pen', 'pes', 'pet', 'sae', 'sal',
  'sap', 'sat', 'sea', 'sel', 'sen', 'set', 'spa', 'tae',
  'tan', 'tap', 'tas', 'tea', 'tel', 'ten', 'ales', 'alps',
  'alts', 'anes', 'ante', 'ants', 'apes', 'apse', 'ates', 'east',
  'eats', 'elan', 'etas', 'etna', 'lane', 'laps', 'lase', 'last',
  'late', 'lats', 'lean', 'leap', 'leas', 'lens', 'lent', 'lept',
  'lest', 'lets', 'nape', 'naps', 'neap', 'neat', 'nest', 'nets',
  'pale', 'pals', 'pane', 'pans', 'pant', 'pase', 'past', 'pate',
  'pats', 'peal', 'pean', 'peas', 'peat', 'pelt', 'pens', 'pent',
  'pest', 'pets', 'plan', 'plat', 'plea', 'sale', 'salp', 'salt',
  'sane', 'sate', 'seal', 'seat', 'sent', 'sept', 'seta', 'slap',
  'slat', 'snap', 'spae', 'span', 'spat', 'step', 'tael', 'tale',
  'tans', 'tape', 'taps', 'teal', 'teas', 'tela', 'tels', 'tens',
  'tepa', 'antes', 'aspen', 'elans', 'etnas', 'lanes', 'lapse', 'laten',
  'leans', 'leant', 'leaps', 'leapt', 'least', 'lepta', 'napes', 'nates',
  'neaps', 'neats', 'pales', 'palet', 'panel', 'panes', 'pants', 'paste',
  'paten', 'pates', 'peals', 'peans', 'peats', 'pelts', 'penal', 'petal',
  'plane', 'plans', 'plant', 'plate', 'plats', 'pleas', 'pleat', 'plena',
  'salep', 'sepal', 'septa', 'setal', 'slant', 'slate', 'slept', 'sneap',
  'spale', 'spate', 'spean', 'spelt', 'spent', 'splat', 'stale', 'stane',
  'steal', 'stela', 'taels', 'tales', 'tapes', 'teals', 'tepal', 'tepas',
  'tesla', 'latens', 'palest', 'palets', 'panels', 'pastel', 'patens', 'petals',
  'planes', 'planet', 'plants', 'platen', 'plates', 'pleats', 'septal', 'splent',
  'staple', 'tepals', 'planets', 'platens',
  // TEACHER (107)
  'ace', 'act', 'arc', 'are', 'art', 'ate', 'car', 'cat',
  'cee', 'ear', 'eat', 'era', 'ere', 'eta', 'eth', 'hae',
  'hat', 'her', 'het', 'rah', 'rat', 'rec', 'ree', 'ret',
  'tae', 'tar', 'tea', 'tee', 'the', 'ache', 'acre', 'arch',
  'care', 'cart', 'cate', 'cere', 'cete', 'char', 'chat', 'each',
  'eath', 'eche', 'etch', 'haet', 'hare', 'hart', 'hate', 'hear',
  'heat', 'here', 'race', 'rate', 'rath', 'rete', 'rhea', 'tace',
  'tach', 'tahr', 'tare', 'tear', 'thae', 'thee', 'tree', 'arete',
  'caret', 'carte', 'cater', 'chare', 'chart', 'cheat', 'cheer', 'chert',
  'crate', 'earth', 'eater', 'erect', 'ether', 'hater', 'heart', 'ratch',
  'rathe', 'reach', 'react', 'recta', 'retch', 'tache', 'teach', 'terce',
  'theca', 'there', 'three', 'trace', 'aether', 'cerate', 'create', 'ecarte',
  'etcher', 'heater', 'hereat', 'rachet', 'reheat', 'thecae', 'cheater', 'hectare',
  'recheat', 'reteach', 'teacher',
  // FRIENDS (126)
  'den', 'die', 'din', 'dis', 'efs', 'end', 'ens', 'ern',
  'ers', 'fed', 'fen', 'fer', 'fid', 'fie', 'fin', 'fir',
  'ids', 'ifs', 'ins', 'ire', 'red', 'ref', 'rei', 'res',
  'rid', 'rif', 'rin', 'sei', 'sen', 'ser', 'sin', 'sir',
  'sri', 'defi', 'dens', 'dies', 'dine', 'dins', 'dire', 'ends',
  'erns', 'feds', 'fend', 'fens', 'fern', 'fids', 'find', 'fine',
  'fins', 'fire', 'firn', 'firs', 'ides', 'ired', 'ires', 'neif',
  'nerd', 'nide', 'reds', 'refs', 'reif', 'rein', 'reis', 'rend',
  'ride', 'rids', 'rife', 'rifs', 'rind', 'rins', 'rise', 'seif',
  'send', 'serf', 'side', 'sine', 'sire', 'sned', 'defis', 'diner',
  'dines', 'dries', 'fends', 'ferns', 'fiend', 'finds', 'fined', 'finer',
  'fines', 'fired', 'fires', 'firns', 'fried', 'fries', 'frise', 'infer',
  'neifs', 'nerds', 'nides', 'reifs', 'reins', 'rends', 'resid', 'resin',
  'rides', 'rinds', 'rinse', 'risen', 'serif', 'serin', 'sired', 'siren',
  'snide', 'diners', 'fiends', 'finder', 'friend', 'infers', 'redfin', 'refind',
  'rinsed', 'snider', 'finders', 'friends', 'redfins', 'refinds',
  // GARDENS (152)
  'ads', 'age', 'and', 'ane', 'are', 'ars', 'dag', 'den',
  'ear', 'end', 'eng', 'ens', 'era', 'erg', 'ern', 'ers',
  'gad', 'gae', 'gan', 'gar', 'gas', 'ged', 'gen', 'nae',
  'nag', 'rad', 'rag', 'ran', 'ras', 'red', 'reg', 'res',
  'sad', 'sae', 'sag', 'sea', 'seg', 'sen', 'ser', 'aged',
  'ager', 'ages', 'ands', 'anes', 'ares', 'dags', 'dang',
  'dare', 'darn', 'dean', 'dear', 'dens', 'drag', 'dreg', 'earn',
  'ears', 'egad', 'ends', 'engs', 'eras', 'ergs', 'erns', 'gads',
  'gaed', 'gaen', 'gaes', 'gane', 'gars', 'gear', 'geds', 'gens',
  'gnar', 'grad', 'gran', 'nags', 'nard', 'near', 'nerd', 'rads',
  'rage', 'rags', 'rand', 'rang', 'rase', 'read', 'reds', 'regs',
  'rend', 'sade', 'sage', 'sand', 'sane', 'sang', 'sard', 'sear',
  'send', 'sera', 'snag', 'sned', 'agers', 'anger', 'dangs', 'dares',
  'darns', 'deans', 'dears', 'degas', 'drags', 'dregs', 'earns', 'egads',
  'gears', 'gnars', 'grade', 'grads', 'grand', 'grans', 'nards', 'nares',
  'nears', 'nerds', 'raged', 'rages', 'rands', 'range', 'rased', 'reads',
  'redan', 'regna', 'rends', 'sager', 'saned', 'saner', 'sarge', 'sedan',
  'snare', 'angers', 'danger', 'gander', 'garden', 'grades', 'grands', 'ranged',
  'ranges', 'redans', 'sander', 'sanger', 'snared', 'dangers', 'ganders', 'gardens',
  // ORANGES (167)
  'age', 'ago', 'ane', 'are', 'ars', 'ear', 'ego', 'eng',
  'ens', 'eon', 'era', 'erg', 'ern', 'ers', 'gae', 'gan',
  'gar', 'gas', 'gen', 'goa', 'gor', 'nae', 'nag', 'nog',
  'nor', 'nos', 'oar', 'oes', 'one', 'ons', 'ora', 'ore',
  'ors', 'ose', 'rag', 'ran', 'ras', 'reg', 'res', 'roe',
  'sae', 'sag', 'sea', 'seg', 'sen', 'ser', 'son', 'aeon',
  'aero', 'ager', 'ages', 'agon', 'anes', 'ares', 'earn',
  'ears', 'egos', 'engs', 'eons', 'eras', 'ergo', 'ergs', 'erns',
  'eros', 'gaen', 'gaes', 'gane', 'gars', 'gear', 'gens', 'gnar',
  'goas', 'goer', 'goes', 'gone', 'gore', 'gran', 'nags', 'naos',
  'near', 'noes', 'nogs', 'nose', 'oars', 'ogre', 'ones', 'ores',
  'osar', 'rage', 'rags', 'rang', 'rase', 'regs', 'roan', 'roes',
  'rose', 'sage', 'sago', 'sane', 'sang', 'sear', 'sego', 'sera',
  'snag', 'snog', 'soar', 'sone', 'song', 'sora', 'sore', 'sorn',
  'aeons', 'agers', 'agone', 'agons', 'anger', 'argon', 'arose', 'arson',
  'earns', 'gears', 'genoa', 'genro', 'gnars', 'goers', 'goner', 'gores',
  'gorse', 'grans', 'groan', 'nares', 'nears', 'ogres', 'orang', 'organ',
  'rages', 'range', 'regna', 'roans', 'sager', 'saner', 'sarge', 'segno',
  'senor', 'snare', 'snore', 'sonar', 'agones', 'angers', 'argons', 'arseno',
  'genoas', 'genros', 'goners', 'groans', 'onager', 'orange', 'orangs', 'organs',
  'ranges', 'reason', 'sanger', 'sarong', 'senora', 'onagers', 'oranges',
  // PAINTER (161)
  'ain', 'air', 'ait', 'ane', 'ani', 'ant', 'ape', 'apt',
  'are', 'art', 'ate', 'ear', 'eat', 'era', 'ern', 'eta',
  'ire', 'nae', 'nap', 'net', 'nip', 'nit', 'pan', 'par',
  'pat', 'pea', 'pen', 'per', 'pet', 'pia', 'pie', 'pin',
  'pit', 'ran', 'rap', 'rat', 'rei', 'rep', 'ret', 'ria',
  'rin', 'rip', 'tae', 'tan', 'tap', 'tar', 'tea', 'ten',
  'tie', 'tin', 'tip', 'airn', 'airt', 'ante', 'anti', 'aper',
  'earn', 'etna', 'nape', 'neap', 'near', 'neat', 'nipa', 'nite',
  'pain', 'pair', 'pane', 'pant', 'pare', 'part', 'pate', 'pean',
  'pear', 'peat', 'pein', 'pent', 'peri', 'pert', 'pian', 'pier',
  'pina', 'pine', 'pint', 'pirn', 'pita', 'prat', 'rain', 'rani',
  'rant', 'rape', 'rapt', 'rate', 'reap', 'rein', 'rent', 'ripe',
  'rite', 'tain', 'tape', 'tare', 'tarn', 'tarp', 'tear', 'tepa',
  'tern', 'tier', 'tine', 'tire', 'trap', 'trip', 'antre', 'apter',
  'arpen', 'atrip', 'entia', 'inapt', 'inept', 'inert', 'inter', 'irate',
  'niter', 'nitre', 'paint', 'paten', 'pater', 'patin', 'peart', 'pieta',
  'pinta', 'prate', 'print', 'repin', 'retia', 'riant', 'ripen', 'taper',
  'tapir', 'tenia', 'terai', 'tinea', 'train', 'trine', 'tripe', 'arpent',
  'enrapt', 'entrap', 'panier', 'pantie', 'parent', 'patine', 'pineta', 'pirate',
  'pterin', 'rapine', 'ratine', 'retain', 'retina', 'trepan', 'painter', 'pertain',
  'repaint',
  // MONSTER (147)
  'ems', 'ens', 'eon', 'ern', 'ers', 'men', 'met', 'mon',
  'mor', 'mos', 'mot', 'net', 'nom', 'nor', 'nos', 'not',
  'oes', 'oms', 'one', 'ons', 'ore', 'ors', 'ort', 'ose',
  'rem', 'res', 'ret', 'roe', 'rom', 'rot', 'sen', 'ser',
  'set', 'son', 'sot', 'ten', 'toe', 'tom', 'ton', 'tor',
  'eons', 'erns', 'eros', 'erst', 'meno', 'mons', 'more', 'morn',
  'mors', 'mort', 'most', 'mote', 'mots', 'nest', 'nets', 'noes',
  'nome', 'noms', 'norm', 'nose', 'note', 'omen', 'omer', 'ones',
  'ores', 'orts', 'rems', 'rent', 'rest', 'rets', 'roes', 'roms',
  'rose', 'rote', 'rots', 'sent', 'snot', 'some', 'sone', 'sore',
  'sorn', 'sort', 'stem', 'tens', 'term', 'tern', 'toes', 'tome',
  'toms', 'tone', 'tons', 'tore', 'torn', 'tors', 'enorm', 'meson',
  'metro', 'monte', 'mores', 'morns', 'morse', 'morts', 'moste', 'motes',
  'nerts', 'nomes', 'norms', 'noter', 'notes', 'omens', 'omers', 'onset',
  'rents', 'roset', 'rotes', 'senor', 'seton', 'smote', 'snore', 'snort',
  'steno', 'stern', 'stone', 'store', 'storm', 'tenor', 'terms', 'terns',
  'tomes', 'toner', 'tones', 'tores', 'torse', 'trone', 'mentor', 'metros',
  'montes', 'nestor', 'noters', 'sermon', 'stoner', 'tenors', 'tensor', 'toners',
  'trones', 'mentors', 'monster',
  // STRANGE (194)
  'age', 'ane', 'ant', 'are', 'ars', 'art', 'ate', 'ear',
  'eat', 'eng', 'ens', 'era', 'erg', 'ern', 'ers', 'eta',
  'gae', 'gan', 'gar', 'gas', 'gat', 'gen', 'get', 'nae',
  'nag', 'net', 'rag', 'ran', 'ras', 'rat', 'reg', 'res',
  'ret', 'sae', 'sag', 'sat', 'sea', 'seg', 'sen', 'ser',
  'set', 'tae', 'tag', 'tan', 'tar', 'tas', 'tea', 'teg',
  'ten', 'ager', 'ages', 'anes', 'ante', 'ants', 'ares',
  'arts', 'ates', 'earn', 'ears', 'east', 'eats', 'engs', 'eras',
  'ergs', 'erns', 'erst', 'etas', 'etna', 'gaen', 'gaes', 'gane',
  'gars', 'gast', 'gate', 'gats', 'gear', 'gens', 'gent', 'gest',
  'geta', 'gets', 'gnar', 'gnat', 'gran', 'grat', 'nags', 'near',
  'neat', 'nest', 'nets', 'rage', 'rags', 'rang', 'rant', 'rase',
  'rate', 'rats', 'regs', 'rent', 'rest', 'rets', 'sage', 'sane',
  'sang', 'sate', 'sear', 'seat', 'sent', 'sera', 'seta', 'snag',
  'stag', 'star', 'tags', 'tang', 'tans', 'tare', 'tarn', 'tars',
  'tear', 'teas', 'tegs', 'tens', 'tern', 'tsar', 'agent', 'agers',
  'anger', 'angst', 'antes', 'antre', 'aster', 'earns', 'etnas', 'gates',
  'gears', 'gents', 'getas', 'gnars', 'gnats', 'grans', 'grant', 'grate',
  'great', 'nares', 'nates', 'nears', 'neats', 'nerts', 'rages', 'range',
  'rants', 'rates', 'regna', 'rents', 'retag', 'sager', 'saner', 'sarge',
  'snare', 'stage', 'stane', 'stang', 'stare', 'stern', 'tangs', 'tares',
  'targe', 'tarns', 'tears', 'terga', 'terns', 'trans', 'agents', 'angers',
  'antres', 'argent', 'astern', 'garnet', 'gaster', 'grants', 'grates', 'greats',
  'ranges', 'retags', 'sanger', 'stager', 'sterna', 'strang', 'targes', 'argents',
  'garnets', 'strange',
  // SILENCE (67)
  'cee', 'cel', 'cis', 'eel', 'els', 'ens', 'ice', 'ins',
  'lee', 'lei', 'lie', 'lin', 'lis', 'nee', 'nil', 'sec',
  'see', 'sei', 'sel', 'sen', 'sic', 'sin', 'cees', 'ceil',
  'cels', 'cine', 'eels', 'else', 'ices', 'isle', 'lees', 'leis',
  'lens', 'lice', 'lien', 'lies', 'line', 'lins', 'nice', 'nils',
  'seel', 'seen', 'sene', 'sice', 'sine', 'ceils', 'cense', 'cines',
  'cline', 'lenes', 'lenis', 'lense', 'liens', 'lines', 'niece', 'scene',
  'seine', 'since', 'slice', 'clines', 'enisle', 'ensile', 'nieces', 'senile',
  'license', 'selenic', 'silence',
  // CLOSING (84)
  'cis', 'cog', 'col', 'con', 'cos', 'gin', 'ins', 'ion',
  'lin', 'lis', 'log', 'nil', 'nog', 'nos', 'oil', 'ons',
  'sic', 'sin', 'sol', 'son', 'cion', 'clog', 'clon', 'cogs',
  'coil', 'coin', 'cols', 'coni', 'cons', 'gins', 'icon', 'ions',
  'ling', 'lino', 'lins', 'lion', 'loci', 'logs', 'loin', 'long',
  'nils', 'nogs', 'noil', 'oils', 'sign', 'silo', 'sing', 'slog',
  'snog', 'soil', 'soli', 'song', 'cions', 'cling', 'clogs', 'clons',
  'coign', 'coils', 'coins', 'colin', 'icons', 'incog', 'lingo', 'lings',
  'linos', 'lions', 'logic', 'loins', 'longs', 'nicol', 'noils', 'scion',
  'sling', 'sonic', 'clings', 'coigns', 'colins', 'cosign', 'incogs', 'logics',
  'losing', 'nicols', 'soling', 'closing',
  // FARMERS (82)
  'are', 'arf', 'arm', 'ars', 'ear', 'efs', 'emf', 'ems',
  'era', 'err', 'ers', 'far', 'fas', 'fem', 'fer', 'mae',
  'mar', 'mas', 'ram', 'ras', 'ref', 'rem', 'res', 'sae',
  'sea', 'ser', 'ares', 'arfs', 'arms', 'ears', 'emfs',
  'eras', 'errs', 'fame', 'fare', 'farm', 'fear', 'fems', 'frae',
  'maes', 'mare', 'mars', 'mesa', 'rams', 'rare', 'rase', 'ream',
  'rear', 'refs', 'rems', 'safe', 'same', 'seam', 'sear', 'sera',
  'serf', 'armer', 'fames', 'farer', 'fares', 'farms', 'fears', 'frame',
  'mares', 'marse', 'maser', 'rares', 'raser', 'reams', 'rearm', 'rears',
  'safer', 'smear', 'armers', 'farers', 'farmer', 'framer', 'frames', 'rearms',
  'farmers', 'framers',
  // READING (142)
  'age', 'aid', 'ain', 'air', 'and', 'ane', 'ani', 'are',
  'dag', 'den', 'die', 'dig', 'din', 'ear', 'end', 'eng',
  'era', 'erg', 'ern', 'gad', 'gae', 'gan', 'gar', 'ged',
  'gen', 'gid', 'gie', 'gin', 'ire', 'nae', 'nag', 'rad',
  'rag', 'ran', 'red', 'reg', 'rei', 'ria', 'rid', 'rig',
  'rin', 'aged', 'ager', 'agin', 'aide', 'airn', 'arid', 'dang',
  'dare', 'darn', 'dean', 'dear', 'dine', 'ding', 'dire', 'drag',
  'dreg', 'earn', 'egad', 'gadi', 'gaed', 'gaen', 'gain', 'gane',
  'gear', 'gied', 'gien', 'gird', 'girn', 'gnar', 'grad', 'gran',
  'grid', 'grin', 'idea', 'ired', 'nard', 'near', 'nerd', 'nide',
  'rage', 'ragi', 'raid', 'rain', 'rand', 'rang', 'rani', 'read',
  'rein', 'rend', 'ride', 'rind', 'ring', 'aider', 'aired', 'anger',
  'deair', 'deign', 'dinar', 'diner', 'dinge', 'dirge', 'drain', 'garni',
  'grade', 'grain', 'grand', 'gride', 'grind', 'irade', 'nadir', 'raged',
  'range', 'ranid', 'redan', 'redia', 'regna', 'reign', 'renig', 'ridge',
  'danger', 'daring', 'dinger', 'earing', 'engird', 'gained', 'gainer', 'gander',
  'garden', 'girned', 'gradin', 'rained', 'ranged', 'reagin', 'reding', 'regain',
  'regina', 'ringed', 'deraign', 'gradine', 'grained', 'reading',
  // REACTOR (95)
  'ace', 'act', 'arc', 'are', 'art', 'ate', 'car', 'cat',
  'cor', 'cot', 'ear', 'eat', 'era', 'err', 'eta', 'oar',
  'oat', 'oca', 'ora', 'orc', 'ore', 'ort', 'rat', 'rec',
  'ret', 'roc', 'roe', 'rot', 'tae', 'tao', 'tar', 'tea',
  'toe', 'tor', 'acre', 'aero', 'arco', 'care', 'carr', 'cart',
  'cate', 'cero', 'coat', 'core', 'cote', 'orca', 'orra', 'race',
  'rare', 'rate', 'rato', 'rear', 'roar', 'rota', 'rote', 'tace',
  'taco', 'tare', 'taro', 'tear', 'toea', 'tora', 'torc', 'tore',
  'torr', 'actor', 'carer', 'caret', 'carte', 'cater', 'corer', 'crate',
  'crore', 'oater', 'ocrea', 'orate', 'racer', 'rater', 'react', 'recta',
  'recto', 'retro', 'taroc', 'tarre', 'terra', 'trace', 'carrot', 'carter',
  'coater', 'crater', 'rector', 'tracer', 'trocar', 'creator', 'reactor',
  // POCKETS (88)
  'cep', 'cop', 'cos', 'cot', 'kep', 'kop', 'kos', 'oes',
  'oke', 'ope', 'ops', 'opt', 'ose', 'pec', 'pes', 'pet',
  'pot', 'sec', 'set', 'sop', 'sot', 'toe', 'top', 'tsk',
  'ceps', 'coke', 'cope', 'cops', 'cost', 'cote', 'cots', 'epos',
  'keps', 'kept', 'keto', 'kops', 'okes', 'opes', 'opts', 'peck',
  'pecs', 'peso', 'pest', 'pets', 'pock', 'poet', 'poke', 'pose',
  'post', 'pots', 'scop', 'scot', 'sect', 'sept', 'skep', 'sock',
  'soke', 'spec', 'spot', 'step', 'stop', 'toes', 'toke', 'tope',
  'tops', 'cokes', 'copes', 'copse', 'coset', 'cotes', 'escot', 'estop',
  'pecks', 'pesto', 'pocks', 'poets', 'pokes', 'scope', 'speck', 'spoke',
  'stock', 'stoke', 'stope', 'tokes', 'topes', 'pocket', 'socket', 'pockets',
]
