// Anagrams rack deck — GENERATED by scripts/build-anagram-racks.mjs; do not
// edit by hand (re-run the script after changing its sources).
//
// 90 racks: common 7-letter words, each with at least 12 everyday
// family-safe solutions and at most 2 seven-letter anagrams. Valid words are every
// 3–7 letter Word Hunt dictionary word buildable from some rack (4340 words).

export const ANAGRAM_RACK_WORDS = [
  'another', 'article', 'bearing', 'bracket', 'breathe', 'candles', 'caption', 'capture',
  'castles', 'central', 'charges', 'climate', 'compare', 'crafted', 'crashed', 'crawled',
  'creator', 'credits', 'dancers', 'debates', 'details', 'display', 'fathers', 'floated',
  'fortune', 'garment', 'granted', 'grasped', 'greatly', 'harvest', 'hunters', 'inflate',
  'isolate', 'largest', 'located', 'longest', 'marched', 'masters', 'matches', 'mistake',
  'monster', 'network', 'neutral', 'notable', 'operate', 'overlap', 'panther', 'partner',
  'pastime', 'pattern', 'payment', 'peanuts', 'penalty', 'permits', 'planets', 'plastic',
  'pointed', 'postman', 'private', 'readily', 'repeats', 'respond', 'roasted', 'routine',
  'scatter', 'section', 'setback', 'smarter', 'soldier', 'sparkle', 'special', 'sprayed',
  'stellar', 'striped', 'sweater', 'tablets', 'tadpole', 'tangled', 'targets', 'therapy',
  'thermal', 'toaster', 'towards', 'trading', 'tragedy', 'wallets', 'warmest', 'wasting',
  'watcher', 'wonders',
]

export const ANAGRAM_VALID_WORDS = `
  abed abet abets able ables ablest abo abri abs ace aced acerb aces ache ached aches acme acmes
  acne acned acnes acold acre acred acres act acted actin action actor acts acute acuter adept
  adit adits ado adopt adore adores ados ads aedes aeon aerily aero aery aether afresh aft after
  afters age aged agent ager agers ages agin agist aglet aglets agley agly ahem aid aide aider
  aides aids ail ailed ails aim aims ain ains air aired airn airt airy ais aisle aisled ait aits
  aiver alb albs alder ale alec alecs alef alert alerts ales alien alif aline alist alit all alls
  alme almeh aloe aloes aloft alone alp alps als also alt alter alters alto altos alts amen ament
  ami amice amie amies amis amp amps and ands ane anes angel anger angle angled angst ani anil
  anile anis anole another ant ante anted antes anther anti antic antis antler antre ants anus
  any ape aped aper apercu apers apery apes apices aplenty apod aport apres apse apt apter aptly
  arb arc arced arch arched arches arco arcs ardent are areic ares arete aretes arf arfs argent
  argle argles argyle arid aridly ariel aril ariled ark arks arles arm armed armer armers armet
  armets armlet armrest arms arose arpen arpent arrest ars art artel artels article arts arty
  arvo aryl ascend asci ash ashed aside ask asker asp aspen asper aspic ass assert asset aster
  asters ate atelic ates atom atoms atone atoner atonic atop atopic atrip att aunt aunts ave aver
  avers avert averts aves avo awe awed awee awes awing awl awls awn awns aye ayes ays back backer
  backs backset bad bade bads bag bah baht bairn bake baker bakes bal bale bales bals ban bane
  bang banger bani bar bare barge baring bark barn bas base based bask basket bast baste basted
  bat bate bated bates bath bathe bather baton bats batt battle battles batts bead beads beak
  beaks bean beano bear bearing beast beat beater beats beck becks bed beds bee beer bees beet
  beets beg began begin being bel bels belt belts ben bent berate beret berg berth bertha beset
  best bestead bested bet beta betas beth beton bets betta bettas bier big bin bine binge binger
  blae blase blast blat blate blats bleat bleats blent blest blet blets bloat blot boa boat
  boatel bola bole bolt bone bot bota botel bra brace bracket bract brae brag brain brake bran
  brat break breath breathe bree bren brie brig brin brine bring cab caber cabs cad cade cades
  cadet cadre cadres cads cafe cage cager cagers cages cain cake cakes calends calm calo cam came
  camel cameo cames camlet camp camper campo cams can candle candles cane caned caner caners
  canes cans cant canter cantle canto cap cape caper capes capo capon caps caption capture caput
  car carb card cards care cared carer cares caret carets cark carl carle carn carnet carns carom
  carp carpet carr carrot cars carse cart carte carted cartel carter cartes carts case cased
  casern cases cash cashed cask casket cast caste caster castes castle castles casts cat cate
  cater caters cates cation catnip cats caw cawed cedar cedarn cedars cedi cedis ceil ceils cel
  cels celt celts cent cental cento centos centra central cents cep ceps ceria cero cess cesta
  cestas cesti cestoi chad chads cham chams char chard chards chare chared chares charge charges
  charm charmed chars chart chase chased chaser chasm chaste chat chats chaw chawer cheat cheats
  chert chest chew ciao cider ciders cine cines cion cions cire cires cis cist cite cited citer
  citers cites citral clad clade clades clads claim clam clan clans clap claps clapt claret clasp
  claspt class clast clasts claw clawed clawer clean cleans clear cleat cleats clew climate clime
  clip clips clipt clod clot coal coaled coapt coat coated coater coati cod coda code coed coin
  coins col cola cold cole colead coled colt coma comae come comer comp compare con cone cones
  coni conies cons conte contes cop cope coper copra cor core corer corm cos coset cosie cosine
  cost cot cotan cote coted cotes cots crab cradle craft crafted crag crags crake cram cramp
  crane craned cranes crap crape crash crashed crate crated crater crates craw crawl crawled
  creak cream creator credal credit credits crept crest crew cried cries cris crop crore cruet
  crwth cue cup cur curate cure curet curt cut cute cuter dab dabs dace daces daft dafter dag
  dags dah dahs daily dairy dais daisy dal dale dales dals dam dame dance dancer dancers dances
  dang danger dangle dap daps dare dares daring darn darns dart darting darts dash dasher date
  dater daters dates dating dato datos daw daws dawt dawts day days deaf deair deal deals dealt
  dean deans dear dearly dears deary deash deasil deb debase debate debates debs debt debts decaf
  decal decals declaw deco dee dees deet deets defat deft degas deil deils deist del delay delf
  delft deli delis delist dels delta deltas den dens dent dental depot derail derat derats deray
  derays derm derma desalt detail details dew dewar dews dey deys dial dialer dials diary dice
  dicer dicers dices die diel dies diet diets dig dilate dilates din dinar dine ding dint diol
  diols dip dipnet dips dipt dire direct directs direly direst dirl dirls dirt dirts dis disc
  display distal dit dita ditas dite dites dits doat doats doc doe doer doers does doest doit dol
  dolce dole doles dols dolt don done dons dopa dope doper dopers dopes dor dore dories dorp
  dorps dors dorsa dorsel dos dose doser dost dot dotal dote doter doters dotes dots dow dower
  dowers down downer downers downs dows dowse dowser drachm draft drag dragnet drags drail drain
  dram drape drapes drapey drat drats draw drawl draws dray drays dream dreg dregs drest drew
  dries driest drily drip drips dript drone drones drop drops drown drowns drowse dry drys dye
  dyer dyers dyes each ear earing earl earls early earn earns ears earth earths earthy ease eased
  east easter easts easy eat eater eaters eath eats eau ebon echard echards eclair eclat eclats
  ecru ecu edgy edh edhs edict edicts edit edits efs eft efts egad egads egal ego egos eidos
  elain elan eland elands elans eld elds elf elfin elint elk elks ell ells elm els eluant elytra
  emic emir emirs emit emits empty ems enact end endow endows ends eng engram engs enol enols
  enorm enow enows enrapt ens entail entia entrap eon eons eosin epact epha epic epical epics
  epos era eras erase ere erg ergs erica ern erns eros err errant errs ers erst eruct erupt escar
  eschar escot eskar espial esprit espy ess ester estral eta etalon etape etapes etas etch eth
  ether eths etic etna etnas etui etyma euro ewe ewer ewers ewes eyas eyra eyras face faced facer
  facet fact fad fade fader fado fail fain faint fan fane far farce farced fard fare fared fares
  fart farted farts fas fash fast faster fat fate fated fates father fathers fats feal fear fears
  feast feat feats fed feh fehs feint felt fen feod fer fern fet feta fetal fetas fetial fetor
  fets feu fiat fie fil fila file filet fin final finale fine fit flan flat flea fled flint flit
  flite float floated floe flota foal foaled foe foetal folate fold fon font for fore fort forte
  fortune fou fount four fracted frae frat frats fresh fret frets fro froe front fun fur futon
  gab gad gadi gads gae gaed gaen gaes gain gainer gains gainst gait gaits gal gale gales gals
  gam game gamer gan gander gane gap gape gaped gaper gapers gapes gaps gar garb garden garment
  garnet garni gars gas gash gasher gasp gasped gasper gast gaster gat gate gated gates gats gay
  gayer gear gears ged geds gel gelant geld gels gelt gelts gem gen gens gent gents gerah gerahs
  germ german gest get geta getas gets gey giant giants gib gibe giber gid gie gien gin gins gird
  girn girt gist git gits glad glade gland glare glares glary glean gled glen glens gley glost
  gnar gnat gnats gnaw gnaws goes gone got grab graben grace graces grad grade grades gradin
  grads grain gram gran grand grant granted grape grapes grasp grasped grat grate grated grates
  gratin gray grayed great greatly greats grey grid grin grind grit gyral gyrate gyrated gyre
  gyred had hade hades hae haed haem haems haen haes haet haets haft hafter hafters hafts hag
  hags hale haler halm halt halter ham hame hames hamlet hams hant hao hap hapten hard hards hare
  hared harem hares harl harm harmed harp harpy hart harts harvest has hast haste hat hate hater
  haters hates hats have haver havers haves haw hay hayer head heads heal heap hear heard hears
  heart hearts hearty heat heater heats hebe heft hefts helm hem hemal hems hen hens hent hents
  hep her herb herd herds here hereat herl herm herma hern herns hero heron hers hes hest het
  hets hew hey hoar hoe hoer hon hone honer hora horn hornet hot hue hues hun huns hunt hunter
  hunters hunts hurst hurt hurts hut huts hyp hype hyper hyte ice iced ices icon icones icons
  idea ideal ideals ideas ides idle idler idlers idles idlest idly idol idols ids idyl idyls ikat
  ikats ilea ileac imp impaste imprest imps inapt incest inept inert inflate inlet inro ins
  insect inset inter into intro inure ion ions iota iotas irade irate ire ired ires iron irone
  isle isled islet ism isolate istle item items its kab kabs kae kaes kale kales kame kames kami
  kart kas kat kats kbar kea keas kebar kelp kelps ken keno kent kep keps kerb kern keto kismat
  kismet kist kit kite kites kits knew knot know knower kor kore krone lab labs lac lace laced
  lacer laces lacier lacs lad lade laden ladens lader lades ladies lads lady laevo lag lagend
  lager lagers lags laic laics laid lain lair laird laired lake laker lakers lakes lam lame lamer
  lance lanced lancer lances lancet land lands lane lanes lang lap lapis laps lapse lapser lar
  lard lardy lares large larges largest lari lark larks lars las lase lased laser lases lass last
  lasted laster lasts lat late lated laten latens later latest lath lathe lather lati lats latte
  lattes lav lave laver law lawed laws lay layed layer lays lea lead leads leady leaf leak leaks
  leal lean leans leant leap leaps leapt lear learn learnt lears leary leas least leasts led left
  leg legs lehr lei leis lek leks lend lends leno lenos lens lent lento lentos lept lepta less
  lest let lets leu lev leva levo lewd ley liane liar liard lice lid lidar lido lidos lids lie
  lied lief lien lier liers lies life lift lima lime lin line lint lip lipase lips lira lire lis
  lisp list listed lit litas lite liter litre lits load loaf loafed loan lob lobate lobe loca
  locate located lode lodes loft lofted log loge loges logs lone long longe longes longest longs
  lop lope loped loper lord lords lore lores lories loris lose loser lost lot lota lotas loti
  lots love lover luna lunar lunate lune lunet lunt lure lute lutea lyard lyart lye lyrate lyre
  mac mace maced macer maces mach mache maches machs macle macro macs mad made madre mae maes mag
  mage magnet mail maile maist make makes male malic malice malt man mane mange manger mano manos
  mans many map maps mar marc march marched mare mares marge margent marl mars marse marses mart
  marten marts mas maser masers mash mask mason mass masse mast master masters masts mat match
  matches mate mater maters mates matey math maths matres mats maw maws may mead meal mean meant
  meany meat meats meaty med mel melic melt men meno menta mentor mentors merit merits merl mesa
  mesas mesh meson mess met meta metal meth meths metical metis metro metros mew mews mica mice
  mike mikes mil mile milt mir mire mires mirs mis misate mise miseat miser mist mistake mister
  mite miter miters mites mitre mitres moa moan moans moas moat moats moc mon monas mons monster
  monte montes mop mope moper mops mor mora morae more mores morn morns mors morse mort morts mos
  most moste mot mote motes mots myna nab nabe nacre nacred nacres nadir nae nag nags nah naif
  nail naled naleds nam name namer naoi naos nap nape napes naps narc narcs nard nards nares
  nates natter nature naw nay neap neaps near nears neat neath neatly neats neb nectar neif neist
  nema nerd nerds nerts nest nestor net netop nets nett network neural neutral new news newt nib
  nice nicest nide nil nip nipa nit nite niter nites nitre nitro nits nob noble nod node nodes
  nodi nods noel noels noes noetic nog nogs noh noir noise nom noma nomas nome nomes noms nope
  nor nori norite norm norms north nos nose nosed not nota notable notal note noted noter noters
  notes nother notice notices now nows nowt nth nurl nurse nus nut nuts oaf oar oared oars oast
  oat oaten oater oaters oath oats obe oblate oca ocrea octad octal octan ode odea odes ods oes
  oft often ofter ogle ogles oil oiled oiler oilers oils oke old older oldie oldies olds ole olea
  oles omen omens omer omers oms once one ones ons onset ontic opal ope oped open opens opera
  operate opes opine opined ops opt opted optic opts ora orad oral orate orated orates orc orca
  ore oread oreads ores oriel oriels orient orle orles ornate orra ors ort orts osar oscine ose
  osier osteal ostia other otic ottar ottars otter otters our ourie out outer outre ova oval over
  overlap owe owed owes own owned owner owners owns owse owsen pac pace pacer paces pacs pact
  paction pacts pad padi padis padle padre padres pads page paged pager pagers pages pah paid
  pail pails pain paint pair paise pal pale paled paler pales palest palet palets pals palsy paly
  pam pams pan pane panel panels panes panic pans pant panther panto pantos pants panty par pard
  pards pardy pare pared parent pareo parer pares pareu parge parged parges park parks parle
  parles parol parole parr pars parse parsed part partner parts party parve parvo pas pase past
  paste pastel paster pastie pastil pastime pat pate pated paten patens patent pater paters pates
  path patin patio patly pats patten patter pattern paty pause pave paver pay payed payer payers
  payment pays pea peag peags peak peaks peal peals pean peans peanut peanuts pear pearl pearls
  pears peart peas pease peat peats peaty pec pecs ped pedal pedalo pedro pedros peds pee peer
  peers pees peg pegs peh pein pelota pelt pelts pen penal penalty pend pends pens pent pentyl
  peon peons per perdy perea peri peris perk perks perm permit permits perms perse person pert
  pes peseta peso pest pester pet petal petals peter peters pets petsai phat pht pia pial pian
  piano pias pic pica pical picas pice picot pics pie pied pier piers pies pieta pietas pile
  pilea piles pily pima pimas pin pina pine pined pinot pint pinta pinto pion pirate pis piste
  pit pita pitas piton pits place places plaice plaices plaid plaids plait plaits plan plane
  planes planet planets plans plant plants plastic plat plate plated platen platens plates plats
  platy play plays plea plead pleas pleat pleats pled plena plenty plica plicae plie plies plod
  plot plover ply pod podite pods poem poet poi poind point pointe pointed pol polar pole poled
  poler pom pomace pome poms pond ponder ponders ponds pone pones ponied pons pore pored pores
  port pose posed poser post postman pot potman pots pram prao prase prat prate prater prates
  prats prau pray prayed prays preact precut pree prees presa prese preset prest prey preys pride
  prides pried pries priest prim prime primes prims prise prised prism private privet pro proa
  prod prods proem prole prom prone pros prose prosed protea prove pruta pry psi puce pun puna
  punas puns punt punts pur pure pus put puts pya pyas pye pyes pyre pyres race raced racer races
  rachet rack racket rad rads raft rafted rafts rag rage raged rages ragi ragmen rags rah raid
  rail railed rain rake rakes rale rales ram ramet ramets ramp rams ran rance rances rand rands
  rang range ranged rani ranid rant ranted ranter rap rape raped raper rapes raphe raps rapt rare
  rares rarest ras rase rased raser rases rash rasp rasped raspy raster rat ratch rate rated
  ratel ratels rater raters rates rath rathe rating rato ratos rats ratten rave ravel raves raw
  rawest raws ray rayed rays reach react reactor reacts read readily reads ready reagin real
  realm reals realty ream reams reap reaps rear rearm rearms rears reb rebate rec recant recap
  recast recital reck reclad recs recta rectal recti recto rector recut red redact redan redans
  redia redial redip redips redipt redly redo redon redons redos reds ree rees reest ref refs
  reft reg regain regal regina regma regna regs rehab reheat rei reign rein reis relaid relay
  relic relict relit rely rem reman remap remit remits rems renal rend rends renig rent rental
  rents reoil reoils rep repast repay repays repeat repeats repo repos repot reps reptant reran
  res resaw resay reseat reset resew resh resid resod resold resow resown respond rest rests ret
  retack retag retags retail retape retapes retch rete retia retial retro rets rev revs rewet
  rewets rewon rhea rheas rho rhus rhyta ria rial riant rib rice riced rices rictal rid ride
  rides ridley rids riel riels rig rile riled riles riley rim rime rimes rims rin rind ring riot
  rip ripe riped ripes ripest rips rise rite rites rive rivet riyal road roads roam roan roar
  roast roasted roc rod rode rods roe roes roil roiled roils role roles rom romp roms rope roped
  ropes rose rosed roset rot rota rotas rotate rotates rote rotes roti rots rotte rottes roue
  rouen rout route routine rove row rowed rowen rowens rows rue rues ruin rule run rune runes
  runlet runs runt runts ruse rush rust rut ruth ruths rutin ruts rya ryas rye ryes sab sabe
  sabed sable sac sachem sachet sack sacred sacs sad sade sadhe sadi sadly sae safe safer sag
  sage sager saice said sail sailed sain saint sake saker saki sal sale salep sales salic sall
  sallet salp salpid sals salt salted salter saltie salts same samech samek samite samp sand
  sander sane saned saner sang santo sap sapid sard saree sarge sark sarod sarode sat sate sated
  satem sates sati satin sating sau saute save saver saw sawer sawing sawn say sayer sayid scab
  scad scag scald scale scaled scales scalp scam scan scape scar scare scared scart scat scathe
  scats scatt scatter scena scend scent schema scion scone scot scrag scried sea seabed seal
  seals seam seams sear search sears seas seat seated seater seats sec secs sect section sects
  sedan sedate see seed seep seer seg segno sego sei sel sell sels semi sen send sendal senor
  sent senti sepal sepia sepic sept septa septal ser sera serac seral serape sere serf sermon
  serow sers set seta setae setal setback seton sets sett setup sew sewar sewer sewn sha shad
  shade shader shaft shag sham shame shard share shared shat shave shaver she shea sheaf shear
  shed shent sherd shred shun shunt shunter shut shute sial sic sice side sidle sidler sign sike
  sild silo siloed silt silted sim sima simp simper sin since sine sing sip sipe siped sir sire
  sired sit site sited ska skat skate skelp skep ski skim skit skite slab slag slake slaker slant
  slap slat slate slated slater slates slats slaw slay sled slept slew slice slid slide slider
  slier slip slipe slipt slit sloe slog sloid slot sly smart smarter smarts smear smears smew
  smit smite smiter smote snag snap snare snared snaw sneap sned snit snog snore snored snort
  snot snow snowed soap soar soared sod soda soil soiled sol sola solate sold solder soldi
  soldier sole soled solei soli solid solider soma some son sonde sonder sone song sonic sop sora
  sord sore sorel sori sorn sorned sort sorted sot sow sowar sowed sower sown spa space spade
  spader spae spaed spail spait spake spale span spar spare spared sparge sparged spark sparkle
  spat spate spay spayed speak spean spear spec special sped speer speil speir spelt spend spent
  sperm spica spicae spice spider spied spiel spier spile spilt spire spired spirem spirt spirted
  spit spital spite spited splake splat splay splent splice split spode spore spored spot sprag
  sprat spray sprayed spread spree sprit sprite spry spue spun sputa spy sri stab stable stack
  stacte stade stag stage stager staid staig stain stake stale staled staler stales stall stamp
  stane stang staple star stare stared starer stares stars start starve stat state stater stator
  stave staw stead steak steal steals steam steams steed steep steer stein stela stelai stelar
  stella stellar stem stems steno step stere steric stern stet stew stied stile stime sting stipe
  stiped stir stirp stoa stoae stoai stoat stoic stole stolen stoma stomp stone stoner stop store
  stored storm stow strafe strap straw stream streams strep strew stride strip stripe striped
  strode strow stun stupa stupe sue suer suet sun sup supe sure swag swain swale swam swan swang
  sward sware swarm swart swat swear sweat sweater sweer sweet swell swig swing sword swore sworn
  swot syli tab taber tabes table tables tablet tablets tabs tace taces tacet tach tache taches
  tachs tack tacker tacks taco tact tacts tad tadpole tads tae tael taels tag tags tahr tahrs
  tail tailed tailer tails tain tains take taker takes talc talced talcs tale taler talers tales
  tali tall taller talon tam tame tamer tamers tames tamis tamp tampon tampons tamps tams tan
  tang tanged tangle tangled tangs tanrec tans tao taos tap tape taped taper tapers tapes tapir
  tapis taps tar tardo tardy tare tared tares targe targes target targets taring tarn taro taroc
  taros tarot tarots tarp tarps tarre tarres tars tart tarts tas task tass tasse tassel taste
  taster tat tate tater taters tates tats tau taupe taupes taus tav tavs taw tawer tawers tawing
  taws tawse tawsing tea teach teacup teak teaks teal teals team teams tear tears teary teas
  tease teased teaser teat teats tecta ted teds tee teed tees teg tegs teind tel tela telia telic
  tell tells teloi telos tels telson temp tempi temps ten tenail tend tenia tenor tenors tenour
  tens tensor tent tepa tepal tepals tepas tephra tepid terai teraph terga tergal term terms tern
  terns terra terras terse tesla teslas test testa tet tetra tetras tets tew tews thae thaler
  than thane tharm thaw thawer the thebe theca thee them then thenar thens therapy there therm
  thermal thew they tho thorn thrave thraves thraw threap three threw thro throe throne thru thus
  thy tic tical ticals tics tidal tide tides tie tied tier tiers ties tike tikes til tilde tildes
  tile tiled tiler tiles tils time timer timers times tin tine tinea tineal tined tines ting
  tings tins tip tips tire tired tires tirl tiro tis toad toads toast toaster tocsin tod tods toe
  toea toed toes tofu tog togs toil toile toiles toils toke token toker tola tolan tolane tolas
  told tole toled toles tom toman tomans tome tomes toms ton tonal tondi tone toned toner toners
  tones tong tongs tonic tonics tonier tons top tope toped topee toper topi topic tops tor tora
  torah toras torc tore tores tori torn torr tors torsade torse tort torte tortes torts tost tot
  tote toter toters totes tots tour tow toward towards tower town tows trace traced tracer traces
  track tract tracts trad trade trades trading tragedy tragi trail train tram tramel trams trance
  trap trapes traps trapt trash trass trave traves tray tread treads treat treats tree trees tref
  trefah trek trend trepan trepid tress tret trets trews trey triac triad trial trice triced
  trices tried tries trig trim trims trine trio trip tripe tripes trips triune trocar trod trode
  troke trona trone trones trop trope trot trots trow trows truce true trues try tsade tsadi tsar
  tsars tsk tui tule tun tuna tunas tune tuner tuners tunes tuns tup tups turf turn turns tush
  twa twae twaes twain twains twang twangs twas twee twig twigs twin twins two twos tye tyer
  tympan tyne typal type tyre tyred ulan ulna ulnae ulnar ultra unapt unit unite uniter unlet
  unreal unrest uns unseat unset unstep untie unto upas uprate ups upsent upset uptear urate urea
  ureal urine urn urns use user usher usnea uta utas uteri uts vair vale valor vapor var vars vas
  vase vast vaster vat vats veal vela velar vera verst vert verts vest vesta vet vets via vie
  vier viper vita vitae voe volar vole wad wade wader wads wae waes wag wags wain wains waist
  wait waits wale waled waler wales wall wallet wallets walls wame wames wan wans want wants war
  ward wards ware wared wares warm warmest warms wars wart warts was wast waste waster wasting
  wat watch watcher water waters wats weal weald weals wear wears wecht wed weds wee weer wees
  weest weet weets weld well wells welt welts wen wend wends wens went were wert west wester wet
  wets wha what wheat whet wig wigan wigans wigs win wing wings wins wis wist wit witan wits woad
  woads woe woes wok woke woken won wonder wonders wonk wons wont word words wore work worn worse
  worsen worst wort worts wos wost wot wots wrath wreath wren wrens wrest wretch wrote yager yah
  yaird yald yam yamen yap yaps yar yard yards yare yea yeah yean year years yeas yeh yeld yelp
  yen yenta yep yes yet yid yids yield yip yips yird
`.split(/\s+/).filter(Boolean)
