// CHAMELEON topic cards: a public topic plus a 4×4 grid of 16 words. Each
// round one word is the secret — sealed to every player except the Chameleon
// (see ChameleonGame.jsx). Rounds store the card INDEX and the room's seen
// history (`games/{id}/seen/chameleon`) is keyed by it, so this list is
// APPEND-ONLY: never reorder or delete cards, and never reorder a card's
// words (the secret is a word index 0–15). Add new cards at the end.
//
// Words are uppercase, at most 12 characters (a 4-column grid on a phone),
// unique within their card. src/lib/decks/chameleon.test.js enforces this and
// runs every word through the shared moderation denylist.

export const CHAMELEON_CARDS = [
  { topic: 'FOOD', words: ['PIZZA', 'BURGER', 'PASTA', 'SUSHI', 'TACOS', 'SALAD', 'SOUP', 'CURRY', 'STEAK', 'NOODLES', 'SANDWICH', 'PANCAKES', 'OMELETTE', 'RISOTTO', 'KEBAB', 'DUMPLINGS'] },
  { topic: 'FRUIT', words: ['APPLE', 'BANANA', 'CHERRY', 'GRAPE', 'LEMON', 'MANGO', 'ORANGE', 'PEACH', 'PEAR', 'PLUM', 'KIWI', 'MELON', 'COCONUT', 'PINEAPPLE', 'STRAWBERRY', 'LIME'] },
  { topic: 'VEGETABLES', words: ['CARROT', 'POTATO', 'ONION', 'GARLIC', 'PEPPER', 'TOMATO', 'CABBAGE', 'SPINACH', 'LETTUCE', 'CELERY', 'BROCCOLI', 'PEAS', 'CORN', 'PUMPKIN', 'MUSHROOM', 'CUCUMBER'] },
  { topic: 'DESSERTS', words: ['CAKE', 'COOKIE', 'BROWNIE', 'CUPCAKE', 'DONUT', 'ICE CREAM', 'PIE', 'PUDDING', 'MOUSSE', 'MUFFIN', 'WAFFLE', 'CHEESECAKE', 'TIRAMISU', 'JELLY', 'CANDY', 'FUDGE'] },
  { topic: 'DRINKS', words: ['WATER', 'MILK', 'COFFEE', 'TEA', 'LEMONADE', 'JUICE', 'SMOOTHIE', 'COLA', 'COCOA', 'MILKSHAKE', 'SODA', 'ICED TEA', 'PUNCH', 'KOMBUCHA', 'SLUSHIE', 'ESPRESSO'] },
  { topic: 'BREAKFAST', words: ['CEREAL', 'TOAST', 'BACON', 'EGGS', 'PANCAKES', 'WAFFLES', 'PORRIDGE', 'YOGURT', 'CROISSANT', 'BAGEL', 'SAUSAGE', 'HASH BROWNS', 'MUESLI', 'FRENCH TOAST', 'JAM', 'GRANOLA'] },
  { topic: 'PIZZA TOPPINGS', words: ['CHEESE', 'PEPPERONI', 'HAM', 'PINEAPPLE', 'MUSHROOM', 'OLIVES', 'ONION', 'PEPPERS', 'SAUSAGE', 'BACON', 'CHICKEN', 'SPINACH', 'ANCHOVIES', 'TOMATO', 'JALAPENO', 'BASIL'] },
  { topic: 'WILD ANIMALS', words: ['LION', 'TIGER', 'ELEPHANT', 'GIRAFFE', 'ZEBRA', 'MONKEY', 'GORILLA', 'HIPPO', 'RHINO', 'BEAR', 'WOLF', 'FOX', 'KANGAROO', 'KOALA', 'PANDA', 'CHEETAH'] },
  { topic: 'ON THE FARM', words: ['COW', 'PIG', 'SHEEP', 'GOAT', 'HORSE', 'CHICKEN', 'DUCK', 'GOOSE', 'TURKEY', 'DONKEY', 'LLAMA', 'ROOSTER', 'SHEEPDOG', 'TRACTOR', 'BARN', 'SCARECROW'] },
  { topic: 'SEA CREATURES', words: ['SHARK', 'WHALE', 'DOLPHIN', 'OCTOPUS', 'SQUID', 'CRAB', 'LOBSTER', 'JELLYFISH', 'STARFISH', 'SEAHORSE', 'TURTLE', 'SEAL', 'CLOWNFISH', 'EEL', 'STINGRAY', 'SHRIMP'] },
  { topic: 'BIRDS', words: ['EAGLE', 'OWL', 'PARROT', 'PENGUIN', 'FLAMINGO', 'PEACOCK', 'SWAN', 'CROW', 'PIGEON', 'ROBIN', 'HAWK', 'OSTRICH', 'TOUCAN', 'HUMMINGBIRD', 'WOODPECKER', 'PELICAN'] },
  { topic: 'BUGS', words: ['ANT', 'BEE', 'WASP', 'BUTTERFLY', 'MOTH', 'BEETLE', 'LADYBUG', 'SPIDER', 'FLY', 'MOSQUITO', 'GRASSHOPPER', 'CRICKET', 'DRAGONFLY', 'CATERPILLAR', 'SNAIL', 'WORM'] },
  { topic: 'PETS', words: ['DOG', 'CAT', 'HAMSTER', 'GOLDFISH', 'RABBIT', 'PARROT', 'TORTOISE', 'GUINEA PIG', 'MOUSE', 'SNAKE', 'LIZARD', 'FERRET', 'CANARY', 'PONY', 'FROG', 'TARANTULA'] },
  { topic: 'SPORTS', words: ['SOCCER', 'TENNIS', 'GOLF', 'RUGBY', 'CRICKET', 'BASEBALL', 'BASKETBALL', 'HOCKEY', 'BOXING', 'SKIING', 'SURFING', 'CYCLING', 'ROWING', 'SWIMMING', 'ARCHERY', 'VOLLEYBALL'] },
  { topic: 'SPORTS GEAR', words: ['BALL', 'BAT', 'RACKET', 'HELMET', 'GLOVES', 'NET', 'GOAL', 'SKATES', 'SKIS', 'PADDLE', 'GOLF CLUB', 'WHISTLE', 'STOPWATCH', 'TROPHY', 'MEDAL', 'JERSEY'] },
  { topic: 'INSTRUMENTS', words: ['PIANO', 'GUITAR', 'DRUMS', 'VIOLIN', 'CELLO', 'FLUTE', 'TRUMPET', 'SAXOPHONE', 'HARP', 'TUBA', 'CLARINET', 'BANJO', 'UKULELE', 'HARMONICA', 'ACCORDION', 'TRIANGLE'] },
  { topic: 'MUSIC STYLES', words: ['POP', 'ROCK', 'JAZZ', 'BLUES', 'RAP', 'COUNTRY', 'REGGAE', 'OPERA', 'DISCO', 'FOLK', 'SOUL', 'FUNK', 'METAL', 'CLASSICAL', 'TECHNO', 'GOSPEL'] },
  { topic: 'JOBS', words: ['DOCTOR', 'NURSE', 'TEACHER', 'CHEF', 'PILOT', 'FARMER', 'DENTIST', 'PLUMBER', 'LAWYER', 'JUDGE', 'BAKER', 'ARTIST', 'BUILDER', 'SCIENTIST', 'FIREFIGHTER', 'POLICE'] },
  { topic: 'SCHOOL', words: ['MATH', 'SCIENCE', 'HISTORY', 'ART', 'MUSIC', 'ENGLISH', 'GEOGRAPHY', 'SPANISH', 'DRAMA', 'GYM', 'RECESS', 'LUNCHBOX', 'HOMEWORK', 'EXAM', 'LIBRARY', 'CHALKBOARD'] },
  { topic: 'COUNTRIES', words: ['FRANCE', 'ITALY', 'SPAIN', 'JAPAN', 'CHINA', 'INDIA', 'BRAZIL', 'MEXICO', 'CANADA', 'EGYPT', 'KENYA', 'GREECE', 'GERMANY', 'AUSTRALIA', 'NORWAY', 'PERU'] },
  { topic: 'CITIES', words: ['PARIS', 'LONDON', 'ROME', 'TOKYO', 'NEW YORK', 'SYDNEY', 'CAIRO', 'DUBAI', 'MUMBAI', 'BEIJING', 'ISTANBUL', 'BERLIN', 'MADRID', 'TORONTO', 'RIO', 'VENICE'] },
  { topic: 'LANDMARKS', words: ['EIFFEL TOWER', 'BIG BEN', 'COLOSSEUM', 'PYRAMIDS', 'TAJ MAHAL', 'STONEHENGE', 'GREAT WALL', 'ACROPOLIS', 'SPHINX', 'PETRA', 'ALCATRAZ', 'LOUVRE', 'MACHU PICCHU', 'GOLDEN GATE', 'OPERA HOUSE', 'MT RUSHMORE'] },
  { topic: 'WEATHER', words: ['SUNNY', 'RAIN', 'SNOW', 'HAIL', 'FOG', 'WIND', 'STORM', 'THUNDER', 'LIGHTNING', 'RAINBOW', 'TORNADO', 'HURRICANE', 'DRIZZLE', 'FROST', 'HEATWAVE', 'BLIZZARD'] },
  { topic: 'TRANSPORT', words: ['CAR', 'BUS', 'TRAIN', 'PLANE', 'BOAT', 'BICYCLE', 'TAXI', 'TRAM', 'SUBWAY', 'SCOOTER', 'TRUCK', 'HELICOPTER', 'SHIP', 'ROCKET', 'MOTORBIKE', 'CANOE'] },
  { topic: 'CLOTHES', words: ['SHIRT', 'JEANS', 'DRESS', 'SKIRT', 'JACKET', 'COAT', 'SWEATER', 'HOODIE', 'SHORTS', 'SOCKS', 'SCARF', 'GLOVES', 'HAT', 'TIE', 'PAJAMAS', 'UNIFORM'] },
  { topic: 'IN THE KITCHEN', words: ['FORK', 'KNIFE', 'SPOON', 'PLATE', 'BOWL', 'CUP', 'KETTLE', 'TOASTER', 'OVEN', 'FRIDGE', 'FRYING PAN', 'WHISK', 'BLENDER', 'SPATULA', 'LADLE', 'SINK'] },
  { topic: 'TOOLS', words: ['HAMMER', 'SAW', 'DRILL', 'WRENCH', 'PLIERS', 'SCREWDRIVER', 'TAPE', 'LADDER', 'SHOVEL', 'RAKE', 'AXE', 'CHISEL', 'NAIL', 'SCREW', 'SANDPAPER', 'TOOLBOX'] },
  { topic: 'FURNITURE', words: ['SOFA', 'BED', 'CHAIR', 'TABLE', 'DESK', 'LAMP', 'SHELF', 'WARDROBE', 'DRESSER', 'STOOL', 'BENCH', 'CRIB', 'HAMMOCK', 'BOOKCASE', 'MIRROR', 'RUG'] },
  { topic: 'ROOMS', words: ['KITCHEN', 'BEDROOM', 'BATHROOM', 'ATTIC', 'BASEMENT', 'GARAGE', 'HALLWAY', 'LIVING ROOM', 'DINING ROOM', 'OFFICE', 'PANTRY', 'LAUNDRY', 'BALCONY', 'PORCH', 'CELLAR', 'NURSERY'] },
  { topic: 'TOYS', words: ['DOLL', 'YO-YO', 'KITE', 'TEDDY BEAR', 'PUZZLE', 'BALL', 'SLINKY', 'ROBOT', 'TRAIN SET', 'MARBLES', 'JUMP ROPE', 'SPINNING TOP', 'BLOCKS', 'PUPPET', 'WATER GUN', 'RATTLE'] },
  { topic: 'BOARD GAMES', words: ['CHESS', 'CHECKERS', 'MONOPOLY', 'SCRABBLE', 'CLUE', 'BACKGAMMON', 'DOMINOES', 'RISK', 'SORRY', 'CONNECT FOUR', 'BATTLESHIP', 'MANCALA', 'GO', 'JENGA', 'TWISTER', 'LUDO'] },
  { topic: 'SPACE', words: ['SUN', 'MOON', 'MARS', 'VENUS', 'JUPITER', 'SATURN', 'COMET', 'ASTEROID', 'GALAXY', 'STAR', 'ROCKET', 'ASTRONAUT', 'ALIEN', 'BLACK HOLE', 'SATELLITE', 'ORBIT'] },
  { topic: 'MYTHICAL BEASTS', words: ['DRAGON', 'UNICORN', 'MERMAID', 'PHOENIX', 'GRIFFIN', 'CENTAUR', 'TROLL', 'GOBLIN', 'FAIRY', 'GIANT', 'CYCLOPS', 'VAMPIRE', 'WEREWOLF', 'YETI', 'KRAKEN', 'PEGASUS'] },
  { topic: 'FAIRY TALES', words: ['CINDERELLA', 'SNOW WHITE', 'RAPUNZEL', 'PINOCCHIO', 'PETER PAN', 'ALADDIN', 'GOLDILOCKS', 'HANSEL', 'GRETEL', 'THUMBELINA', 'BEANSTALK', 'THREE PIGS', 'BIG BAD WOLF', 'FROG PRINCE', 'THE BEAST', 'GINGERBREAD'] },
  { topic: 'SUPERHEROES', words: ['SUPERMAN', 'BATMAN', 'SPIDER-MAN', 'WONDER WOMAN', 'HULK', 'THOR', 'IRON MAN', 'THE FLASH', 'AQUAMAN', 'WOLVERINE', 'STORM', 'ROBIN', 'CYBORG', 'ANT-MAN', 'HAWKEYE', 'SUPERGIRL'] },
  { topic: 'CELEBRATIONS', words: ['BIRTHDAY', 'WEDDING', 'NEW YEAR', 'HALLOWEEN', 'CHRISTMAS', 'EASTER', 'DIWALI', 'HANUKKAH', 'EID', 'THANKSGIVING', 'VALENTINES', 'CARNIVAL', 'GRADUATION', 'ANNIVERSARY', 'HOLI', 'BABY SHOWER'] },
  { topic: 'AT THE BEACH', words: ['SAND', 'WAVES', 'SHELLS', 'TOWEL', 'SUNSCREEN', 'UMBRELLA', 'BUCKET', 'SPADE', 'SANDCASTLE', 'SURFBOARD', 'LIFEGUARD', 'SEAGULL', 'PIER', 'ICE CREAM', 'FLIP FLOPS', 'SUNGLASSES'] },
  { topic: 'CAMPING', words: ['TENT', 'CAMPFIRE', 'SMORES', 'LANTERN', 'COMPASS', 'MAP', 'BACKPACK', 'SLEEPING BAG', 'FLASHLIGHT', 'CANOE', 'HIKING', 'FISHING', 'BUG SPRAY', 'MARSHMALLOW', 'FIREWOOD', 'CABIN'] },
  { topic: 'FEELINGS', words: ['HAPPY', 'SAD', 'ANGRY', 'SCARED', 'EXCITED', 'BORED', 'NERVOUS', 'PROUD', 'JEALOUS', 'CONFUSED', 'SURPRISED', 'TIRED', 'CALM', 'LONELY', 'SILLY', 'GRUMPY'] },
  { topic: 'COLORS', words: ['RED', 'BLUE', 'GREEN', 'YELLOW', 'PURPLE', 'ORANGE', 'PINK', 'BROWN', 'BLACK', 'WHITE', 'GRAY', 'GOLD', 'SILVER', 'TURQUOISE', 'MAROON', 'BEIGE'] },
  { topic: 'SCIENCE', words: ['ATOM', 'MAGNET', 'GRAVITY', 'MICROSCOPE', 'TELESCOPE', 'VOLCANO', 'FOSSIL', 'CRYSTAL', 'ROBOT', 'DNA', 'ENERGY', 'ELECTRICITY', 'EXPERIMENT', 'LAB COAT', 'BATTERY', 'TEST TUBE'] },
  { topic: 'HALLOWEEN', words: ['GHOST', 'WITCH', 'ZOMBIE', 'MUMMY', 'SKELETON', 'PUMPKIN', 'BAT', 'SPIDER', 'BROOMSTICK', 'CAULDRON', 'COSTUME', 'CANDY', 'COBWEB', 'BLACK CAT', 'FULL MOON', 'GRAVEYARD'] },
  { topic: 'WINTER', words: ['SNOWMAN', 'SLED', 'SKATES', 'MITTENS', 'SCARF', 'IGLOO', 'ICICLE', 'SNOWFLAKE', 'BLIZZARD', 'FIREPLACE', 'COCOA', 'PENGUIN', 'SKI LIFT', 'SNOWBALL', 'BOOTS', 'POLAR BEAR'] },
  { topic: 'AIRPORT', words: ['PASSPORT', 'TICKET', 'SUITCASE', 'PILOT', 'RUNWAY', 'GATE', 'SECURITY', 'CUSTOMS', 'TERMINAL', 'TOWER', 'LOUNGE', 'BOARDING', 'JET LAG', 'DUTY FREE', 'TROLLEY', 'BAGGAGE'] },
  { topic: 'SUPERMARKET', words: ['CART', 'BASKET', 'CHECKOUT', 'CASHIER', 'RECEIPT', 'BARCODE', 'AISLE', 'FREEZER', 'BAKERY', 'DELI', 'COUPON', 'SHELF', 'SCALES', 'BAGS', 'PRODUCE', 'SAMPLES'] },
  { topic: 'HOSPITAL', words: ['DOCTOR', 'NURSE', 'AMBULANCE', 'BANDAGE', 'X-RAY', 'STETHOSCOPE', 'WHEELCHAIR', 'CAST', 'INJECTION', 'PILLS', 'SURGEON', 'THERMOMETER', 'PATIENT', 'STRETCHER', 'WARD', 'CRUTCHES'] },
  { topic: 'PIRATES', words: ['SHIP', 'TREASURE', 'PARROT', 'CANNON', 'SWORD', 'MAP', 'PLANK', 'CAPTAIN', 'ISLAND', 'ANCHOR', 'FLAG', 'EYEPATCH', 'HOOK', 'CHEST', 'COMPASS', 'CREW'] },
  { topic: 'CIRCUS', words: ['CLOWN', 'ACROBAT', 'JUGGLER', 'TRAPEZE', 'RINGMASTER', 'LION', 'ELEPHANT', 'TIGHTROPE', 'UNICYCLE', 'POPCORN', 'BIG TOP', 'MAGICIAN', 'STILTS', 'CANNONBALL', 'BALLOONS', 'FIRE EATER'] },
  { topic: 'WILD WEST', words: ['COWBOY', 'SHERIFF', 'HORSE', 'SALOON', 'RODEO', 'LASSO', 'CACTUS', 'DESERT', 'BADGE', 'STETSON', 'WAGON', 'OUTLAW', 'BOOTS', 'SPURS', 'RANCH', 'TUMBLEWEED'] },
  { topic: 'CASTLES', words: ['KNIGHT', 'CASTLE', 'KING', 'QUEEN', 'PRINCE', 'PRINCESS', 'DRAGON', 'SWORD', 'SHIELD', 'ARMOR', 'MOAT', 'TOWER', 'JESTER', 'HORSE', 'CROWN', 'WIZARD'] },
]
