// CODE WORDS deck — common, family-friendly single words (lowercase a–z,
// shown uppercase on the board). Many have more than one meaning on purpose
// (bat, bank, pitch…): that is what makes a clue link several cards.
//
// APPEND-ONLY: the room seen history (games/{id}/seen/codewords) is keyed by
// deck index, so never reorder or delete entries — add new words at the end.
// codewords.test.js checks size, uniqueness, format and the shared denylist.
export const CODE_WORDS = [
  'acid', 'actor', 'air', 'alarm', 'album', 'alley', 'anchor', 'angel', 'ant', 'apple',
  'apron', 'arm', 'arrow', 'atlas', 'attic', 'avocado', 'baby', 'badge', 'bag', 'bagel',
  'ball', 'balloon', 'bamboo', 'banana', 'band', 'bandage', 'bank', 'bar', 'bark', 'barn',
  'basket', 'bat', 'battery', 'beach', 'beam', 'bean', 'bear', 'beard', 'beaver', 'bed',
  'bee', 'bell', 'belt', 'bench', 'berry', 'bike', 'bill', 'bird', 'blade', 'blanket',
  'blizzard', 'block', 'board', 'boat', 'bolt', 'bone', 'book', 'boot', 'bottle', 'bow',
  'bowl', 'box', 'bracelet', 'brain', 'branch', 'breeze', 'brick', 'bridge', 'broom', 'brush',
  'bubble', 'bucket', 'buffalo', 'bug', 'bulb', 'button', 'cabin', 'cable', 'cactus', 'cake',
  'camel', 'camera', 'camp', 'candle', 'candy', 'cane', 'canoe', 'canyon', 'cap', 'captain',
  'car', 'card', 'carnival', 'carpet', 'carrot', 'castle', 'cat', 'cave', 'cell', 'chain',
  'chair', 'chalk', 'check', 'cheese', 'cherry', 'chest', 'chick', 'chimney', 'chip', 'cinema',
  'circle', 'circus', 'clay', 'cliff', 'clock', 'cloud', 'club', 'coach', 'coast', 'coat',
  'cobra', 'cocoa', 'code', 'coin', 'comb', 'comet', 'compass', 'concert', 'cone', 'cookie',
  'copper', 'coral', 'cord', 'corn', 'cotton', 'court', 'cover', 'cow', 'crab', 'crane',
  'crayon', 'cricket', 'crow', 'crown', 'crystal', 'cube', 'cup', 'cupcake', 'cushion', 'daisy',
  'dance', 'date', 'deck', 'dentist', 'desert', 'desk', 'diamond', 'diary', 'dice', 'dinosaur',
  'disk', 'doctor', 'dog', 'doll', 'dolphin', 'door', 'doorbell', 'dough', 'dragon', 'drill',
  'drum', 'duck', 'dust', 'eagle', 'earth', 'egg', 'elbow', 'elephant', 'engine', 'envelope',
  'eraser', 'eye', 'face', 'fair', 'fairy', 'fall', 'fan', 'farm', 'feather', 'fence',
  'ferry', 'field', 'fig', 'file', 'film', 'fire', 'firework', 'fish', 'flag', 'flamingo',
  'flash', 'flute', 'fly', 'fog', 'foot', 'forest', 'fork', 'fossil', 'fountain', 'fox',
  'frame', 'frog', 'frost', 'galaxy', 'game', 'garden', 'garlic', 'gas', 'gate', 'gecko',
  'gem', 'ghost', 'giant', 'gift', 'giraffe', 'glacier', 'glass', 'globe', 'glove', 'glue',
  'goat', 'goblin', 'gold', 'goose', 'gorilla', 'grape', 'grass', 'ground', 'guard', 'guitar',
  'gum', 'hair', 'ham', 'hammer', 'hammock', 'hamster', 'hand', 'harbor', 'harp', 'hat',
  'hawk', 'head', 'heart', 'hedge', 'hedgehog', 'helmet', 'hero', 'hill', 'hive', 'hole',
  'honey', 'hood', 'hook', 'horn', 'horse', 'hose', 'hospital', 'hotel', 'house', 'ice',
  'iceberg', 'igloo', 'iron', 'island', 'jack', 'jam', 'jar', 'jellyfish', 'jet', 'jewel',
  'jigsaw', 'judge', 'juggler', 'jungle', 'kangaroo', 'kayak', 'kettle', 'key', 'keyboard', 'king',
  'kite', 'kiwi', 'knight', 'knot', 'koala', 'lab', 'ladder', 'lake', 'lamp', 'lantern',
  'laser', 'lava', 'lawn', 'leaf', 'leather', 'lemon', 'letter', 'level', 'light', 'lime',
  'line', 'lion', 'lobster', 'lock', 'locket', 'log', 'lollipop', 'loop', 'luck', 'magnet',
  'mail', 'mammoth', 'mango', 'map', 'marble', 'march', 'mask', 'match', 'maze', 'meadow',
  'medal', 'meteor', 'microscope', 'milk', 'mine', 'mint', 'mirror', 'mitten', 'mole', 'monkey',
  'moon', 'mosaic', 'mouse', 'mouth', 'mud', 'muffin', 'mug', 'museum', 'mushroom', 'nail',
  'napkin', 'needle', 'nest', 'net', 'night', 'noodle', 'note', 'notebook', 'nurse', 'nut',
  'oak', 'oasis', 'ocean', 'octopus', 'oil', 'olive', 'onion', 'opera', 'orange', 'orbit',
  'organ', 'ostrich', 'oven', 'owl', 'pad', 'paddle', 'paint', 'pajamas', 'palm', 'pan',
  'panda', 'paper', 'parachute', 'park', 'parrot', 'party', 'pass', 'passport', 'paste', 'patch',
  'pea', 'peach', 'peanut', 'pearl', 'pebble', 'pelican', 'pen', 'pencil', 'penguin', 'pepper',
  'piano', 'pickle', 'pie', 'pig', 'pillow', 'pilot', 'pin', 'pinball', 'pine', 'pipe',
  'pirate', 'pit', 'pitch', 'pizza', 'plane', 'planet', 'plant', 'plate', 'play', 'plot',
  'pocket', 'point', 'pole', 'pool', 'port', 'post', 'pot', 'potato', 'press', 'pretzel',
  'prince', 'pudding', 'pumpkin', 'puppet', 'puzzle', 'pyramid', 'queen', 'quilt', 'rabbit', 'raccoon',
  'race', 'radio', 'raft', 'rail', 'rain', 'rainbow', 'ranch', 'ray', 'record', 'reef',
  'rhino', 'riddle', 'ring', 'river', 'road', 'robot', 'rock', 'rocket', 'roll', 'roof',
  'root', 'rope', 'rose', 'round', 'rubber', 'ruler', 'saddle', 'sail', 'salad', 'salt',
  'sand', 'sandal', 'satellite', 'saw', 'scale', 'scarf', 'school', 'scissors', 'scooter', 'screen',
  'seal', 'season', 'seesaw', 'shadow', 'shark', 'sheep', 'shell', 'ship', 'shoe', 'shop',
  'shower', 'sign', 'silk', 'silver', 'sink', 'skate', 'skeleton', 'ski', 'sky', 'skyscraper',
  'sled', 'slip', 'sloth', 'slug', 'smoke', 'snail', 'snake', 'snow', 'snowman', 'soap',
  'sock', 'soup', 'space', 'spaghetti', 'spark', 'spider', 'spike', 'spine', 'sponge', 'spoon',
  'spot', 'spring', 'spy', 'square', 'squirrel', 'stadium', 'staff', 'stamp', 'stapler', 'star',
  'starfish', 'station', 'statue', 'steam', 'steel', 'stick', 'stone', 'storm', 'straw', 'stream',
  'string', 'sub', 'sugar', 'suit', 'sun', 'surfboard', 'swan', 'sweater', 'swing', 'switch',
  'table', 'tablet', 'taco', 'tail', 'tap', 'tape', 'taxi', 'tea', 'teacher', 'teapot',
  'telescope', 'temple', 'tent', 'thread', 'throne', 'thumb', 'ticket', 'tie', 'tiger', 'tile',
  'time', 'toast', 'tooth', 'torch', 'tower', 'track', 'tractor', 'train', 'trap', 'treasure',
  'tree', 'triangle', 'trip', 'truck', 'trumpet', 'trunk', 'tuba', 'tube', 'tulip', 'tunnel',
  'turkey', 'turtle', 'umbrella', 'unicorn', 'van', 'vase', 'vest', 'vine', 'violin', 'volcano',
  'waffle', 'wagon', 'wall', 'walrus', 'wand', 'watch', 'water', 'wave', 'web', 'well',
  'whale', 'wheel', 'whistle', 'wind', 'window', 'wing', 'wire', 'witch', 'wizard', 'wolf',
  'wood', 'wool', 'worm', 'yacht', 'yard', 'yarn', 'yogurt', 'zebra', 'zero',
]
