// FIBBAGE deck — each entry has a `prompt` with a blank (___) and the real
// `answer` that fills it. Players invent fake answers; everyone votes on which
// of the shuffled options is the truth. Keep answers short and surprising.
//
// `decoys` — used by solo/bot play: 2–3 short plausible fake answers a bot "lies"
// with. Each must grammatically fit the blank, match the answer's register, and
// never case-insensitively equal the real `answer`. Decoys should also be FALSE
// — a decoy that happens to be true makes the bot accidentally honest.
//
// Order matters: a live round stores `promptIndex` into this array, so append
// new facts at the end rather than inserting or reordering. Each prompt holds
// exactly one `___` (the pages swap it with String.replace). Curation bar and
// shape are enforced by src/lib/decks/fibbage.test.js.
//
// ⚠ RESIDUAL (UNFIXABLE) INFO LEAK: this deck — including every `answer` — ships
// in the client JS bundle, and the active prompt (`round.promptIndex`) is public in
// Firebase. A player who inspects the bundle can therefore always derive the truth,
// no matter how the ballot is anonymised. FibbageGame's mitigations (anonymised
// options + author→lie map withheld until reveal, see src/lib/fibbageLogic.js) only
// defend against CASUAL/spectator leakage of a single Firebase field. Closing this
// hole would require a trusted server to hold the answers and grade votes server-side
// — impossible in this serverless, world-readable-`games/$id` architecture.

export const FIBBAGE_FACTS = [
  { prompt: 'In Switzerland, it is illegal to own just one ___ because they are social animals.', answer: 'guinea pig', decoys: ['hamster', 'tortoise', 'snake'] },
  { prompt: 'The unicorn is the official national animal of ___.', answer: 'Scotland', decoys: ['Ireland', 'Wales', 'Norway'] },
  { prompt: 'A group of flamingos is called a ___.', answer: 'flamboyance', decoys: ['fiesta', 'blush', 'parade'] },
  { prompt: 'Shridhar Chillal\'s record-breaking fingernails on one hand measured a combined total of over ___ feet.', answer: '29', decoys: ['20', '15', '33'] },
  { prompt: 'Honey found in ancient Egyptian tombs was still ___ after thousands of years.', answer: 'edible', decoys: ['toxic', 'fizzy', 'glowing'] },
  { prompt: 'Cleopatra lived closer in time to the Moon landing than to the building of the ___.', answer: 'Great Pyramid', decoys: ['Colosseum', 'Parthenon', 'Great Wall'] },
  { prompt: 'The shortest war in history lasted about ___ minutes.', answer: '38', decoys: ['90', '20', '12'] },
  { prompt: 'Octopuses have ___ hearts.', answer: 'three', decoys: ['two', 'four', 'five'] },
  { prompt: 'Bananas are botanically classified as ___.', answer: 'berries', decoys: ['drupes', 'melons', 'nuts'] },
  { prompt: 'The inventor of the Pringles can had part of his ashes buried in ___.', answer: 'a Pringles can', decoys: ['a cereal box', 'a cookie jar', 'his golf bag'] },
  { prompt: 'In 1850, a desert snail glued to a display card at the British Museum was found to be alive after about ___ years.', answer: 'four', decoys: ['two', 'ten', 'seven'] },
  { prompt: 'The dot over a lowercase i or j is called a ___.', answer: 'tittle', decoys: ['serif', 'diacritic', 'glyph'] },
  { prompt: 'Yokohama, Japan, has a museum dedicated entirely to ___.', answer: 'ramen', decoys: ['sushi', 'tofu', 'umbrellas'] },
  { prompt: 'Cows have best friends and get stressed when ___.', answer: 'separated', decoys: ['milked', 'photographed', 'sung to'] },
  { prompt: 'The fear of long words is ironically called ___.', answer: 'hippopotomonstrosesquippedaliophobia', decoys: ['verbophobia', 'logophobia', 'megalexiphobia'] },
  { prompt: 'Adult ___ are among the very few mammals that cannot jump.', answer: 'elephants', decoys: ['bison', 'moose', 'zebras'] },
  { prompt: 'Wombat droppings are shaped like ___.', answer: 'cubes', decoys: ['pyramids', 'spheres', 'discs'] },
  { prompt: 'The longest recorded flight of a chicken is ___ seconds.', answer: '13', decoys: ['7', '22', '4'] },
  { prompt: 'A 2015 study found that the Scots language has 421 words for ___.', answer: 'snow', decoys: ['rain', 'wind', 'fog'] },
  { prompt: 'The first product ever scanned with a barcode was a pack of ___.', answer: 'chewing gum', decoys: ['cigarettes', 'a candy bar', 'a soda can'] },
  { prompt: 'In physics, a "jiffy" is the time it takes light to travel one ___.', answer: 'centimeter', decoys: ['meter', 'inch', 'mile'] },
  { prompt: 'Sea otters hold ___ while they sleep so they do not drift apart.', answer: 'hands', decoys: ['tails', 'whiskers', 'rocks'] },
  { prompt: 'The Eiffel Tower can grow about six inches taller in ___.', answer: 'summer', decoys: ['winter', 'thunderstorms', 'high winds'] },
  { prompt: 'Sloths can hold their breath longer than ___ can.', answer: 'dolphins', decoys: ['whales', 'seals', 'sea turtles'] },
  { prompt: 'The plastic tips at the end of shoelaces are called ___.', answer: 'aglets', decoys: ['grommets', 'eyelets', 'tippets'] },
  { prompt: 'A group of pugs is called a ___.', answer: 'grumble', decoys: ['pack', 'litter', 'pod'] },
  { prompt: 'The hashtag symbol is technically called an ___.', answer: 'octothorpe', decoys: ['ampersand', 'pilcrow', 'asterisk'] },

  // Content v2 — appended (never reorder; see header).
  // Animals
  { prompt: 'A group of owls is called a ___.', answer: 'parliament', decoys: ['council', 'hoot', 'senate'] },
  { prompt: 'A group of ferrets is called a ___.', answer: 'business', decoys: ['scamper', 'fidget', 'burrow'] },
  { prompt: 'A group of rhinos is called a ___.', answer: 'crash', decoys: ['stampede', 'thunder', 'tank'] },
  { prompt: 'A group of jellyfish is called a ___.', answer: 'smack', decoys: ['wobble', 'jiggle', 'sting'] },
  { prompt: 'A group of zebras is called a ___.', answer: 'dazzle', decoys: ['stripe', 'barcode', 'zigzag'] },
  { prompt: 'A group of giraffes standing together is called a ___.', answer: 'tower', decoys: ['steeple', 'skyline', 'ladder'] },
  { prompt: 'A baby puffin is called a ___.', answer: 'puffling', decoys: ['puffkin', 'pufflet', 'puffball'] },
  { prompt: 'A group of cats is called a ___.', answer: 'clowder', decoys: ['purr', 'whisker', 'meow'] },
  { prompt: 'A group of porcupines is called a ___.', answer: 'prickle', decoys: ['needle', 'poke', 'quiver'] },
  { prompt: 'A group of kangaroos is called a ___.', answer: 'mob', decoys: ['hop', 'pouch', 'bounce'] },
  { prompt: 'A shrimp\'s heart is located in its ___.', answer: 'head', decoys: ['tail', 'legs', 'shell'] },
  { prompt: 'An ostrich\'s ___ is bigger than its brain.', answer: 'eye', decoys: ['nostril', 'kneecap', 'eardrum'] },
  { prompt: 'Butterflies taste with their ___.', answer: 'feet', decoys: ['wings', 'eyes', 'antennae'] },
  { prompt: 'A garden snail\'s mouth holds thousands of tiny ___.', answer: 'teeth', decoys: ['eyes', 'hairs', 'tongues'] },
  { prompt: 'A ___ has fingerprints so humanlike they could confuse a crime scene investigator.', answer: 'koala', decoys: ['raccoon', 'sloth', 'panda'] },
  { prompt: 'Some turtles can breathe through their ___.', answer: 'bottoms', decoys: ['shells', 'ears', 'eyelids'] },
  { prompt: 'Honeybees tell each other where flowers are by ___.', answer: 'dancing', decoys: ['drawing maps', 'blinking', 'singing'] },
  { prompt: 'Cats cannot taste ___.', answer: 'sweetness', decoys: ['salt', 'bitterness', 'sourness'] },
  { prompt: 'Dolphins sleep with one ___ open.', answer: 'eye', decoys: ['fin', 'nostril', 'ear'] },
  { prompt: 'One species of jellyfish is nicknamed the ___ jellyfish because it can turn itself young again.', answer: 'immortal', decoys: ['phoenix', 'vampire', 'boomerang'] },
  { prompt: 'Among seahorses, it is the males who ___.', answer: 'give birth', decoys: ['lay eggs', 'build nests', 'sing'] },
  { prompt: 'Starfish have no ___.', answer: 'brain', decoys: ['mouth', 'eyes', 'stomach'] },
  { prompt: 'Flamingos are pink because of their ___.', answer: 'diet', decoys: ['sunburn', 'blood', 'genes'] },
  { prompt: 'Rats make laughing sounds when they are ___.', answer: 'tickled', decoys: ['scared', 'full', 'dreaming'] },
  { prompt: 'Goats have ___ pupils.', answer: 'rectangular', decoys: ['star-shaped', 'triangular', 'heart-shaped'] },
  { prompt: 'A newborn kangaroo is about the size of a ___.', answer: 'jelly bean', decoys: ['golf ball', 'tennis ball', 'grapefruit'] },
  { prompt: 'Tardigrades, tiny animals nicknamed "water bears", have survived exposure to ___.', answer: 'outer space', decoys: ['lava', 'acid rain', 'a black hole'] },
  { prompt: 'A group of lemurs is called a ___.', answer: 'conspiracy', decoys: ['huddle', 'gossip', 'chorus'] },
  { prompt: 'Owls cannot move their ___.', answer: 'eyes', decoys: ['ears', 'beaks', 'toes'] },
  { prompt: 'A woodpecker\'s ___ wraps around the back of its skull.', answer: 'tongue', decoys: ['beak', 'spine', 'ear'] },
  { prompt: 'Giraffes have the same number of neck bones as ___.', answer: 'humans', decoys: ['snakes', 'ostriches', 'swans'] },
  { prompt: 'A crocodile cannot stick out its ___.', answer: 'tongue', decoys: ['teeth', 'claws', 'eyes'] },
  { prompt: 'Frogs use their ___ to help push food down when they swallow.', answer: 'eyeballs', decoys: ['toes', 'ears', 'nostrils'] },
  { prompt: 'Honeybees have ___ eyes.', answer: 'five', decoys: ['two', 'four', 'eight'] },
  { prompt: 'Under their fur, tigers have striped ___.', answer: 'skin', decoys: ['tongues', 'teeth', 'bones'] },
  { prompt: 'Reindeer eyes change ___ between summer and winter.', answer: 'color', decoys: ['shape', 'size', 'sides'] },
  { prompt: 'Horses are unable to ___.', answer: 'throw up', decoys: ['sneeze', 'yawn', 'swim'] },
  { prompt: 'Bottlenose dolphins call each other by ___.', answer: 'name', decoys: ['smell', 'color', 'touch'] },
  { prompt: 'Hippos produce a reddish sweat-like fluid that works as ___.', answer: 'sunscreen', decoys: ['perfume', 'glue', 'toothpaste'] },
  { prompt: 'Some penguins court a mate by offering a ___.', answer: 'pebble', decoys: ['fish', 'feather', 'shell'] },
  { prompt: 'Pigeons have been trained to tell the difference between paintings by Monet and ___.', answer: 'Picasso', decoys: ['Van Gogh', 'Rembrandt', 'Da Vinci'] },
  { prompt: 'Crows can remember human ___ for years.', answer: 'faces', decoys: ['names', 'birthdays', 'phone numbers'] },
  { prompt: 'Only female mosquitoes ___.', answer: 'bite', decoys: ['buzz', 'sleep', 'drink nectar'] },
  { prompt: 'Axolotls can regrow entire ___.', answer: 'limbs', decoys: ['eyelashes', 'whiskers', 'scales'] },
  { prompt: 'Sharks existed before ___.', answer: 'trees', decoys: ['fish', 'bacteria', 'jellyfish'] },
  { prompt: 'Tyrannosaurus rex lived closer in time to humans than to ___.', answer: 'Stegosaurus', decoys: ['Triceratops', 'Velociraptor', 'woolly mammoths'] },
  { prompt: 'The closest living relatives of Tyrannosaurus rex are ___.', answer: 'birds', decoys: ['lizards', 'crocodiles', 'snakes'] },

  // Space
  { prompt: 'A day on Venus is longer than a ___ on Venus.', answer: 'year', decoys: ['week', 'month', 'season'] },
  { prompt: 'Neptune\'s position was predicted using ___ before astronomers knew to look for it.', answer: 'math', decoys: ['radio waves', 'a comet', 'x-rays'] },
  { prompt: 'Astronauts can temporarily grow up to about ___ inches taller in space.', answer: 'two', decoys: ['six', 'ten', 'twelve'] },
  { prompt: 'A lightning bolt is about ___ times hotter than the surface of the Sun.', answer: 'five', decoys: ['two', 'ten', 'fifty'] },
  { prompt: 'Sunsets on Mars look ___.', answer: 'blue', decoys: ['green', 'purple', 'red'] },
  { prompt: 'Footprints left on the Moon could last for ___ of years.', answer: 'millions', decoys: ['hundreds', 'thousands', 'billions'] },
  { prompt: 'Saturn is so light for its size that it would ___ in a big enough bathtub.', answer: 'float', decoys: ['dissolve', 'sink', 'fizz'] },
  { prompt: 'The Sun holds about ___ percent of all the mass in the solar system.', answer: '99.8', decoys: ['75', '90', '50'] },
  { prompt: 'Halley\'s Comet swings past Earth roughly every ___ years.', answer: '76', decoys: ['50', '100', '33'] },
  { prompt: 'One year on Neptune lasts about ___ Earth years.', answer: '165', decoys: ['84', '29', '250'] },
  { prompt: 'The first animals sent into space, in 1947, were ___.', answer: 'fruit flies', decoys: ['mice', 'monkeys', 'spiders'] },
  { prompt: 'Measured from base to peak, the tallest mountain on Earth is ___.', answer: 'Mauna Kea', decoys: ['K2', 'Kilimanjaro', 'Mont Blanc'] },
  { prompt: 'Tree seeds that orbited the Moon on Apollo 14 were planted across the US and became known as ___.', answer: 'Moon Trees', decoys: ['Space Pines', 'Star Oaks', 'Apollo Elms'] },
  { prompt: 'Pluto was named by an 11-year-old girl from ___.', answer: 'Oxford', decoys: ['Arizona', 'Boston', 'Dublin'] },

  // Food
  { prompt: 'Before rubber erasers, people rubbed out pencil marks with ___.', answer: 'bread', decoys: ['wax', 'cheese', 'clay'] },
  { prompt: 'In the 1830s, ketchup was sold in pill form as a ___.', answer: 'medicine', decoys: ['hair dye', 'cleaning product', 'perfume'] },
  { prompt: 'Before the 1600s, most cultivated carrots were ___ or yellow.', answer: 'purple', decoys: ['blue', 'green', 'pink'] },
  { prompt: 'Peanuts are not nuts; they are ___.', answer: 'legumes', decoys: ['berries', 'tubers', 'grains'] },
  { prompt: 'Almonds are the seeds of a fruit closely related to the ___.', answer: 'peach', decoys: ['coconut', 'olive', 'walnut'] },
  { prompt: 'A pineapple plant takes about ___ years to produce one pineapple.', answer: 'two', decoys: ['five', 'ten', 'seven'] },
  { prompt: 'In Japan, it is a popular Christmas tradition to eat ___.', answer: 'KFC', decoys: ['sushi', 'ramen', 'pizza'] },
  { prompt: 'Hawaiian pizza was invented in ___.', answer: 'Canada', decoys: ['Hawaii', 'Australia', 'New Zealand'] },
  { prompt: 'German chocolate cake is named after an American chocolate maker called Samuel ___.', answer: 'German', decoys: ['Baker', 'Schmidt', 'Hershey'] },
  { prompt: 'The Caesar salad was invented in ___.', answer: 'Mexico', decoys: ['Italy', 'Rome', 'Greece'] },
  { prompt: 'Worcestershire sauce is made with fermented ___.', answer: 'anchovies', decoys: ['mushrooms', 'plums', 'beetles'] },
  { prompt: 'The word "orange" named the ___ before it named the color.', answer: 'fruit', decoys: ['sunset', 'flower', 'tiger'] },
  { prompt: 'Fresh cranberries are sorted for quality by checking whether they can ___.', answer: 'bounce', decoys: ['glow', 'squeak', 'whistle'] },
  { prompt: 'Apples float in water because they are about a quarter ___.', answer: 'air', decoys: ['sugar', 'juice', 'fiber'] },
  { prompt: 'Coffee beans are actually the ___ of a fruit.', answer: 'seeds', decoys: ['roots', 'skins', 'flowers'] },
  { prompt: 'Each cashew nut grows hanging from the bottom of a ___.', answer: 'cashew apple', decoys: ['palm leaf', 'vine', 'flower'] },
  { prompt: 'White chocolate contains no ___.', answer: 'cocoa solids', decoys: ['sugar', 'milk', 'fat'] },
  { prompt: 'Broccoli, cabbage, kale and cauliflower are all the same plant ___.', answer: 'species', decoys: ['color', 'shape', 'size'] },
  { prompt: 'The Aztecs used cacao beans as ___.', answer: 'money', decoys: ['perfume', 'paint', 'jewelry'] },
  { prompt: 'Stored in huge piles, pistachios can spontaneously ___.', answer: 'catch fire', decoys: ['sprout', 'explode', 'turn blue'] },
  { prompt: 'Bananas are very slightly ___ because they contain potassium.', answer: 'radioactive', decoys: ['magnetic', 'sticky', 'salty'] },
  { prompt: 'In M&M\'s, one of the two M\'s stands for the surname ___.', answer: 'Mars', decoys: ['Milton', 'Miller', 'Morris'] },
  { prompt: 'The holes in Swiss cheese are called ___.', answer: 'eyes', decoys: ['pockets', 'bubbles', 'windows'] },
  { prompt: 'Many 18th-century Europeans believed tomatoes were ___.', answer: 'poisonous', decoys: ['magic', 'cursed', 'fish eggs'] },

  // Language
  { prompt: 'In Dutch, the @ symbol is nicknamed the "little ___ tail".', answer: 'monkey', decoys: ['pig', 'rat', 'dragon'] },
  { prompt: 'The word "robot" comes from a Czech word meaning ___.', answer: 'forced labor', decoys: ['metal man', 'iron worker', 'clockwork'] },
  { prompt: 'The Chinese word for "computer" literally means ___.', answer: 'electric brain', decoys: ['thinking box', 'number machine', 'light abacus'] },
  { prompt: 'The German word for "glove" literally means ___.', answer: 'hand shoe', decoys: ['hand hat', 'finger sock', 'palm coat'] },
  { prompt: 'The German word for "skunk" literally means ___.', answer: 'stink animal', decoys: ['smelly cat', 'stripe fox', 'nose enemy'] },
  { prompt: 'The French word for "potato" literally means ___.', answer: 'earth apple', decoys: ['ground bread', 'soil nut', 'dirt egg'] },
  { prompt: 'The Japanese word "karaoke" means ___.', answer: 'empty orchestra', decoys: ['singing alone', 'loud voice', 'bar music'] },
  { prompt: 'The word "muscle" comes from the Latin for ___.', answer: 'little mouse', decoys: ['strong arm', 'tight rope', 'small ox'] },
  { prompt: 'The word "hippopotamus" comes from the Greek for ___.', answer: 'river horse', decoys: ['water pig', 'mud cow', 'big mouth'] },
  { prompt: 'The word "dinosaur" comes from the Greek for ___.', answer: 'terrible lizard', decoys: ['giant bird', 'ancient beast', 'thunder feet'] },
  { prompt: 'LEGO comes from the Danish words "leg godt", meaning ___.', answer: 'play well', decoys: ['build big', 'little bricks', 'stack high'] },
  { prompt: 'The space between your eyebrows is called the ___.', answer: 'glabella', decoys: ['browline', 'frontlet', 'temple'] },
  { prompt: 'The groove between your nose and upper lip is called the ___.', answer: 'philtrum', decoys: ['lip ridge', 'nose gutter', 'septum'] },
  { prompt: 'The pale crescent at the base of a fingernail is called the ___.', answer: 'lunula', decoys: ['cuticle', 'crest', 'quick'] },
  { prompt: 'The dangly bit at the back of your throat is called the ___.', answer: 'uvula', decoys: ['epiglottis', 'tonsil', 'larynx'] },
  { prompt: 'The crack of a whip is actually a tiny ___.', answer: 'sonic boom', decoys: ['explosion', 'thunderclap', 'echo'] },
  { prompt: 'A combined question mark and exclamation mark is called an ___.', answer: 'interrobang', decoys: ['exclamaquest', 'shriekmark', 'quizbang'] },
  { prompt: 'The fear of the number 13 is called ___.', answer: 'triskaidekaphobia', decoys: ['tredecaphobia', 'numerophobia', 'unluckophobia'] },
  { prompt: 'An old-fashioned English word for "the day after tomorrow" is ___.', answer: 'overmorrow', decoys: ['nextmorrow', 'twomorrow', 'aftermorn'] },
  { prompt: 'The earthy smell of rain on dry ground is called ___.', answer: 'petrichor', decoys: ['ozonance', 'terrascent', 'raincense'] },
  { prompt: '"Defenestration" means throwing someone out of a ___.', answer: 'window', decoys: ['castle', 'fence', 'boat'] },
  { prompt: 'A googol is the number 1 followed by ___ zeros.', answer: '100', decoys: ['1,000', '50', '10'] },
  { prompt: 'In medieval times, a "moment" was a unit of time lasting ___ seconds.', answer: '90', decoys: ['60', '10', '45'] },
  { prompt: 'The only letter that does not appear in any US state name is ___.', answer: 'Q', decoys: ['X', 'Z', 'J'] },
  { prompt: 'Maine is the only US state whose name has just one ___.', answer: 'syllable', decoys: ['vowel', 'consonant', 'capital letter'] },
  { prompt: 'The word "dollar" comes from the ___, a silver coin first minted in Bohemia.', answer: 'thaler', decoys: ['ducat', 'florin', 'guilder'] },
  { prompt: 'The name "Wendy" became popular thanks to the book ___.', answer: 'Peter Pan', decoys: ['Alice in Wonderland', 'The Secret Garden', 'Little Women'] },
  { prompt: 'The word "nerd" first appeared in print in a book by ___.', answer: 'Dr. Seuss', decoys: ['Roald Dahl', 'Mark Twain', 'Lewis Carroll'] },
  { prompt: 'Dr. Seuss wrote "Green Eggs and Ham" using only ___ different words.', answer: '50', decoys: ['100', '25', '75'] },

  // History & places
  { prompt: 'Oxford University is older than the ___ Empire.', answer: 'Aztec', decoys: ['Roman', 'Byzantine', 'Persian'] },
  { prompt: 'The Eiffel Tower was originally meant to stand for only ___ years.', answer: '20', decoys: ['5', '10', '50'] },
  { prompt: 'Before it turned green, the Statue of Liberty was the shiny color of a new ___.', answer: 'penny', decoys: ['trumpet', 'kettle', 'doorknob'] },
  { prompt: 'The Hundred Years\' War actually lasted ___ years.', answer: '116', decoys: ['100', '99', '112'] },
  { prompt: 'Abraham Lincoln is in the National ___ Hall of Fame.', answer: 'Wrestling', decoys: ['Chess', 'Boxing', 'Rowing'] },
  { prompt: 'The Empire State Building has its own ___.', answer: 'ZIP code', decoys: ['currency', 'time zone', 'police force'] },
  { prompt: 'The Leaning Tower of Pisa took nearly ___ years to finish.', answer: '200', decoys: ['20', '50', '100'] },
  { prompt: 'The first Ferris wheel was built in 1893 to rival the ___.', answer: 'Eiffel Tower', decoys: ['Big Ben', 'Statue of Liberty', 'Colosseum'] },
  { prompt: 'Big Ben is actually the name of the ___.', answer: 'bell', decoys: ['clock', 'tower', 'architect'] },
  { prompt: 'The smaller "bluestones" of Stonehenge were hauled all the way from ___.', answer: 'Wales', decoys: ['France', 'Ireland', 'Cornwall'] },
  { prompt: 'Sudan has more ___ than Egypt.', answer: 'pyramids', decoys: ['camels', 'rivers', 'pharaohs'] },
  { prompt: 'Canada has more ___ than the rest of the world combined.', answer: 'lakes', decoys: ['moose', 'maple trees', 'hockey rinks'] },
  { prompt: 'Norway\'s King\'s Guard has knighted a ___.', answer: 'penguin', decoys: ['moose', 'reindeer', 'salmon'] },
  { prompt: 'The Alaskan town of Talkeetna had a ___ as its honorary mayor for about 20 years.', answer: 'cat', decoys: ['dog', 'moose', 'bear'] },
  { prompt: 'Nepal\'s time zone is ahead of UTC by 5 hours and ___ minutes.', answer: '45', decoys: ['30', '15', '20'] },
  { prompt: 'Nepal\'s flag is the only national flag that is not ___.', answer: 'rectangular', decoys: ['symmetrical', 'cotton', 'bordered'] },
  { prompt: 'The only two square national flags belong to Switzerland and ___.', answer: 'Vatican City', decoys: ['Monaco', 'Nepal', 'Japan'] },
  { prompt: 'In 2007, soldiers from ___ got lost at night and accidentally marched into Liechtenstein.', answer: 'Switzerland', decoys: ['Austria', 'Germany', 'Italy'] },
  { prompt: 'Liechtenstein\'s 80-man army came home from its last war in 1866 with ___ soldiers.', answer: '81', decoys: ['79', '80', '40'] },
  { prompt: 'Alaska is the westernmost and also the ___ US state.', answer: 'easternmost', decoys: ['southernmost', 'flattest', 'youngest'] },
  { prompt: 'Australia is wider than the ___.', answer: 'Moon', decoys: ['Sahara', 'Atlantic', 'Pacific'] },
  { prompt: 'Lake Baikal holds about ___ of the world\'s unfrozen fresh surface water.', answer: 'one fifth', decoys: ['half', 'one tenth', 'one third'] },
  { prompt: 'New Zealand has more ___ than people.', answer: 'sheep', decoys: ['kiwis', 'penguins', 'hobbits'] },
  { prompt: 'In Venice, it is illegal to feed the ___ in St Mark\'s Square.', answer: 'pigeons', decoys: ['cats', 'tourists', 'fish'] },

  // Inventions, tech & toys
  { prompt: 'Bubble wrap was originally invented as ___.', answer: 'wallpaper', decoys: ['a pool float', 'a mattress', 'shower curtains'] },
  { prompt: 'Play-Doh was originally sold as ___.', answer: 'wallpaper cleaner', decoys: ['window putty', 'denture paste', 'bath soap'] },
  { prompt: 'The ashes of Ed Headrick, designer of the modern Frisbee, were molded into ___.', answer: 'Frisbees', decoys: ['golf balls', 'a statue', 'bowling balls'] },
  { prompt: 'The first computer mouse was made of ___.', answer: 'wood', decoys: ['tin', 'ivory', 'cardboard'] },
  { prompt: 'In 1947, engineers taped a real ___ into a logbook as the "first actual case of bug being found".', answer: 'moth', decoys: ['cockroach', 'beetle', 'spider'] },
  { prompt: 'One of the first webcams was set up at Cambridge University to watch a ___.', answer: 'coffee pot', decoys: ['fish tank', 'bird feeder', 'printer queue'] },
  { prompt: 'The first item ever sold on eBay was a broken ___.', answer: 'laser pointer', decoys: ['toaster', 'Game Boy', 'calculator'] },
  { prompt: 'The first video ever uploaded to YouTube was filmed at a ___.', answer: 'zoo', decoys: ['beach', 'birthday party', 'skate park'] },
  { prompt: 'Nintendo was founded in 1889 to make ___.', answer: 'playing cards', decoys: ['toy trains', 'umbrellas', 'rice cookers'] },
  { prompt: 'Google\'s original name was ___.', answer: 'BackRub', decoys: ['SearchDog', 'WebCrawler', 'Findr'] },
  { prompt: 'Before it was called Pepsi, the drink was called ___.', answer: 'Brad\'s Drink', decoys: ['Caleb\'s Cola', 'Fizzy Brad', 'Pep Water'] },
  { prompt: 'Bluetooth is named after a 10th-century ___ king.', answer: 'Danish', decoys: ['Roman', 'Egyptian', 'Scottish'] },
  { prompt: 'Mr. Potato Head was the first toy ever advertised on ___.', answer: 'TV', decoys: ['radio', 'billboards', 'cereal boxes'] },
  { prompt: 'The Slinky was invented by accident by a naval ___.', answer: 'engineer', decoys: ['cook', 'chaplain', 'pilot'] },
  { prompt: 'The microwave oven was invented after a radar engineer noticed a ___ had melted in his pocket.', answer: 'chocolate bar', decoys: ['crayon', 'candle', 'cheese sandwich'] },
  { prompt: 'The Popsicle was invented by a boy aged ___ who left a drink outside overnight.', answer: '11', decoys: ['7', '15', '9'] },
  { prompt: 'Velcro was inspired by ___ stuck to a dog\'s fur.', answer: 'burrs', decoys: ['gum', 'snowballs', 'seaweed'] },
  { prompt: 'The first known vending machine, from ancient Egypt, dispensed ___.', answer: 'holy water', decoys: ['olive oil', 'wine', 'bread'] },
  { prompt: 'The first American mechanical alarm clock could only ring at ___.', answer: '4 a.m.', decoys: ['midnight', 'noon', '6 a.m.'] },
  { prompt: 'The Rubik\'s Cube was invented by a Hungarian professor of ___.', answer: 'architecture', decoys: ['math', 'physics', 'chemistry'] },
  { prompt: 'Monopoly grew out of "The Landlord\'s Game", which was designed to warn people about ___.', answer: 'monopolies', decoys: ['gambling', 'debt', 'taxes'] },
  { prompt: 'Barbie\'s full name is Barbara Millicent ___.', answer: 'Roberts', decoys: ['Johnson', 'Carter', 'Wilson'] },
  { prompt: 'Winnie-the-Pooh was named after a real bear from the Canadian city of ___.', answer: 'Winnipeg', decoys: ['Toronto', 'Vancouver', 'Calgary'] },
  { prompt: 'Kermit the Frog\'s first eyes were made from a cut-up ___.', answer: 'ping-pong ball', decoys: ['golf ball', 'bottle cap', 'egg cup'] },
  { prompt: 'In the original Donkey Kong, Mario was called ___.', answer: 'Jumpman', decoys: ['Hopper', 'Bouncer', 'Leapman'] },
  { prompt: 'The Pac-Man ghosts are Blinky, Pinky, Inky and ___.', answer: 'Clyde', decoys: ['Dinky', 'Stinky', 'Winky'] },
  { prompt: 'Pac-Man\'s shape was inspired by a ___ with a slice missing.', answer: 'pizza', decoys: ['cake', 'pie', 'cheese wheel'] },
  { prompt: 'There are more possible games of ___ than atoms in the observable universe.', answer: 'chess', decoys: ['checkers', 'tic-tac-toe', 'Connect Four'] },

  // Film, TV & sport
  { prompt: 'The hum of a Star Wars lightsaber was made partly from the motor of an old ___.', answer: 'film projector', decoys: ['vacuum cleaner', 'fridge', 'hair dryer'] },
  { prompt: 'Chewbacca\'s voice was built partly from recordings of a ___.', answer: 'bear', decoys: ['camel', 'donkey', 'whale'] },
  { prompt: 'The fake blood in the shower scene of "Psycho" was ___.', answer: 'chocolate syrup', decoys: ['ketchup', 'cherry juice', 'red paint'] },
  { prompt: 'Walt Disney first wanted to name Mickey Mouse ___.', answer: 'Mortimer', decoys: ['Marvin', 'Milton', 'Maxwell'] },
  { prompt: 'Donald Duck\'s middle name is ___.', answer: 'Fauntleroy', decoys: ['Quackers', 'Duckworth', 'Beaksley'] },
  { prompt: 'Mickey Mouse was first voiced by ___.', answer: 'Walt Disney', decoys: ['Mel Blanc', 'Roy Disney', 'Ub Iwerks'] },
  { prompt: 'Scooby-Doo\'s full first name is ___.', answer: 'Scoobert', decoys: ['Scoobias', 'Scooberto', 'Scoobington'] },
  { prompt: 'Toto in "The Wizard of Oz" was played by a female dog named ___.', answer: 'Terry', decoys: ['Lucky', 'Daisy', 'Bella'] },
  { prompt: 'The first basketball hoops were ___.', answer: 'peach baskets', decoys: ['buckets', 'fishing nets', 'flower pots'] },
  { prompt: 'Volleyball was originally called ___.', answer: 'Mintonette', decoys: ['Netball', 'Mintball', 'Skyball'] },
  { prompt: 'Tennis balls at Wimbledon were ___ until 1986.', answer: 'white', decoys: ['orange', 'green', 'pink'] },
  { prompt: 'Tug of war was an Olympic sport until ___.', answer: '1920', decoys: ['1936', '1948', '1908'] },
  { prompt: 'From 1912 to 1948, the Olympics also awarded medals for ___.', answer: 'art', decoys: ['chess', 'cooking', 'bridge'] },
  { prompt: 'A regulation baseball has exactly ___ double stitches.', answer: '108', decoys: ['88', '100', '144'] },
]
