// FIBBAGE deck — each entry has a `prompt` with a blank (___) and the real
// `answer` that fills it. Players invent fake answers; everyone votes on which
// of the shuffled options is the truth. Keep answers short and surprising.
//
// CONTENT RULES: only well-established, checkable facts — no myths or "fun
// facts" that fall apart on inspection (the old "the elephant is the only mammal
// that can't jump" item was false and has been removed). Avoid "more than N"
// style prompts where a wrong number would still make the sentence true.
//
// `decoys` — used by solo/bot play: 2–3 short plausible fake answers a bot "lies"
// with. Each must grammatically fit the blank, match the answer's register, make
// the sentence FALSE (a true decoy makes the bot accidentally honest), and never
// be truth-like (fibbageLogic.isTruthLike) — fibbageLogic.test.js enforces the
// last part.
//
// Order matters: a live round stores deck indices (`round.order` /
// `round.promptIndex`) and the room's `seen/fibbage` history, so append new
// facts at the end rather than inserting or reordering (a removed fact's slot is
// reused in place). Each prompt holds exactly one `___` (the pages swap it with
// String.replace). Curation bar and shape are enforced by
// src/lib/decks/fibbage.test.js and src/lib/fibbageLogic.test.js.
//
// ⚠ RESIDUAL (UNFIXABLE) INFO LEAK: this deck — including every `answer` — ships
// in the client JS bundle, and the active prompt (`round.promptIndex`) is public in
// Firebase. A player who inspects the bundle can therefore always derive the truth,
// no matter how the ballot is anonymised. FibbageGame's mitigations (anonymised
// options + author→lie map withheld until reveal, see src/lib/fibbageLogic.js) only
// defend against CASUAL/spectator leakage of a single Firebase field. Closing this
// hole would require a trusted server to hold the answers and grade votes server-side
// — impossible in this serverless, world-readable-`games/$id` architecture.

export const FIBBAGE_FACTS = [
  { prompt: 'In Switzerland, it is illegal to own just one ___, because they are social animals.', answer: 'guinea pig', decoys: ['hamster', 'goldfish', 'parrot'] },
  { prompt: 'The unicorn is the official national animal of ___.', answer: 'Scotland', decoys: ['Ireland', 'Wales', 'Norway'] },
  { prompt: 'A group of flamingos is called a ___.', answer: 'flamboyance', decoys: ['parade', 'fiesta', 'blush'] },
  { prompt: 'Shridhar Chillal\'s record-breaking fingernails on one hand measured a combined total of over ___ feet.', answer: '29', decoys: ['20', '15', '33'] },
  { prompt: 'Archaeologists have found pots of honey in ancient Egyptian tombs that were still ___.', answer: 'edible', decoys: ['toxic', 'fizzy', 'frozen'] },
  { prompt: 'Cleopatra lived closer in time to the Moon landing than to the building of the ___.', answer: 'Great Pyramid', decoys: ['Colosseum', 'Parthenon', 'Pantheon'] },
  { prompt: 'A group of crows is called a ___.', answer: 'murder', decoys: ['cackle', 'riot', 'shadow'] },
  { prompt: 'Octopuses have ___ hearts.', answer: 'three', decoys: ['two', 'four', 'five'] },
  { prompt: 'Botanically, bananas are classified as ___.', answer: 'berries', decoys: ['drupes', 'legumes', 'nuts'] },
  { prompt: 'The inventor of the Pringles can had some of his ashes buried in ___.', answer: 'a Pringles can', decoys: ['a cereal box', 'a cookie jar', 'his golf bag'] },
  { prompt: 'In 1850, a desert snail glued to a display card at the British Museum was found to be alive after about ___ years.', answer: 'four', decoys: ['two', 'ten', 'seven'] },
  { prompt: 'The dot over a lowercase i or j is called a ___.', answer: 'tittle', decoys: ['serif', 'pip', 'dimple'] },
  { prompt: 'Yokohama, Japan, has a museum dedicated entirely to ___.', answer: 'ramen', decoys: ['sushi', 'tofu', 'umbrellas'] },
  { prompt: 'A baby kangaroo is called a ___.', answer: 'joey', decoys: ['kit', 'cub', 'pup'] },
  { prompt: 'Most of an octopus\'s neurons are in its ___.', answer: 'arms', decoys: ['head', 'skin', 'eyes'] },
  { prompt: 'Horseshoe crabs have ___ blood.', answer: 'blue', decoys: ['green', 'purple', 'orange'] },
  { prompt: 'Wombat droppings are shaped like ___.', answer: 'cubes', decoys: ['pyramids', 'stars', 'discs'] },
  { prompt: 'Under their white-looking fur, polar bears have ___ skin.', answer: 'black', decoys: ['white', 'pink', 'orange'] },
  { prompt: 'Researchers at the University of Glasgow counted 421 Scots words for ___.', answer: 'snow', decoys: ['rain', 'wind', 'fog'] },
  { prompt: 'The first product ever scanned with a barcode at a supermarket checkout was a pack of ___.', answer: 'chewing gum', decoys: ['cigarettes', 'batteries', 'mints'] },
  { prompt: 'In physics, a "jiffy" is the time it takes light to travel one ___.', answer: 'centimeter', decoys: ['meter', 'inch', 'mile'] },
  { prompt: 'Sea otters hold ___ while they sleep so they don\'t drift apart.', answer: 'hands', decoys: ['tails', 'whiskers', 'ears'] },
  { prompt: 'Thanks to heat expansion, the Eiffel Tower can grow about 15 centimetres taller in ___.', answer: 'summer', decoys: ['winter', 'the rain', 'a snowstorm'] },
  { prompt: 'Sloths can hold their breath longer than ___ can.', answer: 'dolphins', decoys: ['penguins', 'otters', 'hippos'] },
  { prompt: 'The plastic tips on the ends of shoelaces are called ___.', answer: 'aglets', decoys: ['grommets', 'eyelets', 'toggles'] },
  { prompt: 'In seahorses, it\'s the ___ that gets pregnant.', answer: 'male', decoys: ['female', 'eldest', 'biggest'] },
  { prompt: 'The # symbol is also known as an ___.', answer: 'octothorpe', decoys: ['ampersand', 'interrobang', 'asterisk'] },

  // Content v2 — appended (never reorder; see header).
  // Animals
  { prompt: 'A group of owls is called a ___.', answer: 'parliament', decoys: ['senate', 'council', 'hoot'] },
  { prompt: 'A group of ferrets is called a ___.', answer: 'business', decoys: ['scamper', 'fidget', 'burrow'] },
  { prompt: 'A group of rhinos is called a ___.', answer: 'crash', decoys: ['charge', 'stampede', 'rumble'] },
  { prompt: 'A group of jellyfish is called a ___.', answer: 'smack', decoys: ['wobble', 'jiggle', 'drift'] },
  { prompt: 'A group of zebras is called a ___.', answer: 'dazzle', decoys: ['stripe', 'barcode', 'zigzag'] },
  { prompt: 'A group of giraffes standing together is called a ___.', answer: 'tower', decoys: ['steeple', 'skyline', 'ladder'] },
  { prompt: 'A baby puffin is called a ___.', answer: 'puffling', decoys: ['pufflet', 'puffkin', 'squab'] },
  { prompt: 'A group of cats is called a ___.', answer: 'clowder', decoys: ['purr', 'whisker', 'meow'] },
  { prompt: 'A group of porcupines is called a ___.', answer: 'prickle', decoys: ['needle', 'poke', 'quiver'] },
  { prompt: 'A group of kangaroos is called a ___.', answer: 'mob', decoys: ['hop', 'pouch', 'bounce'] },
  { prompt: 'A shrimp\'s heart is in its ___.', answer: 'head', decoys: ['tail', 'legs', 'claws'] },
  { prompt: 'An ostrich\'s ___ is bigger than its brain.', answer: 'eye', decoys: ['nostril', 'kneecap', 'eardrum'] },
  { prompt: 'Butterflies taste with their ___.', answer: 'feet', decoys: ['wings', 'eyes', 'tails'] },
  { prompt: 'A garden snail has thousands of tiny ___.', answer: 'teeth', decoys: ['eyes', 'hearts', 'legs'] },
  { prompt: 'A ___ has fingerprints so humanlike they could confuse a crime scene investigator.', answer: 'koala', decoys: ['raccoon', 'sloth', 'panda'] },
  { prompt: 'Some turtles can breathe through their ___.', answer: 'bottoms', decoys: ['shells', 'ears', 'eyelids'] },
  { prompt: 'Honeybees tell each other where flowers are by ___.', answer: 'dancing', decoys: ['drawing maps', 'blinking', 'singing'] },
  { prompt: 'Cats can\'t taste ___.', answer: 'sweetness', decoys: ['saltiness', 'bitterness', 'sourness'] },
  { prompt: 'Dolphins sleep with one ___ open.', answer: 'eye', decoys: ['fin', 'nostril', 'ear'] },
  { prompt: 'One species of jellyfish is nicknamed the ___ jellyfish because it can turn itself young again.', answer: 'immortal', decoys: ['phoenix', 'vampire', 'boomerang'] },
  { prompt: 'Among seahorses, it is the males who ___.', answer: 'give birth', decoys: ['lay eggs', 'build nests', 'sing'] },
  { prompt: 'Starfish don\'t have a ___.', answer: 'brain', decoys: ['mouth', 'stomach', 'skeleton'] },
  { prompt: 'Flamingos are pink because of their ___.', answer: 'diet', decoys: ['sunburn', 'blood', 'genes'] },
  { prompt: 'Rats make laughing sounds when they are ___.', answer: 'tickled', decoys: ['scared', 'full', 'dreaming'] },
  { prompt: 'Goats have ___ pupils.', answer: 'rectangular', decoys: ['star-shaped', 'triangular', 'heart-shaped'] },
  { prompt: 'A newborn kangaroo is about the size of a ___.', answer: 'jelly bean', decoys: ['golf ball', 'tennis ball', 'grapefruit'] },
  { prompt: 'Tardigrades, tiny animals nicknamed "water bears", have survived exposure to ___.', answer: 'outer space', decoys: ['lava', 'acid rain', 'a black hole'] },
  { prompt: 'A group of lemurs is called a ___.', answer: 'conspiracy', decoys: ['huddle', 'gossip', 'chorus'] },
  { prompt: 'Owls cannot move their ___.', answer: 'eyes', decoys: ['ears', 'beaks', 'toes'] },
  { prompt: 'A woodpecker\'s ___ wraps around the back of its skull.', answer: 'tongue', decoys: ['beak', 'spine', 'ear'] },
  { prompt: 'Giraffes have the same number of neck bones as ___.', answer: 'humans', decoys: ['snakes', 'swans', 'owls'] },
  { prompt: 'A crocodile cannot stick out its ___.', answer: 'tongue', decoys: ['teeth', 'claws', 'eyes'] },
  { prompt: 'Frogs use their ___ to help push food down when they swallow.', answer: 'eyeballs', decoys: ['toes', 'ears', 'nostrils'] },
  { prompt: 'Honeybees have ___ eyes.', answer: 'five', decoys: ['two', 'four', 'eight'] },
  { prompt: 'Under their fur, tigers have striped ___.', answer: 'skin', decoys: ['tongues', 'teeth', 'bones'] },
  { prompt: 'Reindeer eyes change ___ between summer and winter.', answer: 'color', decoys: ['shape', 'size', 'sides'] },
  { prompt: 'Horses are unable to ___.', answer: 'throw up', decoys: ['sneeze', 'yawn', 'swim'] },
  { prompt: 'Bottlenose dolphins call each other by ___.', answer: 'name', decoys: ['smell', 'color', 'touch'] },
  { prompt: 'Hippos produce a reddish sweat-like fluid that works as ___.', answer: 'sunscreen', decoys: ['perfume', 'glue', 'toothpaste'] },
  { prompt: 'Some penguins court a mate by offering a ___.', answer: 'pebble', decoys: ['fish', 'feather', 'shell'] },
  { prompt: 'Pigeons have been trained to tell the difference between paintings by Monet and ___.', answer: 'Picasso', decoys: ['Van Gogh', 'Rembrandt', 'Da Vinci'] },
  { prompt: 'Crows can remember individual human ___ for years.', answer: 'faces', decoys: ['names', 'handwriting', 'shoe sizes'] },
  { prompt: 'Only female mosquitoes ___.', answer: 'bite', decoys: ['buzz', 'sleep', 'drink nectar'] },
  { prompt: 'Axolotls can regrow entire ___.', answer: 'limbs', decoys: ['eyelashes', 'whiskers', 'scales'] },
  { prompt: 'Sharks have been around for longer than ___.', answer: 'trees', decoys: ['jellyfish', 'sponges', 'coral'] },
  { prompt: 'Tyrannosaurus rex lived closer in time to humans than to ___.', answer: 'Stegosaurus', decoys: ['Triceratops', 'Velociraptor', 'woolly mammoths'] },
  { prompt: 'The closest living relatives of Tyrannosaurus rex are ___.', answer: 'birds', decoys: ['lizards', 'crocodiles', 'snakes'] },

  // Space
  { prompt: 'A day on Venus is longer than a ___ on Venus.', answer: 'year', decoys: ['week', 'month', 'season'] },
  { prompt: 'Neptune\'s position was predicted using ___ before astronomers knew to look for it.', answer: 'math', decoys: ['radio waves', 'a comet', 'x-rays'] },
  { prompt: 'Astronauts can temporarily grow up to about ___ inches taller in space.', answer: 'two', decoys: ['six', 'ten', 'twelve'] },
  { prompt: 'A lightning bolt is about ___ times hotter than the surface of the Sun.', answer: 'five', decoys: ['two', 'ten', 'fifty'] },
  { prompt: 'Sunsets on Mars look ___.', answer: 'blue', decoys: ['green', 'purple', 'red'] },
  { prompt: 'Footprints left on the Moon could last for ___ of years.', answer: 'millions', decoys: ['hundreds', 'thousands', 'dozens'] },
  { prompt: 'Saturn is so light for its size that it would ___ in a big enough bathtub.', answer: 'float', decoys: ['sink', 'melt', 'shatter'] },
  { prompt: 'The Sun holds about ___ percent of all the mass in the solar system.', answer: '99.8', decoys: ['75', '90', '50'] },
  { prompt: 'Halley\'s Comet swings past Earth roughly every ___ years.', answer: '76', decoys: ['50', '100', '33'] },
  { prompt: 'One year on Neptune lasts about ___ Earth years.', answer: '165', decoys: ['84', '29', '250'] },
  { prompt: 'The first animals sent into space, in 1947, were ___.', answer: 'fruit flies', decoys: ['mice', 'monkeys', 'spiders'] },
  { prompt: 'Measured from base to peak, the world\'s tallest mountain is ___.', answer: 'Mauna Kea', decoys: ['K2', 'Denali', 'Kilimanjaro'] },
  { prompt: 'Tree seeds that orbited the Moon on Apollo 14 were planted across the US and became known as ___.', answer: 'Moon Trees', decoys: ['Space Pines', 'Star Oaks', 'Apollo Elms'] },
  { prompt: 'Pluto was named by an 11-year-old girl from ___.', answer: 'Oxford', decoys: ['Arizona', 'Boston', 'Dublin'] },

  // Food
  { prompt: 'Before rubber erasers, people rubbed out pencil marks with ___.', answer: 'bread', decoys: ['wax', 'cheese', 'clay'] },
  { prompt: 'In the 1830s, tomato ketchup was sold as a ___.', answer: 'medicine', decoys: ['hair tonic', 'shoe polish', 'furniture stain'] },
  { prompt: 'Before the 1600s, most farmed carrots were ___ or yellow, not orange.', answer: 'purple', decoys: ['blue', 'green', 'pink'] },
  { prompt: 'Peanuts aren\'t really nuts. They\'re ___.', answer: 'legumes', decoys: ['tubers', 'grains', 'berries'] },
  { prompt: 'Almonds are the seeds of a fruit closely related to the ___.', answer: 'peach', decoys: ['coconut', 'olive', 'walnut'] },
  { prompt: 'A pineapple plant takes about ___ years to produce one pineapple.', answer: 'two', decoys: ['five', 'ten', 'seven'] },
  { prompt: 'In Japan, it is a popular Christmas tradition to eat ___.', answer: 'KFC', decoys: ['sushi', 'ramen', 'pizza'] },
  { prompt: 'Hawaiian pizza was invented in ___.', answer: 'Canada', decoys: ['Hawaii', 'Australia', 'Sweden'] },
  { prompt: 'German chocolate cake is named after an American chocolate maker called Samuel ___.', answer: 'German', decoys: ['Hershey', 'Schmidt', 'Fudge'] },
  { prompt: 'The Caesar salad was invented in ___.', answer: 'Mexico', decoys: ['Italy', 'Greece', 'France'] },
  { prompt: 'Worcestershire sauce is made with fermented ___.', answer: 'anchovies', decoys: ['mushrooms', 'plums', 'beetles'] },
  { prompt: 'The word "orange" named the ___ before it named the color.', answer: 'fruit', decoys: ['sunset', 'flower', 'tiger'] },
  { prompt: 'Fresh cranberries are sorted for quality by checking whether they can ___.', answer: 'bounce', decoys: ['glow', 'squeak', 'whistle'] },
  { prompt: 'Apples float in water because they are about 25% ___.', answer: 'air', decoys: ['sugar', 'fiber', 'juice'] },
  { prompt: 'Coffee beans are actually the ___ of a fruit.', answer: 'seeds', decoys: ['roots', 'skins', 'flowers'] },
  { prompt: 'Each cashew nut grows hanging from the bottom of a ___.', answer: 'cashew apple', decoys: ['palm leaf', 'vine', 'flower'] },
  { prompt: 'White chocolate contains no ___.', answer: 'cocoa solids', decoys: ['sugar', 'milk', 'fat'] },
  { prompt: 'Broccoli, cabbage, kale and cauliflower are all the same plant ___.', answer: 'species', decoys: ['color', 'shape', 'size'] },
  { prompt: 'The Aztecs used cacao beans as ___.', answer: 'money', decoys: ['perfume', 'paint', 'jewelry'] },
  { prompt: 'Stored in huge piles, pistachios can spontaneously ___.', answer: 'catch fire', decoys: ['sprout', 'explode', 'turn blue'] },
  { prompt: 'Bananas are very slightly ___ because they contain potassium.', answer: 'radioactive', decoys: ['magnetic', 'sticky', 'salty'] },
  { prompt: 'In M&M\'s, one of the two M\'s stands for the surname ___.', answer: 'Mars', decoys: ['Milton', 'Miller', 'Morris'] },
  { prompt: 'The holes in Swiss cheese are called ___.', answer: 'eyes', decoys: ['pockets', 'bubbles', 'windows'] },
  { prompt: 'Many 18th-century Europeans believed tomatoes were ___.', answer: 'poisonous', decoys: ['magic', 'cursed', 'fish eggs'] },

  // Language
  { prompt: 'In Dutch, the @ symbol is nicknamed the "little ___ tail".', answer: 'monkey', decoys: ['pig', 'rat', 'dragon'] },
  { prompt: 'The word "robot" comes from a Czech word meaning ___.', answer: 'forced labor', decoys: ['metal man', 'machine', 'helper'] },
  { prompt: 'The Chinese word for "computer" literally means ___.', answer: 'electric brain', decoys: ['thinking box', 'number machine', 'light abacus'] },
  { prompt: 'The German word for "glove" literally means ___.', answer: 'hand shoe', decoys: ['hand hat', 'finger sock', 'palm coat'] },
  { prompt: 'The German word for "skunk" literally means ___.', answer: 'stink animal', decoys: ['smelly cat', 'stripe fox', 'nose enemy'] },
  { prompt: 'The French word for "potato" literally means ___.', answer: 'earth apple', decoys: ['ground bread', 'soil nut', 'dirt egg'] },
  { prompt: 'The Japanese word "karaoke" means ___.', answer: 'empty orchestra', decoys: ['singing alone', 'loud voice', 'bar music'] },
  { prompt: 'The word "muscle" comes from the Latin for ___.', answer: 'little mouse', decoys: ['strong arm', 'tight rope', 'small ox'] },
  { prompt: 'The word "hippopotamus" comes from the Greek for ___.', answer: 'river horse', decoys: ['water pig', 'mud cow', 'big mouth'] },
  { prompt: 'The word "dinosaur" comes from the Greek for ___.', answer: 'terrible lizard', decoys: ['giant bird', 'ancient beast', 'thunder feet'] },
  { prompt: 'The name LEGO comes from the Danish words "leg godt", meaning ___.', answer: 'play well', decoys: ['build big', 'little bricks', 'good toys'] },
  { prompt: 'The space between your eyebrows is called the ___.', answer: 'glabella', decoys: ['browline', 'frontlet', 'temple'] },
  { prompt: 'The groove between your nose and upper lip is called the ___.', answer: 'philtrum', decoys: ['glabella', 'septum', 'lunula'] },
  { prompt: 'The pale half-moon at the base of a fingernail is called the ___.', answer: 'lunula', decoys: ['cuticle', 'crescent', 'halo'] },
  { prompt: 'The dangly bit at the back of your throat is called the ___.', answer: 'uvula', decoys: ['epiglottis', 'tonsil', 'larynx'] },
  { prompt: 'The crack of a whip is actually a tiny ___.', answer: 'sonic boom', decoys: ['explosion', 'thunderclap', 'echo'] },
  { prompt: 'A combined question mark and exclamation mark is called an ___.', answer: 'interrobang', decoys: ['exclamaquest', 'shriekmark', 'quizbang'] },
  { prompt: 'The fear of the number 13 is called ___.', answer: 'triskaidekaphobia', decoys: ['tredecaphobia', 'numerophobia', 'unluckophobia'] },
  { prompt: 'An old-fashioned English word for "the day after tomorrow" is ___.', answer: 'overmorrow', decoys: ['nextmorrow', 'twomorrow', 'aftermorn'] },
  { prompt: 'The earthy smell of rain on dry ground is called ___.', answer: 'petrichor', decoys: ['ozonance', 'terrascent', 'raincense'] },
  { prompt: '"Defenestration" means throwing someone out of a ___.', answer: 'window', decoys: ['castle', 'fence', 'boat'] },
  { prompt: 'A googol is a 1 followed by ___ zeros.', answer: '100', decoys: ['1,000', '50', '64'] },
  { prompt: 'In medieval times, a "moment" was a unit of time lasting ___ seconds.', answer: '90', decoys: ['60', '10', '45'] },
  { prompt: '___ is the only letter that doesn\'t appear in any U.S. state name.', answer: 'Q', decoys: ['X', 'Z', 'J'] },
  { prompt: 'Maine is the only US state whose name has just one ___.', answer: 'syllable', decoys: ['vowel', 'consonant', 'capital letter'] },
  { prompt: 'The word "dollar" comes from the ___, a silver coin first minted in Bohemia.', answer: 'thaler', decoys: ['ducat', 'florin', 'guilder'] },
  { prompt: 'The name "Wendy" became popular thanks to the book ___.', answer: 'Peter Pan', decoys: ['Alice in Wonderland', 'The Secret Garden', 'Little Women'] },
  { prompt: 'The word "nerd" first appeared in print in a book by ___.', answer: 'Dr. Seuss', decoys: ['Roald Dahl', 'Mark Twain', 'Lewis Carroll'] },
  { prompt: 'Dr. Seuss wrote "Green Eggs and Ham" using only ___ different words.', answer: '50', decoys: ['100', '25', '75'] },

  // History & places
  { prompt: 'The University of Oxford is older than the ___ Empire.', answer: 'Aztec', decoys: ['Roman', 'Byzantine', 'Persian'] },
  { prompt: 'The Eiffel Tower was only supposed to stand for ___ years.', answer: '20', decoys: ['5', '50', '100'] },
  { prompt: 'When it was new, the Statue of Liberty was the color of a shiny ___.', answer: 'penny', decoys: ['gold coin', 'silver spoon', 'lemon'] },
  { prompt: 'The Hundred Years’ War actually lasted ___ years.', answer: '116', decoys: ['100', '99', '88'] },
  { prompt: 'Abraham Lincoln is honored in the National ___ Hall of Fame.', answer: 'Wrestling', decoys: ['Boxing', 'Chess', 'Fencing'] },
  { prompt: 'The Empire State Building has its own ___.', answer: 'ZIP code', decoys: ['currency', 'time zone', 'police force'] },
  { prompt: 'The Leaning Tower of Pisa took nearly ___ years to finish.', answer: '200', decoys: ['20', '50', '100'] },
  { prompt: 'The first Ferris wheel was built in 1893 to rival the ___.', answer: 'Eiffel Tower', decoys: ['Big Ben', 'Statue of Liberty', 'Colosseum'] },
  { prompt: 'Big Ben is actually the name of the ___.', answer: 'bell', decoys: ['clock', 'tower', 'architect'] },
  { prompt: 'The smaller "bluestones" of Stonehenge were hauled all the way from ___.', answer: 'Wales', decoys: ['France', 'Ireland', 'Cornwall'] },
  { prompt: 'Sudan has more ___ than Egypt.', answer: 'pyramids', decoys: ['camels', 'rivers', 'pharaohs'] },
  { prompt: 'Canada has more ___ than the rest of the world combined.', answer: 'lakes', decoys: ['moose', 'maple trees', 'hockey rinks'] },
  { prompt: 'Norway\'s King\'s Guard has knighted a ___.', answer: 'penguin', decoys: ['moose', 'reindeer', 'salmon'] },
  { prompt: 'The Alaskan town of Talkeetna had a ___ as its honorary mayor for about 20 years.', answer: 'cat', decoys: ['dog', 'moose', 'bear'] },
  { prompt: 'Nepal\'s time zone is ahead of UTC by 5 hours and ___ minutes.', answer: '45', decoys: ['30', '15', '20'] },
  { prompt: 'Nepal\'s flag is the only national flag that is not ___.', answer: 'rectangular', decoys: ['symmetrical', 'cotton', 'bordered'] },
  { prompt: 'The only two square national flags belong to Switzerland and ___.', answer: 'Vatican City', decoys: ['Monaco', 'Nepal', 'Japan'] },
  { prompt: 'In 2007, soldiers from ___ got lost at night and accidentally marched into Liechtenstein.', answer: 'Switzerland', decoys: ['Austria', 'Germany', 'Italy'] },
  { prompt: 'Liechtenstein\'s 80-man army came home from its last war in 1866 with ___ soldiers.', answer: '81', decoys: ['79', '80', '40'] },
  { prompt: 'Alaska is the westernmost and also the ___ US state.', answer: 'easternmost', decoys: ['southernmost', 'flattest', 'youngest'] },
  { prompt: 'Australia is wider than the ___.', answer: 'Moon', decoys: ['Sahara', 'United States', 'Mars'] },
  { prompt: 'Lake Baikal holds about ___ of the world\'s unfrozen fresh surface water.', answer: 'one fifth', decoys: ['half', 'one tenth', 'one third'] },
  { prompt: 'New Zealand has more ___ than people.', answer: 'sheep', decoys: ['kiwis', 'penguins', 'hobbits'] },
  { prompt: 'In Venice, it is illegal to feed the ___ in St Mark\'s Square.', answer: 'pigeons', decoys: ['cats', 'tourists', 'fish'] },

  // Inventions, tech & toys
  { prompt: 'Bubble wrap was first invented as a textured ___.', answer: 'wallpaper', decoys: ['floor mat', 'raincoat', 'pool cover'] },
  { prompt: 'Play-Doh was originally sold as ___.', answer: 'wallpaper cleaner', decoys: ['window putty', 'denture paste', 'bath soap'] },
  { prompt: 'The ashes of Ed Headrick, designer of the modern Frisbee, were molded into ___.', answer: 'Frisbees', decoys: ['golf balls', 'a statue', 'bowling balls'] },
  { prompt: 'The first computer mouse was made of ___.', answer: 'wood', decoys: ['tin', 'ivory', 'cardboard'] },
  { prompt: 'The first recorded computer "bug" was an actual ___ stuck in a machine.', answer: 'moth', decoys: ['beetle', 'spider', 'cockroach'] },
  { prompt: 'The first webcam was pointed at a ___ in a Cambridge University computer lab.', answer: 'coffee pot', decoys: ['fish tank', 'parking lot', 'bird feeder'] },
  { prompt: 'The first item ever sold on eBay was a broken ___.', answer: 'laser pointer', decoys: ['toaster', 'calculator', 'lava lamp'] },
  { prompt: 'The first video ever uploaded to YouTube was filmed at a ___.', answer: 'zoo', decoys: ['beach', 'bowling alley', 'birthday party'] },
  { prompt: 'Nintendo was founded in 1889 to make ___.', answer: 'playing cards', decoys: ['toy trains', 'umbrellas', 'kites'] },
  { prompt: 'Google\'s original name was ___.', answer: 'BackRub', decoys: ['SearchDog', 'WebCrawler', 'Findr'] },
  { prompt: 'Before it was called Pepsi, the drink was called ___.', answer: 'Brad\'s Drink', decoys: ['Caleb\'s Cola', 'Fizzy Brad', 'Pep Water'] },
  { prompt: 'Bluetooth is named after a 10th-century ___ king.', answer: 'Danish', decoys: ['Roman', 'Egyptian', 'Scottish'] },
  { prompt: 'Mr. Potato Head was the first toy ever advertised on ___.', answer: 'television', decoys: ['radio', 'billboards', 'cereal boxes'] },
  { prompt: 'The Slinky was invented by accident by a naval ___.', answer: 'engineer', decoys: ['cook', 'chaplain', 'pilot'] },
  { prompt: 'The microwave oven was invented after an engineer noticed a melted ___ in his pocket.', answer: 'chocolate bar', decoys: ['crayon', 'lip balm', 'cheese sandwich'] },
  { prompt: 'The Popsicle was invented by a boy aged ___ who left a drink outside overnight.', answer: '11', decoys: ['7', '15', '9'] },
  { prompt: 'Velcro was inspired by ___ stuck to a dog\'s fur.', answer: 'burrs', decoys: ['gum', 'snowballs', 'seaweed'] },
  { prompt: 'The first known vending machine, from ancient Egypt, dispensed ___.', answer: 'holy water', decoys: ['olive oil', 'wine', 'bread'] },
  { prompt: 'The first American mechanical alarm clock could only ring at ___.', answer: '4 a.m.', decoys: ['midnight', 'noon', '6 a.m.'] },
  { prompt: 'The Rubik\'s Cube was invented by a Hungarian professor of ___.', answer: 'architecture', decoys: ['math', 'physics', 'chemistry'] },
  { prompt: 'Monopoly grew out of "The Landlord\'s Game", which was designed to warn people about ___.', answer: 'monopolies', decoys: ['gambling', 'debt', 'taxes'] },
  { prompt: 'Barbie\'s full name is Barbara Millicent ___.', answer: 'Roberts', decoys: ['Johnson', 'Carter', 'Hughes'] },
  { prompt: 'Winnie-the-Pooh was named after a real bear from the Canadian city of ___.', answer: 'Winnipeg', decoys: ['Toronto', 'Vancouver', 'Calgary'] },
  { prompt: 'Kermit the Frog\'s first eyes were made from a cut-up ___.', answer: 'ping-pong ball', decoys: ['golf ball', 'bottle cap', 'egg cup'] },
  { prompt: 'Mario, of Super Mario fame, was originally called ___.', answer: 'Jumpman', decoys: ['Plumbman', 'Hammerman', 'Barrel Boy'] },
  { prompt: 'The Pac-Man ghosts are Blinky, Pinky, Inky and ___.', answer: 'Clyde', decoys: ['Dinky', 'Stinky', 'Winky'] },
  { prompt: 'Pac-Man\'s shape was inspired by a ___ with a slice missing.', answer: 'pizza', decoys: ['cake', 'pie', 'cheese wheel'] },
  { prompt: 'There are more possible games of ___ than atoms in the observable universe.', answer: 'chess', decoys: ['checkers', 'tic-tac-toe', 'Connect Four'] },

  // Film, TV & sport
  { prompt: 'The hum of a Star Wars lightsaber was made partly from the motor of an old ___.', answer: 'film projector', decoys: ['vacuum cleaner', 'fridge', 'hair dryer'] },
  { prompt: 'Chewbacca\'s voice was built partly from recordings of a ___.', answer: 'bear', decoys: ['camel', 'donkey', 'whale'] },
  { prompt: 'The fake blood in the shower scene of "Psycho" was ___.', answer: 'chocolate syrup', decoys: ['ketchup', 'cherry juice', 'red paint'] },
  { prompt: 'Walt Disney first wanted to name Mickey Mouse ___.', answer: 'Mortimer', decoys: ['Marvin', 'Milton', 'Maxwell'] },
  { prompt: 'Donald Duck\'s middle name is ___.', answer: 'Fauntleroy', decoys: ['Quackers', 'Duckworth', 'Beaksley'] },
  { prompt: 'Mickey Mouse was first voiced by ___.', answer: 'Walt Disney', decoys: ['Mel Blanc', 'Roy Disney', 'Ub Iwerks'] },
  { prompt: 'Scooby-Doo\'s full first name is ___.', answer: 'Scoobert', decoys: ['Scoobias', 'Scoobster', 'Scoobington'] },
  { prompt: 'Toto in "The Wizard of Oz" was played by a female dog named ___.', answer: 'Terry', decoys: ['Lucky', 'Daisy', 'Bella'] },
  { prompt: 'The first basketball hoops were ___.', answer: 'peach baskets', decoys: ['buckets', 'fishing nets', 'flower pots'] },
  { prompt: 'Volleyball was originally called ___.', answer: 'Mintonette', decoys: ['Netball', 'Mintball', 'Skyball'] },
  { prompt: 'Tennis balls at Wimbledon were ___ until 1986.', answer: 'white', decoys: ['orange', 'green', 'pink'] },
  { prompt: 'Tug of war was an Olympic sport until ___.', answer: '1920', decoys: ['1936', '1948', '1908'] },
  { prompt: 'From 1912 to 1948, the Olympics also awarded medals for ___.', answer: 'art', decoys: ['chess', 'cooking', 'bridge'] },
  { prompt: 'A regulation baseball has exactly ___ double stitches.', answer: '108', decoys: ['88', '100', '144'] },
  // Content v3 — appended from the reviewed word-games deck (never reorder; see header).
  { prompt: 'Kangaroos can\'t easily walk ___.', answer: 'backwards', decoys: ['uphill', 'on sand', 'in the rain'] },
  { prompt: 'Under ultraviolet light, platypus fur glows ___.', answer: 'blue-green', decoys: ['pink', 'orange', 'red'] },
  { prompt: 'Botanically, a raspberry is not a true berry, but an ___ is.', answer: 'avocado', decoys: ['apple', 'almond', 'olive'] },
  { prompt: 'Vanilla comes from the seed pods of an ___.', answer: 'orchid', decoys: ['iris', 'oak tree', 'aloe plant'] },
  { prompt: 'Saffron is made from the dried ___ of crocus flowers.', answer: 'stigmas', decoys: ['petals', 'roots', 'seeds'] },
  { prompt: 'Most "wasabi" served outside Japan is really dyed ___.', answer: 'horseradish', decoys: ['ginger', 'avocado', 'cabbage'] },
  { prompt: 'Fortune cookies as we know them were first served in ___, not China.', answer: 'California', decoys: ['Hong Kong', 'New York', 'Hawaii'] },
  { prompt: 'A chili pepper\'s heat is measured in ___ units.', answer: 'Scoville', decoys: ['Blaze', 'Kelvin', 'Pepperton'] },
  { prompt: 'The ___ is the only bone in the human body not connected to another bone.', answer: 'hyoid', decoys: ['kneecap', 'collarbone', 'tailbone'] },
  { prompt: 'Babies are born with kneecaps made of ___ instead of bone.', answer: 'cartilage', decoys: ['fat', 'muscle', 'jelly'] },
  { prompt: 'Your stomach grows a new lining every few ___.', answer: 'days', decoys: ['hours', 'months', 'years'] },
  { prompt: 'It\'s almost impossible to hum while holding your ___.', answer: 'nose', decoys: ['tongue', 'ears', 'elbows'] },
  { prompt: 'The word "___" can be typed using only the top letter row of a QWERTY keyboard.', answer: 'typewriter', decoys: ['keyboard', 'computer', 'printer'] },
  { prompt: '"Dreamt" is the only common English word that ends in the letters ___.', answer: 'mt', decoys: ['pt', 'wn', 'mb'] },
  { prompt: 'The word "salary" comes from the Latin word for ___.', answer: 'salt', decoys: ['silver', 'soldier', 'bread'] },
  { prompt: 'The word "disaster" literally means bad ___.', answer: 'star', decoys: ['weather', 'harvest', 'river'] },
  { prompt: 'Mr. Monopoly\'s original name was Rich Uncle ___.', answer: 'Pennybags', decoys: ['Moneybags', 'Bigbucks', 'Goldsworth'] },
  { prompt: 'The first text message ever sent said "___".', answer: 'Merry Christmas', decoys: ['Hello World', 'Can you hear me', 'Testing testing'] },
  { prompt: 'The first Apple computer went on sale for $___.', answer: '666.66', decoys: ['999.99', '500.00', '1,234.56'] },
  { prompt: 'Before it built cars, the company behind Toyota made automatic ___.', answer: 'looms', decoys: ['sewing machines', 'bicycles', 'typewriters'] },
  { prompt: 'Nokia began in 1865 as a mill making ___.', answer: 'wood pulp', decoys: ['flour', 'steel', 'cotton cloth'] },
  { prompt: 'Tetris was created in the ___.', answer: 'Soviet Union', decoys: ['Japan', 'Finland', 'Canada'] },
  { prompt: 'Penicillin was discovered when mold grew in a forgotten ___.', answer: 'petri dish', decoys: ['sandwich', 'loaf of bread', 'orange'] },
  { prompt: 'Darth Vader\'s breathing sound was made with a ___ regulator.', answer: 'scuba', decoys: ['hospital', 'vacuum', 'space suit'] },
  { prompt: 'The Anglo-Zanzibar War of 1896, the shortest war on record, was over in less than one ___.', answer: 'hour', decoys: ['minute', 'second', 'heartbeat'] },
  { prompt: 'In 1896, the first driver in Britain fined for speeding was doing about ___ mph.', answer: '8', decoys: ['15', '25', '40'] },
  { prompt: 'Before alarm clocks were common, "knocker-uppers" woke people by tapping on their ___ with long poles.', answer: 'windows', decoys: ['chimneys', 'roofs', 'gates'] },
  { prompt: 'During World War II, Princess Elizabeth, later Queen Elizabeth II, trained as a ___.', answer: 'mechanic', decoys: ['pilot', 'chef', 'nurse'] },
  { prompt: 'In 1952, Albert Einstein was offered the presidency of ___.', answer: 'Israel', decoys: ['Germany', 'Switzerland', 'Austria'] },
  { prompt: 'Olympic gold medals are made mostly of ___.', answer: 'silver', decoys: ['bronze', 'brass', 'copper'] },
  { prompt: 'Russia has a bigger surface area than ___.', answer: 'Pluto', decoys: ['the Moon', 'Mars', 'Mercury'] },
  { prompt: 'Compared with most planets, Venus spins ___.', answer: 'backwards', decoys: ['sideways', 'faster', 'in bursts'] },
  { prompt: 'A puffy cumulus cloud can weigh about as much as a hundred ___.', answer: 'elephants', decoys: ['feathers', 'bicycles', 'pianos'] },
  { prompt: 'Sound travels about four times faster through ___ than through air.', answer: 'water', decoys: ['space', 'fog', 'helium'] },
  { prompt: 'Counting its overseas territories, the country with the most time zones is ___.', answer: 'France', decoys: ['Russia', 'United States', 'China'] },
  { prompt: 'The city of Istanbul sits on two ___.', answer: 'continents', decoys: ['volcanoes', 'rivers', 'glaciers'] },
  { prompt: 'The Sahara Desert is roughly the size of the ___.', answer: 'United States', decoys: ['United Kingdom', 'India', 'Moon'] },
  { prompt: 'Vatican City is smaller than New York\'s ___.', answer: 'Central Park', decoys: ['Times Square', 'Grand Central Station', 'Empire State Building'] },
]
