// JUST ONE deck — everyday, family-friendly nouns that everyone at the table
// can clue: animals, food, objects, places and people. Lowercase a–z.
//
// APPEND-ONLY: the room seen history (games/{id}/seen/justone) is keyed by
// deck index, so never reorder or delete entries — add new words at the end.
// justone.test.js checks size, uniqueness, format and the shared denylist.
export const JUST_ONE_WORDS = [
  'airplane', 'airport', 'alligator', 'ambulance', 'anchor', 'anteater', 'apple', 'apron', 'aquarium', 'armchair',
  'astronaut', 'autumn', 'avalanche', 'avocado', 'backpack', 'bagpipe', 'bakery', 'ballerina', 'balloon', 'bamboo',
  'banana', 'bandage', 'bank', 'barn', 'baseball', 'basket', 'basketball', 'bathtub', 'battery', 'beach',
  'beard', 'beaver', 'bed', 'bee', 'beehive', 'bench', 'bicycle', 'binoculars', 'birthday', 'blanket',
  'blender', 'blizzard', 'blueberry', 'boat', 'bonfire', 'book', 'boomerang', 'bottle', 'bowling', 'bowtie',
  'bracelet', 'bread', 'bridge', 'broccoli', 'broom', 'brush', 'bubble', 'bucket', 'bus', 'butter',
  'butterfly', 'button', 'cabbage', 'cactus', 'cake', 'calendar', 'camel', 'camera', 'campfire', 'candle',
  'candy', 'canoe', 'car', 'cardboard', 'carousel', 'carrot', 'cashier', 'castle', 'cat', 'caterpillar',
  'cave', 'chair', 'chalk', 'cheese', 'cheetah', 'chef', 'cherry', 'chess', 'chicken', 'chimney',
  'chocolate', 'circus', 'clock', 'cloud', 'clown', 'coat', 'coconut', 'coffee', 'comet', 'compass',
  'computer', 'cookie', 'cork', 'corn', 'cow', 'cowboy', 'crab', 'crane', 'crayon', 'cricket',
  'crocodile', 'crown', 'cupcake', 'curtain', 'daisy', 'dentist', 'desert', 'dessert', 'detective', 'diamond',
  'diary', 'dinosaur', 'doctor', 'dog', 'doll', 'dolphin', 'donkey', 'donut', 'door', 'dragon',
  'dragonfly', 'drawer', 'drum', 'duck', 'eagle', 'earring', 'earthquake', 'easel', 'egg', 'elbow',
  'elephant', 'elevator', 'engine', 'envelope', 'eraser', 'farm', 'feather', 'fence', 'ferry', 'fireman',
  'fireplace', 'firework', 'fish', 'flag', 'flamingo', 'flashlight', 'flower', 'flute', 'fog', 'football',
  'forest', 'fork', 'fountain', 'fox', 'fridge', 'frog', 'garage', 'garden', 'garlic', 'gecko',
  'ghost', 'giraffe', 'glacier', 'glasses', 'globe', 'glove', 'gnome', 'goat', 'goggles', 'gold',
  'goldfish', 'gorilla', 'grandma', 'grape', 'grass', 'gravy', 'guitar', 'hairbrush', 'hamburger', 'hammer',
  'hammock', 'hamster', 'harbor', 'harp', 'hat', 'headphones', 'hedgehog', 'helicopter', 'helmet', 'hippo',
  'hive', 'honey', 'horse', 'hose', 'hospital', 'hotdog', 'house', 'ice', 'iceberg', 'igloo',
  'island', 'jacket', 'jam', 'jeans', 'jellyfish', 'jewel', 'jigsaw', 'juggler', 'juice', 'jungle',
  'kangaroo', 'kayak', 'ketchup', 'kettle', 'key', 'keyboard', 'king', 'kitchen', 'kite', 'kitten',
  'knight', 'koala', 'ladder', 'ladybug', 'lamp', 'lantern', 'lava', 'leaf', 'lemon', 'lemonade',
  'lettuce', 'library', 'lighthouse', 'lion', 'lipstick', 'lizard', 'lobster', 'lollipop', 'magician', 'magnet',
  'mailbox', 'mango', 'map', 'marshmallow', 'mask', 'meadow', 'mermaid', 'meteor', 'microphone', 'microwave',
  'milk', 'mirror', 'mitten', 'money', 'monkey', 'moon', 'moose', 'mop', 'mosquito', 'motorcycle',
  'mountain', 'mouse', 'muffin', 'mug', 'mummy', 'museum', 'mushroom', 'necklace', 'needle', 'nest',
  'newspaper', 'ninja', 'noodle', 'nose', 'notebook', 'nurse', 'ocean', 'octopus', 'onion', 'orange',
  'ostrich', 'oven', 'owl', 'paddle', 'paint', 'pajamas', 'palace', 'pancake', 'panda', 'parachute',
  'parade', 'parrot', 'passport', 'peacock', 'peanut', 'pear', 'pebble', 'pelican', 'pencil', 'penguin',
  'pepper', 'piano', 'pickle', 'picnic', 'pig', 'pillow', 'pilot', 'pineapple', 'pinecone', 'pirate',
  'pizza', 'planet', 'plumber', 'pond', 'popcorn', 'postcard', 'potato', 'present', 'pretzel', 'princess',
  'pudding', 'pumpkin', 'puppet', 'puppy', 'puzzle', 'pyramid', 'queen', 'quilt', 'rabbit', 'raccoon',
  'radio', 'rain', 'rainbow', 'rhino', 'riddle', 'robin', 'robot', 'rocket', 'rollercoaster', 'rose',
  'ruler', 'saddle', 'sailboat', 'salad', 'salt', 'sandal', 'sandcastle', 'sandwich', 'satellite', 'saxophone',
  'scarecrow', 'scarf', 'school', 'scissors', 'scooter', 'seahorse', 'seesaw', 'shark', 'sheep', 'shell',
  'ship', 'shoe', 'shovel', 'shower', 'skateboard', 'skeleton', 'ski', 'skunk', 'sled', 'slipper',
  'sloth', 'snail', 'snake', 'snowflake', 'snowman', 'soap', 'soccer', 'sock', 'sofa', 'soup',
  'spaghetti', 'spider', 'sponge', 'spoon', 'sprinkler', 'squirrel', 'stadium', 'stapler', 'star', 'starfish',
  'statue', 'stethoscope', 'strawberry', 'submarine', 'suitcase', 'sun', 'sundae', 'sunflower', 'sunglasses', 'superhero',
  'surfboard', 'sushi', 'swan', 'sweater', 'swing', 'taco', 'tambourine', 'teacher', 'teapot', 'teddy',
  'telephone', 'telescope', 'television', 'tennis', 'tent', 'tiara', 'tiger', 'toad', 'toaster', 'tomato',
  'toothbrush', 'tornado', 'tortoise', 'towel', 'tractor', 'train', 'trampoline', 'treasure', 'tree', 'trophy',
  'truck', 'trumpet', 'tuba', 'tulip', 'tunnel', 'turkey', 'turtle', 'umbrella', 'unicorn', 'vacuum',
  'vampire', 'vase', 'vest', 'violin', 'volcano', 'waffle', 'wagon', 'wallet', 'walnut', 'walrus',
  'wand', 'waterfall', 'watermelon', 'whale', 'wheel', 'whistle', 'wig', 'windmill', 'witch', 'wizard',
  'wolf', 'worm', 'yacht', 'yogurt', 'yoyo', 'zebra', 'zipper', 'zoo',
]
