// SKETCH deck — drawable words/phrases for the draw & guess party game. Each entry:
// { word: string, tier: 1 | 2 | 3 } — a rough "how easy to draw and guess" rating.
// pickOptions() offers exactly one word per tier every choosing phase, so the artist
// always has an easy/medium/hard spread:
//   tier 1 — concrete, iconic, single objects (e.g. "cat", "house", "sun")
//   tier 2 — everyday objects/actions, slightly trickier concrete things (e.g.
//            "birthday party", "juggling", "traffic jam")
//   tier 3 — harder common words, still short and drawable; avoid long idioms
//            and complicated phrases (e.g. "mirror", "dream", "detective")
//
// ⚠ RESIDUAL (UNFIXABLE) INFO LEAK: this deck ships in the client JS bundle, and the
// 3 offered `options` (deck indices) are public in Firebase — so any player who opens
// devtools can shortlist the 3 candidates. Sketch's commit scheme additionally
// publishes the SALT immediately (not withheld until reveal, unlike Wavelength/
// Fibbage), so a determined player can also hash each of the 3 candidates locally
// against the public `commitment.hash` and read the real word BEFORE the round ends
// (see deriveWord() in sketchLogic.js — this is the same function honest clients use
// to show the word at reveal). This is an accepted leak at the same trust tier as
// Fibbage's bundled answer key — the platform has no trusted server to keep a word
// secret from a client willing to inspect its own network traffic / JS bundle. It only
// defends against a spectator glancing at a single Firebase field. See the
// commit-reveal trust-model note in docs/prds/README.md.

export const SKETCH_WORDS = [
  // --- tier 1 -------------------------------------------------------------
  { word: 'cat', tier: 1 }, { word: 'dog', tier: 1 }, { word: 'house', tier: 1 },
  { word: 'sun', tier: 1 }, { word: 'moon', tier: 1 }, { word: 'star', tier: 1 },
  { word: 'tree', tier: 1 }, { word: 'flower', tier: 1 }, { word: 'fish', tier: 1 },
  { word: 'bird', tier: 1 }, { word: 'car', tier: 1 }, { word: 'boat', tier: 1 },
  { word: 'apple', tier: 1 }, { word: 'banana', tier: 1 }, { word: 'book', tier: 1 },
  { word: 'chair', tier: 1 }, { word: 'table', tier: 1 }, { word: 'clock', tier: 1 },
  { word: 'cup', tier: 1 }, { word: 'hat', tier: 1 }, { word: 'shoe', tier: 1 },
  { word: 'umbrella', tier: 1 }, { word: 'balloon', tier: 1 }, { word: 'kite', tier: 1 },
  { word: 'ball', tier: 1 }, { word: 'bicycle', tier: 1 }, { word: 'guitar', tier: 1 },
  { word: 'drum', tier: 1 }, { word: 'key', tier: 1 }, { word: 'door', tier: 1 },
  { word: 'window', tier: 1 }, { word: 'ladder', tier: 1 }, { word: 'bridge', tier: 1 },
  { word: 'mountain', tier: 1 }, { word: 'cloud', tier: 1 }, { word: 'rainbow', tier: 1 },
  { word: 'snowman', tier: 1 }, { word: 'candle', tier: 1 }, { word: 'lightbulb', tier: 1 },
  { word: 'phone', tier: 1 }, { word: 'camera', tier: 1 }, { word: 'glasses', tier: 1 },
  { word: 'crown', tier: 1 }, { word: 'ring', tier: 1 }, { word: 'heart', tier: 1 },
  { word: 'spider', tier: 1 }, { word: 'snake', tier: 1 }, { word: 'frog', tier: 1 },
  { word: 'rabbit', tier: 1 }, { word: 'duck', tier: 1 }, { word: 'owl', tier: 1 },
  { word: 'bee', tier: 1 }, { word: 'ant', tier: 1 }, { word: 'whale', tier: 1 },
  { word: 'octopus', tier: 1 }, { word: 'crab', tier: 1 }, { word: 'snail', tier: 1 },
  { word: 'turtle', tier: 1 }, { word: 'penguin', tier: 1 }, { word: 'elephant', tier: 1 },
  { word: 'giraffe', tier: 1 }, { word: 'lion', tier: 1 }, { word: 'tiger', tier: 1 },
  { word: 'monkey', tier: 1 }, { word: 'horse', tier: 1 }, { word: 'cow', tier: 1 },
  { word: 'pig', tier: 1 }, { word: 'sheep', tier: 1 }, { word: 'chicken', tier: 1 },
  { word: 'egg', tier: 1 }, { word: 'pizza', tier: 1 }, { word: 'hamburger', tier: 1 },
  { word: 'ice cream', tier: 1 }, { word: 'cake', tier: 1 }, { word: 'cookie', tier: 1 },
  { word: 'pretzel', tier: 1 }, { word: 'carrot', tier: 1 }, { word: 'mushroom', tier: 1 },
  { word: 'cactus', tier: 1 }, { word: 'volcano', tier: 1 }, { word: 'island', tier: 1 },
  { word: 'anchor', tier: 1 }, { word: 'compass', tier: 1 }, { word: 'telescope', tier: 1 },
  { word: 'robot', tier: 1 }, { word: 'rocket', tier: 1 }, { word: 'airplane', tier: 1 },
  { word: 'train', tier: 1 }, { word: 'bus', tier: 1 }, { word: 'skateboard', tier: 1 },
  { word: 'bed', tier: 1 }, { word: 'sofa', tier: 1 }, { word: 'pillow', tier: 1 },
  { word: 'blanket', tier: 1 }, { word: 'lamp', tier: 1 }, { word: 'desk', tier: 1 },
  { word: 'pencil', tier: 1 }, { word: 'crayon', tier: 1 }, { word: 'paintbrush', tier: 1 },
  { word: 'backpack', tier: 1 }, { word: 'lunchbox', tier: 1 }, { word: 'bottle', tier: 1 },
  { word: 'spoon', tier: 1 }, { word: 'fork', tier: 1 }, { word: 'plate', tier: 1 },
  { word: 'bowl', tier: 1 }, { word: 'toothbrush', tier: 1 }, { word: 'soap', tier: 1 },
  { word: 'towel', tier: 1 }, { word: 'mirror', tier: 1 }, { word: 'comb', tier: 1 },
  { word: 'sock', tier: 1 }, { word: 'shirt', tier: 1 }, { word: 'pants', tier: 1 },
  { word: 'dress', tier: 1 }, { word: 'coat', tier: 1 }, { word: 'scarf', tier: 1 },
  { word: 'glove', tier: 1 }, { word: 'belt', tier: 1 }, { word: 'wallet', tier: 1 },
  { word: 'purse', tier: 1 }, { word: 'box', tier: 1 }, { word: 'gift', tier: 1 },
  { word: 'map', tier: 1 }, { word: 'flag', tier: 1 }, { word: 'coin', tier: 1 },
  { word: 'magnet', tier: 1 }, { word: 'battery', tier: 1 }, { word: 'remote', tier: 1 },
  { word: 'keyboard', tier: 1 }, { word: 'mouse', tier: 1 }, { word: 'television', tier: 1 },
  { word: 'radio', tier: 1 }, { word: 'microphone', tier: 1 }, { word: 'headphones', tier: 1 },
  { word: 'violin', tier: 1 }, { word: 'piano', tier: 1 }, { word: 'trumpet', tier: 1 },
  { word: 'saxophone', tier: 1 }, { word: 'hammer', tier: 1 }, { word: 'saw', tier: 1 },
  { word: 'nail', tier: 1 }, { word: 'screwdriver', tier: 1 }, { word: 'wrench', tier: 1 },
  { word: 'paint can', tier: 1 }, { word: 'trash can', tier: 1 }, { word: 'mailbox', tier: 1 },
  { word: 'fence', tier: 1 }, { word: 'gate', tier: 1 }, { word: 'chimney', tier: 1 },

  // --- tier 2 -------------------------------------------------------------
  { word: 'birthday party', tier: 2 }, { word: 'juggling', tier: 2 },
  { word: 'sandcastle', tier: 2 }, { word: 'campfire', tier: 2 },
  { word: 'snowball fight', tier: 2 }, { word: 'roller coaster', tier: 2 },
  { word: 'fireworks', tier: 2 }, { word: 'tightrope walker', tier: 2 },
  { word: 'scuba diver', tier: 2 }, { word: 'mummy', tier: 2 },
  { word: 'pirate ship', tier: 2 }, { word: 'treasure chest', tier: 2 },
  { word: 'magic wand', tier: 2 }, { word: 'wizard hat', tier: 2 },
  { word: 'dragon', tier: 2 }, { word: 'unicorn', tier: 2 }, { word: 'mermaid', tier: 2 },
  { word: 'ghost', tier: 2 }, { word: 'vampire', tier: 2 }, { word: 'werewolf', tier: 2 },
  { word: 'zombie', tier: 2 }, { word: 'superhero cape', tier: 2 },
  { word: 'knight in armor', tier: 2 }, { word: 'castle', tier: 2 },
  { word: 'drawbridge', tier: 2 }, { word: 'waterfall', tier: 2 },
  { word: 'desert oasis', tier: 2 }, { word: 'igloo', tier: 2 },
  { word: 'lighthouse', tier: 2 }, { word: 'windmill', tier: 2 },
  { word: 'scarecrow', tier: 2 }, { word: 'beehive', tier: 2 },
  { word: 'spider web', tier: 2 }, { word: 'footprint', tier: 2 },
  { word: 'shadow puppet', tier: 2 }, { word: 'thunderstorm', tier: 2 },
  { word: 'tornado', tier: 2 }, { word: 'earthquake', tier: 2 },
  { word: 'avalanche', tier: 2 }, { word: 'quicksand', tier: 2 }, { word: 'maze', tier: 2 },
  { word: 'seesaw', tier: 2 }, { word: 'trampoline', tier: 2 }, { word: 'hopscotch', tier: 2 },
  { word: 'tug of war', tier: 2 }, { word: 'arm wrestling', tier: 2 },
  { word: 'thumb war', tier: 2 }, { word: 'piggyback ride', tier: 2 },
  { word: 'sleepwalking', tier: 2 }, { word: 'snoring', tier: 2 }, { word: 'hiccups', tier: 2 },
  { word: 'sneezing', tier: 2 }, { word: 'yawning', tier: 2 }, { word: 'whispering', tier: 2 },
  { word: 'tiptoeing', tier: 2 }, { word: 'somersault', tier: 2 }, { word: 'cartwheel', tier: 2 },
  { word: 'handstand', tier: 2 }, { word: 'high five', tier: 2 }, { word: 'fist bump', tier: 2 },
  { word: 'group hug', tier: 2 }, { word: 'staring contest', tier: 2 },
  { word: 'hide and seek', tier: 2 }, { word: 'musical chairs', tier: 2 },
  { word: 'jump rope', tier: 2 }, { word: 'board game', tier: 2 },
  { word: 'puzzle piece', tier: 2 }, { word: 'domino effect', tier: 2 },
  { word: 'house of cards', tier: 2 }, { word: 'paper airplane', tier: 2 },
  { word: 'origami crane', tier: 2 }, { word: 'bubble wrap', tier: 2 },
  { word: 'rubber band', tier: 2 }, { word: 'clothesline', tier: 2 },
  { word: 'vacuum cleaner', tier: 2 }, { word: 'lawnmower', tier: 2 },
  { word: 'wheelbarrow', tier: 2 }, { word: 'garden hose', tier: 2 },
  { word: 'birdhouse', tier: 2 }, { word: 'scaffolding', tier: 2 },
  { word: 'traffic jam', tier: 2 }, { word: 'parking lot', tier: 2 },
  { word: 'crosswalk', tier: 2 }, { word: 'escalator', tier: 2 }, { word: 'elevator', tier: 2 },
  { word: 'revolving door', tier: 2 }, { word: 'fire escape', tier: 2 },
  { word: 'fire hydrant', tier: 2 }, { word: 'manhole cover', tier: 2 },
  { word: 'street lamp', tier: 2 },
  { word: 'brushing teeth', tier: 2 }, { word: 'washing dishes', tier: 2 },
  { word: 'taking a bath', tier: 2 }, { word: 'making a bed', tier: 2 },
  { word: 'reading a book', tier: 2 }, { word: 'flying a kite', tier: 2 },
  { word: 'walking a dog', tier: 2 }, { word: 'feeding a cat', tier: 2 },
  { word: 'riding a bike', tier: 2 }, { word: 'driving a car', tier: 2 },
  { word: 'catching a fish', tier: 2 }, { word: 'climbing a tree', tier: 2 },
  { word: 'planting flowers', tier: 2 }, { word: 'watering plants', tier: 2 },
  { word: 'building a snowman', tier: 2 }, { word: 'eating pizza', tier: 2 },
  { word: 'baking cookies', tier: 2 }, { word: 'making popcorn', tier: 2 },
  { word: 'opening a gift', tier: 2 }, { word: 'blowing bubbles', tier: 2 },
  { word: 'tying shoes', tier: 2 }, { word: 'packing a bag', tier: 2 },
  { word: 'mailing a letter', tier: 2 }, { word: 'playing piano', tier: 2 },
  { word: 'playing guitar', tier: 2 }, { word: 'playing soccer', tier: 2 },
  { word: 'playing basketball', tier: 2 }, { word: 'throwing a ball', tier: 2 },
  { word: 'catching a ball', tier: 2 }, { word: 'flying a plane', tier: 2 },
  { word: 'sailing a boat', tier: 2 }, { word: 'waiting in line', tier: 2 },
  { word: 'crossing a bridge', tier: 2 }, { word: 'lost keys', tier: 2 },
  { word: 'broken umbrella', tier: 2 }, { word: 'flat tire', tier: 2 },
  { word: 'birthday cake', tier: 2 }, { word: 'dog bath', tier: 2 },
  { word: 'cat nap', tier: 2 }, { word: 'school bus', tier: 2 },

  // --- tier 3 -------------------------------------------------------------
  { word: 'detective', tier: 3 }, { word: 'spy', tier: 3 }, { word: 'secret', tier: 3 },
  { word: 'clue', tier: 3 }, { word: 'fingerprint', tier: 3 }, { word: 'footsteps', tier: 3 },
  { word: 'shadow', tier: 3 }, { word: 'echo', tier: 3 }, { word: 'dream', tier: 3 },
  { word: 'nightmare', tier: 3 }, { word: 'wish', tier: 3 }, { word: 'memory', tier: 3 },
  { word: 'idea', tier: 3 }, { word: 'question', tier: 3 }, { word: 'answer', tier: 3 },
  { word: 'surprise', tier: 3 }, { word: 'mistake', tier: 3 }, { word: 'promise', tier: 3 },
  { word: 'treasure map', tier: 3 }, { word: 'secret door', tier: 3 },
  { word: 'hidden cave', tier: 3 }, { word: 'monster mask', tier: 3 },
  { word: 'space helmet', tier: 3 }, { word: 'moon boots', tier: 3 },
  { word: 'laser beam', tier: 3 }, { word: 'time machine', tier: 3 },
  { word: 'invisible man', tier: 3 }, { word: 'magic mirror', tier: 3 },
  { word: 'crystal ball', tier: 3 }, { word: 'fortune teller', tier: 3 },
  { word: 'haunted house', tier: 3 }, { word: 'trapdoor', tier: 3 },
  { word: 'secret tunnel', tier: 3 }, { word: 'rope bridge', tier: 3 },
  { word: 'treehouse', tier: 3 }, { word: 'bird nest', tier: 3 },
  { word: 'bee swarm', tier: 3 }, { word: 'ant hill', tier: 3 },
  { word: 'dog collar', tier: 3 }, { word: 'cat whiskers', tier: 3 },
  { word: 'lion mane', tier: 3 }, { word: 'tiger stripes', tier: 3 },
  { word: 'zebra stripes', tier: 3 }, { word: 'peacock tail', tier: 3 },
  { word: 'octopus arms', tier: 3 }, { word: 'shark fin', tier: 3 },
  { word: 'whale spout', tier: 3 }, { word: 'turtle shell', tier: 3 },
  { word: 'snail trail', tier: 3 }, { word: 'spider bite', tier: 3 },
  { word: 'dragon egg', tier: 3 }, { word: 'unicorn horn', tier: 3 },
  { word: 'pirate flag', tier: 3 }, { word: 'shipwreck', tier: 3 },
  { word: 'message bottle', tier: 3 }, { word: 'sea monster', tier: 3 },
  { word: 'sand dune', tier: 3 }, { word: 'cave painting', tier: 3 },
  { word: 'fossil', tier: 3 }, { word: 'dinosaur bone', tier: 3 },
  { word: 'volcano ash', tier: 3 }, { word: 'lava', tier: 3 },
  { word: 'meteor', tier: 3 }, { word: 'comet', tier: 3 }, { word: 'satellite', tier: 3 },
  { word: 'planet ring', tier: 3 }, { word: 'alien', tier: 3 }, { word: 'ufo', tier: 3 },
  { word: 'robot arm', tier: 3 }, { word: 'broken robot', tier: 3 },
  { word: 'alarm clock', tier: 3 }, { word: 'stopwatch', tier: 3 },
  { word: 'hourglass', tier: 3 }, { word: 'calendar', tier: 3 },
  { word: 'birthday wish', tier: 3 }, { word: 'gift wrap', tier: 3 },
  { word: 'party hat', tier: 3 }, { word: 'confetti', tier: 3 },
  { word: 'parade float', tier: 3 }, { word: 'circus tent', tier: 3 },
  { word: 'clown nose', tier: 3 }, { word: 'magic trick', tier: 3 },
  { word: 'puppet show', tier: 3 }, { word: 'movie ticket', tier: 3 },
  { word: 'popcorn bucket', tier: 3 }, { word: 'ice skates', tier: 3 },
  { word: 'roller skates', tier: 3 }, { word: 'ski slope', tier: 3 },
  { word: 'surfboard', tier: 3 }, { word: 'life jacket', tier: 3 },
  { word: 'rain puddle', tier: 3 }, { word: 'snow angel', tier: 3 },
  { word: 'leaf pile', tier: 3 }, { word: 'wind chime', tier: 3 },
  { word: 'broken window', tier: 3 }, { word: 'leaky faucet', tier: 3 },
  { word: 'sticky note', tier: 3 }, { word: 'paper clip', tier: 3 },
  { word: 'rubber duck', tier: 3 }, { word: 'toy train', tier: 3 },
  { word: 'teddy bear', tier: 3 }, { word: 'yo-yo', tier: 3 },
  { word: 'hula hoop', tier: 3 }, { word: 'jigsaw puzzle', tier: 3 },
  { word: 'domino', tier: 3 }, { word: 'chess board', tier: 3 },
  { word: 'king crown', tier: 3 }, { word: 'queen crown', tier: 3 },
  { word: 'gold medal', tier: 3 }, { word: 'finish line', tier: 3 },

]
