// TRIVIA BLITZ deck (see docs/prds/trivia-blitz.md). Content v2 grows the v1
// 60-question starter to 300+ across 13 categories.
// Shape: { q, options[4], answer: 0-3, cat, diff: 1|2|3 }. `cat` is shown as an
// uppercase label; `diff` drives the easy→hard ordering in seededDraw().
//
// Curation bar: only settled, non-time-sensitive facts (no "current" holders,
// records likely to fall, or contested claims), one unambiguous answer, and
// distractors of the same type. src/lib/decks/trivia.test.js enforces the
// schema, minimum size, and prompt uniqueness.
//
// ⚠ RESIDUAL (UNFIXABLE) INFO LEAK — same acceptance as decks/fibbage.js: this
// deck ships in the client JS bundle, so a player who inspects it can look up
// answers. Here the leak is partially self-limiting: looking things up costs
// time, and speed is most of the score. Do not "fix" by moving the deck
// server-side — there is no server.

export const TRIVIA_DECK = [
  // Science
  { q: 'What gas do plants absorb from the air?', options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Helium'], answer: 2, cat: 'science', diff: 1 },
  { q: 'What is the chemical symbol for gold?', options: ['Go', 'Gd', 'Au', 'Ag'], answer: 2, cat: 'science', diff: 1 },
  { q: 'Which organ pumps blood through the body?', options: ['Lungs', 'Liver', 'Heart', 'Kidneys'], answer: 2, cat: 'science', diff: 1 },
  { q: 'What is the hardest natural substance?', options: ['Quartz', 'Diamond', 'Titanium', 'Obsidian'], answer: 1, cat: 'science', diff: 2 },
  { q: 'How long does sunlight take to reach Earth?', options: ['8 seconds', '8 minutes', '8 hours', '80 minutes'], answer: 1, cat: 'science', diff: 2 },
  { q: 'Which particle carries a negative charge?', options: ['Proton', 'Neutron', 'Electron', 'Positron'], answer: 2, cat: 'science', diff: 2 },
  { q: 'What does DNA stand for?', options: ['Deoxyribonucleic acid', 'Dinucleic acid', 'Dual nucleotide array', 'Diribonucleic acid'], answer: 0, cat: 'science', diff: 2 },
  { q: 'Which metal has the highest melting point?', options: ['Tungsten', 'Iron', 'Osmium', 'Platinum'], answer: 0, cat: 'science', diff: 3 },
  { q: 'Which of these letters appears in no chemical element symbol?', options: ['Z', 'X', 'K', 'J'], answer: 3, cat: 'science', diff: 3 },
  { q: 'At sea level, water boils at what temperature?', options: ['90°C', '100°C', '110°C', '120°C'], answer: 1, cat: 'science', diff: 1 },
  { q: 'Which blood cells carry oxygen around the body?', options: ['White blood cells', 'Platelets', 'Red blood cells', 'Plasma cells'], answer: 2, cat: 'science', diff: 2 },
  { q: 'What is the largest organ of the human body?', options: ['Liver', 'Brain', 'Lungs', 'Skin'], answer: 3, cat: 'science', diff: 2 },
  { q: 'How many bones are in the adult human body?', options: ['186', '206', '226', '306'], answer: 1, cat: 'science', diff: 2 },
  { q: 'Which gas makes up most of Earth\'s atmosphere?', options: ['Nitrogen', 'Oxygen', 'Carbon dioxide', 'Argon'], answer: 0, cat: 'science', diff: 2 },
  { q: 'What is the chemical symbol for sodium?', options: ['So', 'Sd', 'Sn', 'Na'], answer: 3, cat: 'science', diff: 2 },
  { q: 'Which force keeps our feet on the ground?', options: ['Magnetism', 'Gravity', 'Friction', 'Inertia'], answer: 1, cat: 'science', diff: 1 },
  { q: 'Who developed the theory of general relativity?', options: ['Isaac Newton', 'Niels Bohr', 'Albert Einstein', 'Galileo Galilei'], answer: 2, cat: 'science', diff: 1 },
  { q: 'What is the smallest bone in the human body?', options: ['Stapes', 'Femur', 'Radius', 'Patella'], answer: 0, cat: 'science', diff: 3 },
  { q: 'Electrical resistance is measured in which unit?', options: ['Volt', 'Ampere', 'Watt', 'Ohm'], answer: 3, cat: 'science', diff: 2 },
  { q: 'What is the pH of pure water at 25°C?', options: ['5', '7', '9', '14'], answer: 1, cat: 'science', diff: 3 },
  { q: 'Which vitamin does your skin make in sunlight?', options: ['Vitamin D', 'Vitamin A', 'Vitamin C', 'Vitamin K'], answer: 0, cat: 'science', diff: 2 },
  { q: 'Which part of a cell is called its "powerhouse"?', options: ['Nucleus', 'Ribosome', 'Mitochondrion', 'Cell wall'], answer: 2, cat: 'science', diff: 1 },
  { q: 'Which element has the atomic number 1?', options: ['Helium', 'Hydrogen', 'Lithium', 'Oxygen'], answer: 1, cat: 'science', diff: 2 },
  { q: 'Roughly how fast does light travel in a vacuum?', options: ['300 km per second', '30,000 km per second', '300,000 km per second', '3 million km per second'], answer: 2, cat: 'science', diff: 3 },
  { q: 'Which scientist is famous for three laws of motion?', options: ['Charles Darwin', 'Marie Curie', 'Louis Pasteur', 'Isaac Newton'], answer: 3, cat: 'science', diff: 1 },
  { q: 'Marie Curie won Nobel Prizes in physics and which other field?', options: ['Medicine', 'Chemistry', 'Peace', 'Literature'], answer: 1, cat: 'science', diff: 2 },
  { q: 'Which organ produces insulin?', options: ['Pancreas', 'Liver', 'Kidney', 'Spleen'], answer: 0, cat: 'science', diff: 2 },
  { q: 'Which element has the symbol Fe?', options: ['Fluorine', 'Lead', 'Iron', 'Francium'], answer: 2, cat: 'science', diff: 2 },
  { q: 'How many chambers does the human heart have?', options: ['Two', 'Three', 'Four', 'Five'], answer: 2, cat: 'science', diff: 1 },

  // Space
  { q: 'Which planet has the most moons?', options: ['Saturn', 'Jupiter', 'Mars', 'Neptune'], answer: 0, cat: 'space', diff: 1 },
  { q: 'Which planet is known as the Red Planet?', options: ['Venus', 'Mars', 'Jupiter', 'Mercury'], answer: 1, cat: 'space', diff: 1 },
  { q: 'Which is the largest planet in our solar system?', options: ['Saturn', 'Neptune', 'Uranus', 'Jupiter'], answer: 3, cat: 'space', diff: 1 },
  { q: 'Which planet is closest to the Sun?', options: ['Mercury', 'Venus', 'Mars', 'Earth'], answer: 0, cat: 'space', diff: 1 },
  { q: 'What is the name of our home galaxy?', options: ['Andromeda', 'Triangulum', 'Milky Way', 'Whirlpool'], answer: 2, cat: 'space', diff: 1 },
  { q: 'Which is the hottest planet in our solar system?', options: ['Mercury', 'Venus', 'Mars', 'Jupiter'], answer: 1, cat: 'space', diff: 2 },
  { q: 'Who was the first human to travel into space?', options: ['Neil Armstrong', 'Alan Shepard', 'John Glenn', 'Yuri Gagarin'], answer: 3, cat: 'space', diff: 2 },
  { q: 'Which planet is best known for its bright, wide rings?', options: ['Saturn', 'Mars', 'Mercury', 'Venus'], answer: 0, cat: 'space', diff: 1 },
  { q: 'What was the first artificial satellite, launched in 1957?', options: ['Explorer 1', 'Vostok 1', 'Sputnik 1', 'Telstar'], answer: 2, cat: 'space', diff: 2 },
  { q: 'Roughly how strong is the Moon\'s gravity compared with Earth\'s?', options: ['One-half', 'One-third', 'One-sixth', 'One-tenth'], answer: 2, cat: 'space', diff: 3 },
  { q: 'Which world was reclassified as a dwarf planet in 2006?', options: ['Ceres', 'Pluto', 'Eris', 'Makemake'], answer: 1, cat: 'space', diff: 1 },
  { q: 'What is the closest star to Earth?', options: ['Proxima Centauri', 'Sirius', 'Polaris', 'The Sun'], answer: 3, cat: 'space', diff: 2 },
  { q: 'Which NASA program landed astronauts on the Moon from 1969 to 1972?', options: ['Gemini', 'Mercury', 'Apollo', 'Skylab'], answer: 2, cat: 'space', diff: 1 },
  { q: 'Which planet has a giant storm called the Great Red Spot?', options: ['Jupiter', 'Mars', 'Saturn', 'Neptune'], answer: 0, cat: 'space', diff: 2 },
  { q: 'A light-year is a measure of what?', options: ['Time', 'Distance', 'Brightness', 'Speed'], answer: 1, cat: 'space', diff: 2 },
  { q: 'Which planet is tilted so far it orbits the Sun on its side?', options: ['Neptune', 'Saturn', 'Uranus', 'Venus'], answer: 2, cat: 'space', diff: 3 },
  { q: 'Olympus Mons, the tallest volcano in the solar system, is on which planet?', options: ['Venus', 'Mercury', 'Jupiter', 'Mars'], answer: 3, cat: 'space', diff: 3 },
  { q: 'How many planets are in our solar system?', options: ['Seven', 'Eight', 'Nine', 'Ten'], answer: 1, cat: 'space', diff: 1 },
  { q: 'Which space telescope was launched in 1990?', options: ['Hubble', 'Kepler', 'Spitzer', 'James Webb'], answer: 0, cat: 'space', diff: 2 },
  { q: 'What were the first animals deliberately sent into space, in 1947?', options: ['Mice', 'Monkeys', 'Dogs', 'Fruit flies'], answer: 3, cat: 'space', diff: 3 },

  // Animals
  { q: 'How many legs does a spider have?', options: ['Six', 'Eight', 'Ten', 'Twelve'], answer: 1, cat: 'animals', diff: 1 },
  { q: 'Which animal is the tallest?', options: ['Elephant', 'Giraffe', 'Ostrich', 'Moose'], answer: 1, cat: 'animals', diff: 1 },
  { q: 'What is the largest animal on Earth?', options: ['African elephant', 'Sperm whale', 'Blue whale', 'Giant squid'], answer: 2, cat: 'animals', diff: 1 },
  { q: 'What is the fastest land animal?', options: ['Cheetah', 'Lion', 'Pronghorn', 'Greyhound'], answer: 0, cat: 'animals', diff: 1 },
  { q: 'Which is the largest bird in the world?', options: ['Emu', 'Albatross', 'Condor', 'Ostrich'], answer: 3, cat: 'animals', diff: 1 },
  { q: 'What is a baby kangaroo called?', options: ['Cub', 'Joey', 'Kit', 'Calf'], answer: 1, cat: 'animals', diff: 1 },
  { q: 'Which animal is nicknamed the "ship of the desert"?', options: ['Horse', 'Donkey', 'Camel', 'Llama'], answer: 2, cat: 'animals', diff: 1 },
  { q: 'Which is the only mammal capable of true flight?', options: ['Flying squirrel', 'Sugar glider', 'Colugo', 'Bat'], answer: 3, cat: 'animals', diff: 2 },
  { q: 'How many legs does an insect have?', options: ['Four', 'Six', 'Eight', 'Ten'], answer: 1, cat: 'animals', diff: 1 },
  { q: 'What is a group of crows called?', options: ['A murder', 'A parliament', 'A gaggle', 'A pod'], answer: 0, cat: 'animals', diff: 2 },
  { q: 'What kind of animal is a Komodo dragon?', options: ['Snake', 'Crocodile', 'Lizard', 'Dinosaur'], answer: 2, cat: 'animals', diff: 2 },
  { q: 'Which is the largest species of shark?', options: ['Great white', 'Hammerhead', 'Tiger shark', 'Whale shark'], answer: 3, cat: 'animals', diff: 2 },
  { q: 'What do giant pandas mostly eat?', options: ['Bamboo', 'Eucalyptus', 'Fish', 'Berries'], answer: 0, cat: 'animals', diff: 1 },
  { q: 'Which bird is famous for being able to fly backwards?', options: ['Swallow', 'Hummingbird', 'Kingfisher', 'Sparrow'], answer: 1, cat: 'animals', diff: 2 },
  { q: 'Which of these mammals lays eggs?', options: ['Beaver', 'Otter', 'Platypus', 'Sloth'], answer: 2, cat: 'animals', diff: 2 },
  { q: 'What color is a polar bear\'s skin?', options: ['White', 'Pink', 'Grey', 'Black'], answer: 3, cat: 'animals', diff: 3 },
  { q: 'How many arms does a typical starfish have?', options: ['Four', 'Five', 'Six', 'Eight'], answer: 1, cat: 'animals', diff: 2 },
  { q: 'Which lizard is famous for changing the color of its skin?', options: ['Chameleon', 'Iguana', 'Gecko', 'Komodo dragon'], answer: 0, cat: 'animals', diff: 1 },
  { q: 'A dog\'s sense of what is its strongest?', options: ['Sight', 'Hearing', 'Smell', 'Taste'], answer: 2, cat: 'animals', diff: 1 },
  { q: 'What is the fastest bird in a dive?', options: ['Bald eagle', 'Peregrine falcon', 'Swift', 'Albatross'], answer: 1, cat: 'animals', diff: 3 },
  { q: 'Which animal is the giraffe\'s only living relative in the giraffe family?', options: ['Okapi', 'Tapir', 'Gazelle', 'Zebra'], answer: 0, cat: 'animals', diff: 3 },

  // Geography
  { q: 'What is the capital of France?', options: ['Lyon', 'Marseille', 'Paris', 'Nice'], answer: 2, cat: 'geography', diff: 1 },
  { q: 'Which is the largest ocean?', options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'], answer: 3, cat: 'geography', diff: 1 },
  { q: 'On which continent is the Sahara desert?', options: ['Asia', 'Africa', 'Australia', 'South America'], answer: 1, cat: 'geography', diff: 1 },
  { q: 'Which country has the most time zones?', options: ['Russia', 'USA', 'France', 'China'], answer: 2, cat: 'geography', diff: 2 },
  { q: 'What is the longest river in Africa?', options: ['Congo', 'Nile', 'Niger', 'Zambezi'], answer: 1, cat: 'geography', diff: 2 },
  { q: 'Mount Everest sits on the border of Nepal and…', options: ['India', 'China', 'Bhutan', 'Pakistan'], answer: 1, cat: 'geography', diff: 2 },
  { q: 'Quito is the capital of which country?', options: ['Peru', 'Colombia', 'Ecuador', 'Bolivia'], answer: 2, cat: 'geography', diff: 2 },
  { q: 'The shore of which lake is the lowest land point on Earth?', options: ['Dead Sea', 'Caspian Sea', 'Lake Assal', 'Salton Sea'], answer: 0, cat: 'geography', diff: 3 },
  { q: 'Which is the largest continent by area?', options: ['Africa', 'North America', 'Europe', 'Asia'], answer: 3, cat: 'geography', diff: 1 },
  { q: 'What is the currency of Japan?', options: ['Won', 'Yuan', 'Yen', 'Ringgit'], answer: 2, cat: 'geography', diff: 1 },
  { q: 'What is the capital of Australia?', options: ['Sydney', 'Melbourne', 'Canberra', 'Perth'], answer: 2, cat: 'geography', diff: 2 },
  { q: 'What is the capital of Canada?', options: ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'], answer: 0, cat: 'geography', diff: 2 },
  { q: 'Which country is shaped like a boot?', options: ['Greece', 'Portugal', 'Spain', 'Italy'], answer: 3, cat: 'geography', diff: 1 },
  { q: 'What is the smallest country in the world by area?', options: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'], answer: 1, cat: 'geography', diff: 2 },
  { q: 'Which is the largest country by area?', options: ['Russia', 'Canada', 'China', 'USA'], answer: 0, cat: 'geography', diff: 1 },
  { q: 'Which river flows through London?', options: ['Seine', 'Danube', 'Thames', 'Rhine'], answer: 2, cat: 'geography', diff: 1 },
  { q: 'Mount Kilimanjaro is in which country?', options: ['Kenya', 'Uganda', 'Ethiopia', 'Tanzania'], answer: 3, cat: 'geography', diff: 2 },
  { q: 'What is the capital of Japan?', options: ['Kyoto', 'Tokyo', 'Osaka', 'Hiroshima'], answer: 1, cat: 'geography', diff: 1 },
  { q: 'Which US state is made up entirely of islands?', options: ['Hawaii', 'Florida', 'Alaska', 'Maine'], answer: 0, cat: 'geography', diff: 1 },
  { q: 'The ancient city of Petra is in which country?', options: ['Egypt', 'Lebanon', 'Jordan', 'Syria'], answer: 2, cat: 'geography', diff: 3 },
  { q: 'Which is the world\'s largest island that is not a continent?', options: ['Borneo', 'Madagascar', 'New Guinea', 'Greenland'], answer: 3, cat: 'geography', diff: 2 },
  { q: 'Which city sits on both sides of the Bosphorus, in Europe and Asia?', options: ['Athens', 'Istanbul', 'Cairo', 'Baku'], answer: 1, cat: 'geography', diff: 2 },
  { q: 'What is the deepest ocean trench on Earth?', options: ['Mariana Trench', 'Puerto Rico Trench', 'Java Trench', 'Tonga Trench'], answer: 0, cat: 'geography', diff: 3 },
  { q: 'What is the capital of Egypt?', options: ['Alexandria', 'Luxor', 'Giza', 'Cairo'], answer: 3, cat: 'geography', diff: 1 },
  { q: 'Which mountain range runs through Russia and marks part of the boundary between Europe and Asia?', options: ['Alps', 'Andes', 'Urals', 'Pyrenees'], answer: 2, cat: 'geography', diff: 3 },
  { q: 'What is the largest lake in Africa?', options: ['Lake Tanganyika', 'Lake Victoria', 'Lake Malawi', 'Lake Chad'], answer: 1, cat: 'geography', diff: 3 },
  { q: 'The Great Barrier Reef lies off the coast of which country?', options: ['Australia', 'Indonesia', 'Philippines', 'Fiji'], answer: 0, cat: 'geography', diff: 1 },
  { q: 'Which is the largest country in South America?', options: ['Argentina', 'Peru', 'Colombia', 'Brazil'], answer: 3, cat: 'geography', diff: 2 },
  { q: 'Reykjavík is the capital of which country?', options: ['Norway', 'Finland', 'Iceland', 'Denmark'], answer: 2, cat: 'geography', diff: 2 },
  { q: 'Marrakesh is a city in which country?', options: ['Morocco', 'Tunisia', 'Algeria', 'Egypt'], answer: 0, cat: 'geography', diff: 2 },

  // History
  { q: 'In which year did World War II end?', options: ['1943', '1944', '1945', '1946'], answer: 2, cat: 'history', diff: 1 },
  { q: 'Who was the first person to walk on the Moon?', options: ['Buzz Aldrin', 'Yuri Gagarin', 'Neil Armstrong', 'Michael Collins'], answer: 2, cat: 'history', diff: 1 },
  { q: 'The Great Pyramid was built in which country?', options: ['Mexico', 'Egypt', 'Sudan', 'Iraq'], answer: 1, cat: 'history', diff: 1 },
  { q: 'Which empire built Machu Picchu?', options: ['Aztec', 'Maya', 'Inca', 'Olmec'], answer: 2, cat: 'history', diff: 2 },
  { q: 'Who was the first President of the United States?', options: ['Thomas Jefferson', 'John Adams', 'Benjamin Franklin', 'George Washington'], answer: 3, cat: 'history', diff: 1 },
  { q: 'The Berlin Wall fell in which decade?', options: ['1970s', '1980s', '1990s', '2000s'], answer: 1, cat: 'history', diff: 2 },
  { q: 'Which ship famously sank in 1912?', options: ['Lusitania', 'Britannic', 'Titanic', 'Bismarck'], answer: 2, cat: 'history', diff: 1 },
  { q: 'Who was the last active pharaoh of ancient Egypt?', options: ['Nefertiti', 'Cleopatra VII', 'Hatshepsut', 'Ramesses II'], answer: 1, cat: 'history', diff: 3 },
  { q: 'The Rosetta Stone helped decode which script?', options: ['Cuneiform', 'Linear B', 'Hieroglyphics', 'Runes'], answer: 2, cat: 'history', diff: 3 },
  { q: 'In which year did Christopher Columbus first reach the Americas?', options: ['1392', '1492', '1592', '1692'], answer: 1, cat: 'history', diff: 2 },
  { q: 'Which ancient civilization built the Colosseum?', options: ['Romans', 'Greeks', 'Egyptians', 'Persians'], answer: 0, cat: 'history', diff: 1 },
  { q: 'Who was the first woman to fly solo across the Atlantic Ocean?', options: ['Bessie Coleman', 'Amy Johnson', 'Harriet Quimby', 'Amelia Earhart'], answer: 3, cat: 'history', diff: 3 },
  { q: 'Which famous wall was built to guard China\'s northern borders?', options: ['Hadrian\'s Wall', 'The Western Wall', 'The Great Wall', 'The Berlin Wall'], answer: 2, cat: 'history', diff: 1 },
  { q: 'The Wright brothers made the first powered airplane flight in which year?', options: ['1893', '1903', '1913', '1923'], answer: 1, cat: 'history', diff: 2 },
  { q: 'Which British monarch reigned for over 70 years, until 2022?', options: ['Elizabeth II', 'Victoria', 'Anne', 'Mary I'], answer: 0, cat: 'history', diff: 1 },
  { q: 'Whose expedition was the first to sail all the way around the world (1519–1522)?', options: ['Vasco da Gama', 'James Cook', 'Francis Drake', 'Ferdinand Magellan'], answer: 3, cat: 'history', diff: 2 },
  { q: 'The ancient Olympic Games began in which country?', options: ['Italy', 'Greece', 'Egypt', 'Turkey'], answer: 1, cat: 'history', diff: 1 },
  { q: 'Which famous English charter was sealed in 1215?', options: ['Magna Carta', 'Bill of Rights', 'Domesday Book', 'Treaty of Paris'], answer: 0, cat: 'history', diff: 2 },
  { q: 'Who introduced movable-type printing to Europe around 1440?', options: ['Leonardo da Vinci', 'Martin Luther', 'Johannes Gutenberg', 'Galileo Galilei'], answer: 2, cat: 'history', diff: 2 },
  { q: 'Which Roman city was buried by the eruption of Mount Vesuvius in AD 79?', options: ['Rome', 'Carthage', 'Ravenna', 'Pompeii'], answer: 3, cat: 'history', diff: 1 },
  { q: 'Who was the first emperor of Rome?', options: ['Julius Caesar', 'Augustus', 'Nero', 'Caligula'], answer: 1, cat: 'history', diff: 3 },
  { q: 'In which country did the Industrial Revolution begin?', options: ['Britain', 'France', 'Germany', 'United States'], answer: 0, cat: 'history', diff: 2 },
  { q: 'Which ancient people created cuneiform writing?', options: ['Egyptians', 'Greeks', 'Sumerians', 'Romans'], answer: 2, cat: 'history', diff: 3 },
  { q: 'Which ship carried the Pilgrims to America in 1620?', options: ['Santa Maria', 'Endeavour', 'Beagle', 'Mayflower'], answer: 3, cat: 'history', diff: 2 },
  { q: 'The Terracotta Army guards the tomb of which country\'s first emperor?', options: ['Japan', 'China', 'Korea', 'Mongolia'], answer: 1, cat: 'history', diff: 2 },
  { q: 'Nelson Mandela became president of which country in 1994?', options: ['South Africa', 'Kenya', 'Nigeria', 'Zimbabwe'], answer: 0, cat: 'history', diff: 1 },
  { q: 'Which Wonder of the Ancient World was a giant statue on the island of Rhodes?', options: ['The Lighthouse', 'The Hanging Gardens', 'The Colossus', 'The Mausoleum'], answer: 2, cat: 'history', diff: 3 },
  { q: 'Which country gave the Statue of Liberty to the United States?', options: ['Britain', 'Spain', 'Italy', 'France'], answer: 3, cat: 'history', diff: 1 },

  // Food
  { q: 'What is the main ingredient in guacamole?', options: ['Tomato', 'Avocado', 'Lime', 'Peas'], answer: 1, cat: 'food', diff: 1 },
  { q: 'Which nut is ground to make marzipan?', options: ['Almond', 'Peanut', 'Walnut', 'Cashew'], answer: 0, cat: 'food', diff: 2 },
  { q: 'What is the main ingredient of hummus?', options: ['Lentils', 'Fava beans', 'Chickpeas', 'Peas'], answer: 2, cat: 'food', diff: 1 },
  { q: 'Modern pizza was born in which Italian city?', options: ['Rome', 'Milan', 'Venice', 'Naples'], answer: 3, cat: 'food', diff: 2 },
  { q: 'What kind of food is Brie?', options: ['Bread', 'Cheese', 'Sausage', 'Pastry'], answer: 1, cat: 'food', diff: 1 },
  { q: 'Which spice comes from the dried stigmas of a crocus flower?', options: ['Turmeric', 'Paprika', 'Saffron', 'Cardamom'], answer: 2, cat: 'food', diff: 2 },
  { q: 'Which compound gives chili peppers their heat?', options: ['Capsaicin', 'Caffeine', 'Menthol', 'Tannin'], answer: 0, cat: 'food', diff: 3 },
  { q: 'Which fruit wears its seeds on the outside?', options: ['Raspberry', 'Blueberry', 'Kiwi', 'Strawberry'], answer: 3, cat: 'food', diff: 1 },
  { q: 'Tofu is made from which bean?', options: ['Kidney bean', 'Soybean', 'Black bean', 'Lima bean'], answer: 1, cat: 'food', diff: 2 },
  { q: 'Which Japanese dish is thinly sliced raw fish served without rice?', options: ['Tempura', 'Ramen', 'Sashimi', 'Udon'], answer: 2, cat: 'food', diff: 2 },
  { q: 'Paella comes from which country?', options: ['Spain', 'Italy', 'Mexico', 'Portugal'], answer: 0, cat: 'food', diff: 1 },
  { q: 'Risotto is made with which grain?', options: ['Barley', 'Oats', 'Wheat', 'Rice'], answer: 3, cat: 'food', diff: 2 },
  { q: 'Which vegetable gives borscht its deep red color?', options: ['Red cabbage', 'Beetroot', 'Tomato', 'Red pepper'], answer: 1, cat: 'food', diff: 2 },
  { q: 'Classic pesto is made with which herb?', options: ['Parsley', 'Mint', 'Basil', 'Coriander'], answer: 2, cat: 'food', diff: 1 },
  { q: 'Kimchi is a staple of which country\'s cuisine?', options: ['Korea', 'Japan', 'Thailand', 'Vietnam'], answer: 0, cat: 'food', diff: 1 },
  { q: 'Raisins are dried versions of which fruit?', options: ['Plums', 'Figs', 'Dates', 'Grapes'], answer: 3, cat: 'food', diff: 1 },
  { q: 'Pasta cooked so it is still firm to the bite is called…', options: ['Al forno', 'Al dente', 'Al fresco', 'Alfredo'], answer: 1, cat: 'food', diff: 2 },
  { q: 'Which cheese tops a classic Margherita pizza?', options: ['Cheddar', 'Parmesan', 'Mozzarella', 'Feta'], answer: 2, cat: 'food', diff: 1 },
  { q: 'Which fizzy drink is made by fermenting sweet tea?', options: ['Kombucha', 'Kefir', 'Kvass', 'Lassi'], answer: 0, cat: 'food', diff: 3 },
  { q: 'Wasabi is traditionally served with which dish?', options: ['Paella', 'Tacos', 'Curry', 'Sushi'], answer: 3, cat: 'food', diff: 1 },
  { q: 'Which fruit is caramelized in a classic French tarte Tatin?', options: ['Pear', 'Apple', 'Plum', 'Apricot'], answer: 1, cat: 'food', diff: 3 },
  { q: 'Which fruit is used to make traditional marmalade?', options: ['Apple', 'Orange', 'Cherry', 'Peach'], answer: 1, cat: 'food', diff: 2 },

  // Sports
  { q: 'How many players does a soccer team have on the field?', options: ['9', '10', '11', '12'], answer: 2, cat: 'sports', diff: 1 },
  { q: 'In which sport would you perform a slam dunk?', options: ['Volleyball', 'Basketball', 'Tennis', 'Handball'], answer: 1, cat: 'sports', diff: 1 },
  { q: 'How often are the Summer Olympics held?', options: ['Every 2 years', 'Every 3 years', 'Every 4 years', 'Every 5 years'], answer: 2, cat: 'sports', diff: 1 },
  { q: 'In tennis, what score comes after 30?', options: ['40', '45', '50', '60'], answer: 0, cat: 'sports', diff: 1 },
  { q: 'Which country won the first FIFA World Cup in 1930?', options: ['Brazil', 'Uruguay', 'Argentina', 'Italy'], answer: 1, cat: 'sports', diff: 2 },
  { q: 'How many rings are on the Olympic flag?', options: ['Four', 'Five', 'Six', 'Seven'], answer: 1, cat: 'sports', diff: 1 },
  { q: 'In Formula 1, which flag signals the end of the race?', options: ['Red', 'White', 'Checkered', 'Yellow'], answer: 2, cat: 'sports', diff: 1 },
  { q: 'A "goose egg" in sports scoring means…', options: ['Zero', 'One', 'A penalty', 'Overtime'], answer: 0, cat: 'sports', diff: 2 },
  { q: 'In bowling, what is a perfect score?', options: ['200', '250', '300', '360'], answer: 2, cat: 'sports', diff: 2 },
  { q: 'How many holes are in a standard round of golf?', options: ['9', '12', '24', '18'], answer: 3, cat: 'sports', diff: 1 },
  { q: 'Which sport is played with a shuttlecock?', options: ['Squash', 'Badminton', 'Table tennis', 'Lacrosse'], answer: 1, cat: 'sports', diff: 1 },
  { q: 'How long is a marathon?', options: ['13.1 miles', '20 miles', '26.2 miles', '30 miles'], answer: 2, cat: 'sports', diff: 2 },
  { q: 'The martial art judo comes from which country?', options: ['Japan', 'China', 'Korea', 'Thailand'], answer: 0, cat: 'sports', diff: 2 },
  { q: 'In cricket, how many balls are bowled in a standard over?', options: ['Four', 'Five', 'Eight', 'Six'], answer: 3, cat: 'sports', diff: 2 },
  { q: 'Which sport is played at Wimbledon?', options: ['Golf', 'Tennis', 'Cricket', 'Rugby'], answer: 1, cat: 'sports', diff: 1 },
  { q: 'How many players does each basketball team have on the court?', options: ['Five', 'Six', 'Seven', 'Eleven'], answer: 0, cat: 'sports', diff: 1 },
  { q: 'What is the standard maximum break in snooker?', options: ['100', '155', '147', '180'], answer: 2, cat: 'sports', diff: 3 },
  { q: 'What is the highest possible score with three darts?', options: ['150', '170', '200', '180'], answer: 3, cat: 'sports', diff: 2 },
  { q: 'In American football, how many points is a touchdown worth?', options: ['Three', 'Six', 'Seven', 'Two'], answer: 1, cat: 'sports', diff: 2 },
  { q: 'How many players does each indoor volleyball team have on court?', options: ['Six', 'Five', 'Seven', 'Nine'], answer: 0, cat: 'sports', diff: 2 },
  { q: 'In which sport does "love" mean a score of zero?', options: ['Golf', 'Cricket', 'Tennis', 'Bowling'], answer: 2, cat: 'sports', diff: 1 },
  { q: 'In darts, how many points is the inner bullseye worth?', options: ['25', '60', '100', '50'], answer: 3, cat: 'sports', diff: 2 },
  { q: 'Which sport uses the terms "birdie" and "eagle"?', options: ['Golf', 'Tennis', 'Cricket', 'Polo'], answer: 0, cat: 'sports', diff: 1 },
  { q: 'Where were the first modern Olympic Games held, in 1896?', options: ['Paris', 'Athens', 'London', 'Rome'], answer: 1, cat: 'sports', diff: 2 },
  { q: 'In baseball, how many strikes make a strikeout?', options: ['Two', 'Four', 'Three', 'Five'], answer: 2, cat: 'sports', diff: 1 },
  { q: 'Olympic gold medals are mostly made of which metal?', options: ['Gold', 'Bronze', 'Copper', 'Silver'], answer: 3, cat: 'sports', diff: 3 },
  { q: 'What was the first sport played on the Moon?', options: ['Golf', 'Baseball', 'Frisbee', 'Tennis'], answer: 0, cat: 'sports', diff: 3 },

  // Music
  { q: 'Which band released "Bohemian Rhapsody"?', options: ['The Beatles', 'Queen', 'Led Zeppelin', 'Pink Floyd'], answer: 1, cat: 'music', diff: 1 },
  { q: 'Which instrument has 88 keys?', options: ['Organ', 'Piano', 'Accordion', 'Harpsichord'], answer: 1, cat: 'music', diff: 2 },
  { q: 'How many strings does a standard guitar have?', options: ['Four', 'Five', 'Six', 'Eight'], answer: 2, cat: 'music', diff: 1 },
  { q: 'Who composed "Für Elise"?', options: ['Beethoven', 'Mozart', 'Bach', 'Chopin'], answer: 0, cat: 'music', diff: 2 },
  { q: 'Which band was made up of John, Paul, George and Ringo?', options: ['The Rolling Stones', 'The Who', 'The Kinks', 'The Beatles'], answer: 3, cat: 'music', diff: 1 },
  { q: 'How many lines make up a musical staff?', options: ['Four', 'Five', 'Six', 'Seven'], answer: 1, cat: 'music', diff: 2 },
  { q: 'Which singer is known as the "King of Pop"?', options: ['Elvis Presley', 'Prince', 'Michael Jackson', 'Stevie Wonder'], answer: 2, cat: 'music', diff: 1 },
  { q: 'A timpanist plays which instruments?', options: ['Kettle drums', 'Trumpets', 'Harps', 'Cellos'], answer: 0, cat: 'music', diff: 3 },
  { q: 'Which composer kept writing music after going deaf?', options: ['Vivaldi', 'Handel', 'Haydn', 'Beethoven'], answer: 3, cat: 'music', diff: 2 },
  { q: 'Which Italian composer wrote "The Four Seasons"?', options: ['Verdi', 'Vivaldi', 'Puccini', 'Rossini'], answer: 1, cat: 'music', diff: 2 },
  { q: 'The didgeridoo is a traditional instrument from which country?', options: ['New Zealand', 'South Africa', 'Australia', 'Brazil'], answer: 2, cat: 'music', diff: 2 },
  { q: 'How many musicians play in a quartet?', options: ['Four', 'Two', 'Three', 'Five'], answer: 0, cat: 'music', diff: 1 },
  { q: 'In sheet music, what does "forte" tell you to play?', options: ['Slowly', 'Softly', 'Quickly', 'Loudly'], answer: 3, cat: 'music', diff: 2 },
  { q: 'Which ABBA song shares its name with a famous battle of 1815?', options: ['Fernando', 'Waterloo', 'Dancing Queen', 'Mamma Mia'], answer: 1, cat: 'music', diff: 2 },
  { q: 'Which large orchestral instrument has pedals and strings that are plucked by hand?', options: ['Cello', 'Piano', 'Harp', 'Double bass'], answer: 2, cat: 'music', diff: 2 },
  { q: 'Which rock and roll star was nicknamed "The King"?', options: ['Elvis Presley', 'Chuck Berry', 'Little Richard', 'Buddy Holly'], answer: 0, cat: 'music', diff: 1 },
  { q: 'In 4/4 time, how many beats does a whole note last?', options: ['One', 'Two', 'Eight', 'Four'], answer: 3, cat: 'music', diff: 3 },
  { q: 'Which woodwind instrument is held sideways and has no reed?', options: ['Clarinet', 'Flute', 'Oboe', 'Bassoon'], answer: 1, cat: 'music', diff: 2 },
  { q: 'The tango dance first developed in which country?', options: ['Spain', 'Brazil', 'Argentina', 'Cuba'], answer: 2, cat: 'music', diff: 2 },
  { q: 'How many keys on a standard piano are black?', options: ['36', '40', '44', '52'], answer: 0, cat: 'music', diff: 3 },

  // Film & TV
  { q: 'What color is the cartoon character SpongeBob SquarePants?', options: ['Yellow', 'Pink', 'Blue', 'Green'], answer: 0, cat: 'film & tv', diff: 1 },
  { q: 'Which movie features the line "I\'ll be back"?', options: ['Rocky', 'The Terminator', 'Die Hard', 'Predator'], answer: 1, cat: 'film & tv', diff: 2 },
  { q: 'Who directed "Jurassic Park" (1993)?', options: ['James Cameron', 'Steven Spielberg', 'Ridley Scott', 'George Lucas'], answer: 1, cat: 'film & tv', diff: 2 },
  { q: 'What is the name of the cowboy doll in "Toy Story"?', options: ['Buzz', 'Jessie', 'Woody', 'Slinky'], answer: 2, cat: 'film & tv', diff: 1 },
  { q: 'In the 1939 film "The Wizard of Oz", what kind of slippers does Dorothy wear?', options: ['Silver slippers', 'Gold slippers', 'Glass slippers', 'Ruby slippers'], answer: 3, cat: 'film & tv', diff: 2 },
  { q: 'In "The Lion King", what is the name of Simba\'s father?', options: ['Mufasa', 'Scar', 'Rafiki', 'Zazu'], answer: 0, cat: 'film & tv', diff: 1 },
  { q: 'In which film series does the droid R2-D2 appear?', options: ['Star Trek', 'Star Wars', 'Blade Runner', 'Alien'], answer: 1, cat: 'film & tv', diff: 1 },
  { q: 'Which animated film follows a clownfish searching for his son?', options: ['Shark Tale', 'The Little Mermaid', 'Finding Nemo', 'Luca'], answer: 2, cat: 'film & tv', diff: 1 },
  { q: 'In "Frozen", what is the name of the snowman?', options: ['Sven', 'Kristoff', 'Hans', 'Olaf'], answer: 3, cat: 'film & tv', diff: 1 },
  { q: 'Who played Jack in "Titanic" (1997)?', options: ['Leonardo DiCaprio', 'Brad Pitt', 'Matt Damon', 'Johnny Depp'], answer: 0, cat: 'film & tv', diff: 2 },
  { q: 'Which film won the very first Academy Award for Best Picture?', options: ['Sunrise', 'The Jazz Singer', 'Wings', 'Metropolis'], answer: 2, cat: 'film & tv', diff: 3 },
  { q: 'In "E.T. the Extra-Terrestrial", which candy does Elliott use to lure E.T.?', options: ['M&M\'s', 'Reese\'s Pieces', 'Skittles', 'Jelly beans'], answer: 1, cat: 'film & tv', diff: 3 },
  { q: 'Which "Lord of the Rings" wizard is first known as "the Grey"?', options: ['Saruman', 'Radagast', 'Elrond', 'Gandalf'], answer: 3, cat: 'film & tv', diff: 1 },
  { q: 'Which cartoon family lives in Springfield and has a son named Bart?', options: ['The Simpsons', 'The Griffins', 'The Flintstones', 'The Jetsons'], answer: 0, cat: 'film & tv', diff: 1 },
  { q: 'In "Back to the Future", which car becomes a time machine?', options: ['Mustang', 'Corvette', 'DeLorean', 'Beetle'], answer: 2, cat: 'film & tv', diff: 2 },
  { q: 'What kind of animal is Scooby-Doo?', options: ['Cat', 'Dog', 'Horse', 'Fox'], answer: 1, cat: 'film & tv', diff: 1 },
  { q: 'In "Mary Poppins", a spoonful of sugar helps what go down?', options: ['The tea', 'The porridge', 'The cake', 'The medicine'], answer: 3, cat: 'film & tv', diff: 1 },
  { q: 'Which 1975 Steven Spielberg film is about a great white shark?', options: ['Jaws', 'Orca', 'The Deep', 'Piranha'], answer: 0, cat: 'film & tv', diff: 1 },
  { q: 'Which film hero is an archaeologist with a fedora and a whip?', options: ['Allan Quatermain', 'Indiana Jones', 'Lara Croft', 'Benjamin Gates'], answer: 1, cat: 'film & tv', diff: 1 },
  { q: 'In "Shrek", what kind of creature is Shrek?', options: ['Troll', 'Giant', 'Ogre', 'Goblin'], answer: 2, cat: 'film & tv', diff: 1 },
  { q: 'Which Pixar film takes place inside a girl\'s mind, with her emotions as characters?', options: ['Soul', 'Coco', 'Up', 'Inside Out'], answer: 3, cat: 'film & tv', diff: 1 },
  { q: 'In "Toy Story", what is the name of the boy who owns the toys?', options: ['Andy', 'Sid', 'Bonnie', 'Max'], answer: 0, cat: 'film & tv', diff: 2 },

  // Art & books
  { q: 'Which wizard school does Harry Potter attend?', options: ['Durmstrang', 'Beauxbatons', 'Hogwarts', 'Ilvermorny'], answer: 2, cat: 'art & books', diff: 1 },
  { q: 'Who painted the Mona Lisa?', options: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Botticelli'], answer: 1, cat: 'art & books', diff: 1 },
  { q: 'Who painted "The Starry Night"?', options: ['Claude Monet', 'Paul Cézanne', 'Pablo Picasso', 'Vincent van Gogh'], answer: 3, cat: 'art & books', diff: 1 },
  { q: 'Who painted the ceiling of the Sistine Chapel?', options: ['Michelangelo', 'Raphael', 'Donatello', 'Caravaggio'], answer: 0, cat: 'art & books', diff: 2 },
  { q: 'Salvador Dalí is best known for which art movement?', options: ['Cubism', 'Impressionism', 'Surrealism', 'Pop Art'], answer: 2, cat: 'art & books', diff: 2 },
  { q: 'Pablo Picasso co-founded which art movement?', options: ['Surrealism', 'Cubism', 'Fauvism', 'Baroque'], answer: 1, cat: 'art & books', diff: 3 },
  { q: 'Who wrote "Romeo and Juliet"?', options: ['Charles Dickens', 'Jane Austen', 'Geoffrey Chaucer', 'William Shakespeare'], answer: 3, cat: 'art & books', diff: 1 },
  { q: 'In which museum does the Mona Lisa hang?', options: ['The Louvre', 'The Prado', 'The Uffizi', 'The British Museum'], answer: 0, cat: 'art & books', diff: 2 },
  { q: 'Who wrote "Pride and Prejudice"?', options: ['Charlotte Brontë', 'Emily Brontë', 'Jane Austen', 'Mary Shelley'], answer: 2, cat: 'art & books', diff: 2 },
  { q: 'Which author created Sherlock Holmes?', options: ['Agatha Christie', 'Arthur Conan Doyle', 'Edgar Allan Poe', 'Charles Dickens'], answer: 1, cat: 'art & books', diff: 1 },
  { q: 'What are the three primary colors in traditional painting?', options: ['Red, green, blue', 'Cyan, magenta, yellow', 'Orange, green, purple', 'Red, yellow, blue'], answer: 3, cat: 'art & books', diff: 2 },
  { q: 'Who wrote "Alice\'s Adventures in Wonderland"?', options: ['Lewis Carroll', 'Roald Dahl', 'C. S. Lewis', 'J. M. Barrie'], answer: 0, cat: 'art & books', diff: 2 },
  { q: 'In "Charlie and the Chocolate Factory", who owns the factory?', options: ['Augustus Gloop', 'Mr. Bucket', 'Willy Wonka', 'Slugworth'], answer: 2, cat: 'art & books', diff: 1 },
  { q: 'Which Norwegian artist painted "The Scream"?', options: ['Gustav Klimt', 'Edvard Munch', 'Egon Schiele', 'Henri Matisse'], answer: 1, cat: 'art & books', diff: 2 },
  { q: 'Which J. M. Barrie character is the boy who never grows up?', options: ['Pinocchio', 'Oliver Twist', 'Tom Sawyer', 'Peter Pan'], answer: 3, cat: 'art & books', diff: 1 },
  { q: 'Who wrote "The Hobbit"?', options: ['J. R. R. Tolkien', 'C. S. Lewis', 'Roald Dahl', 'Philip Pullman'], answer: 0, cat: 'art & books', diff: 1 },
  { q: 'Claude Monet was a leading painter of which movement?', options: ['Cubism', 'Surrealism', 'Impressionism', 'Renaissance'], answer: 2, cat: 'art & books', diff: 2 },
  { q: 'Who wrote "Don Quixote"?', options: ['Dante Alighieri', 'Miguel de Cervantes', 'Victor Hugo', 'Gabriel García Márquez'], answer: 1, cat: 'art & books', diff: 3 },
  { q: 'In the novel "Moby-Dick", what is Moby Dick?', options: ['A shark', 'A ship', 'A sea captain', 'A white whale'], answer: 3, cat: 'art & books', diff: 2 },
  { q: 'Which children\'s author wrote "The Cat in the Hat"?', options: ['Dr. Seuss', 'Roald Dahl', 'Beatrix Potter', 'Maurice Sendak'], answer: 0, cat: 'art & books', diff: 1 },

  // Tech
  { q: 'What year did the first iPhone launch?', options: ['2005', '2006', '2007', '2008'], answer: 2, cat: 'tech', diff: 3 },
  { q: 'What does "CPU" stand for?', options: ['Computer Power Unit', 'Central Processing Unit', 'Core Program Utility', 'Central Program Unit'], answer: 1, cat: 'tech', diff: 2 },
  { q: 'What does "www" stand for in a web address?', options: ['World Wide Web', 'Wide Web World', 'Web World Wide', 'World Web Wire'], answer: 0, cat: 'tech', diff: 1 },
  { q: 'Who co-founded Microsoft with Paul Allen?', options: ['Steve Jobs', 'Steve Wozniak', 'Larry Page', 'Bill Gates'], answer: 3, cat: 'tech', diff: 1 },
  { q: 'How many bits are in a byte?', options: ['Four', 'Ten', 'Eight', 'Sixteen'], answer: 2, cat: 'tech', diff: 2 },
  { q: 'Who invented the World Wide Web?', options: ['Vint Cerf', 'Tim Berners-Lee', 'Alan Turing', 'Bill Gates'], answer: 1, cat: 'tech', diff: 2 },
  { q: 'What does "USB" stand for?', options: ['Universal Serial Bus', 'United System Board', 'Universal Signal Block', 'Unified Serial Bridge'], answer: 0, cat: 'tech', diff: 3 },
  { q: 'What is the standard English keyboard layout called?', options: ['AZERTY', 'Dvorak', 'Colemak', 'QWERTY'], answer: 3, cat: 'tech', diff: 1 },
  { q: 'Which British mathematician was a World War II codebreaker and a pioneer of computer science?', options: ['Charles Babbage', 'Isaac Newton', 'Alan Turing', 'John Napier'], answer: 2, cat: 'tech', diff: 2 },
  { q: 'Ada Lovelace wrote famous notes about which proposed machine?', options: ['Analytical Engine', 'ENIAC', 'Colossus', 'Enigma'], answer: 0, cat: 'tech', diff: 3 },
  { q: 'In computing, what does "RAM" stand for?', options: ['Read And Modify', 'Random Access Memory', 'Rapid Access Module', 'Run-time Allocated Memory'], answer: 1, cat: 'tech', diff: 2 },
  { q: 'What is the binary number 101 in decimal?', options: ['3', '6', '5', '10'], answer: 2, cat: 'tech', diff: 2 },
  { q: 'Which symbol separates the name from the domain in an email address?', options: ['#', '&', '%', '@'], answer: 3, cat: 'tech', diff: 1 },
  { q: 'Who received the first US patent for the telephone, in 1876?', options: ['Alexander Graham Bell', 'Thomas Edison', 'Nikola Tesla', 'Guglielmo Marconi'], answer: 0, cat: 'tech', diff: 1 },
  { q: 'What does "HTML" stand for?', options: ['High Tech Modern Language', 'HyperText Markup Language', 'Hyperlink Text Management Logic', 'Home Tool Markup Language'], answer: 1, cat: 'tech', diff: 2 },
  { q: 'Which company makes the PlayStation?', options: ['Nintendo', 'Microsoft', 'Sony', 'Sega'], answer: 2, cat: 'tech', diff: 1 },

  // Pop culture (games, comics, toys)
  { q: 'In chess, which piece can only move diagonally?', options: ['Rook', 'Knight', 'Bishop', 'Queen'], answer: 2, cat: 'pop culture', diff: 1 },
  { q: 'What is the name of Batman\'s home city?', options: ['Metropolis', 'Star City', 'Gotham', 'Central City'], answer: 2, cat: 'pop culture', diff: 1 },
  { q: 'Which video game franchise features Master Chief?', options: ['Doom', 'Halo', 'Destiny', 'Metro'], answer: 1, cat: 'pop culture', diff: 2 },
  { q: 'What is the name of Mario\'s brother in Nintendo games?', options: ['Wario', 'Toad', 'Yoshi', 'Luigi'], answer: 3, cat: 'pop culture', diff: 1 },
  { q: 'In Pac-Man, what do you eat to turn the ghosts blue?', options: ['Power pellets', 'Cherries', 'Keys', 'Stars'], answer: 0, cat: 'pop culture', diff: 2 },
  { q: 'Which falling-block puzzle game was created in the Soviet Union?', options: ['Columns', 'Tetris', 'Dr. Mario', 'Puyo Puyo'], answer: 1, cat: 'pop culture', diff: 2 },
  { q: 'How many squares are on a chessboard?', options: ['36', '49', '64', '81'], answer: 2, cat: 'pop culture', diff: 1 },
  { q: 'In classic Monopoly, what color are the two most expensive properties?', options: ['Green', 'Red', 'Yellow', 'Dark blue'], answer: 3, cat: 'pop culture', diff: 2 },
  { q: 'Which superhero is known as the Man of Steel?', options: ['Superman', 'Batman', 'Iron Man', 'Captain America'], answer: 0, cat: 'pop culture', diff: 1 },
  { q: 'What is the secret identity of the original Spider-Man?', options: ['Bruce Wayne', 'Peter Parker', 'Clark Kent', 'Tony Stark'], answer: 1, cat: 'pop culture', diff: 1 },
  { q: 'How many dots are on a standard six-sided die in total?', options: ['18', '24', '21', '36'], answer: 2, cat: 'pop culture', diff: 2 },
  { q: 'Which company made the Game Boy?', options: ['Sega', 'Sony', 'Atari', 'Nintendo'], answer: 3, cat: 'pop culture', diff: 1 },
  { q: 'In chess, which piece can jump over other pieces?', options: ['Knight', 'Bishop', 'Rook', 'Queen'], answer: 0, cat: 'pop culture', diff: 1 },
  { q: 'Which Pokémon is Ash\'s first partner in the anime?', options: ['Charmander', 'Pikachu', 'Bulbasaur', 'Squirtle'], answer: 1, cat: 'pop culture', diff: 1 },
  { q: 'Which princess does Mario most often rescue?', options: ['Zelda', 'Daisy', 'Peach', 'Rosalina'], answer: 2, cat: 'pop culture', diff: 1 },
  { q: 'In Minecraft, which green creature sneaks up and explodes?', options: ['Zombie', 'Enderman', 'Slime', 'Creeper'], answer: 3, cat: 'pop culture', diff: 1 },
  { q: 'Which word game is played on a 15×15 board of letter tiles?', options: ['Scrabble', 'Boggle', 'Bananagrams', 'Upwords'], answer: 0, cat: 'pop culture', diff: 2 },
  { q: 'What is the name of the hero in "The Legend of Zelda" games?', options: ['Zelda', 'Link', 'Ganon', 'Epona'], answer: 1, cat: 'pop culture', diff: 2 },
  { q: 'How many pieces does each player start with in checkers?', options: ['8', '10', '12', '16'], answer: 2, cat: 'pop culture', diff: 2 },

  // Wordplay
  { q: 'Which word is a synonym for "rapid"?', options: ['Sluggish', 'Swift', 'Sturdy', 'Shallow'], answer: 1, cat: 'wordplay', diff: 1 },
  { q: 'What do you call a group of lions?', options: ['Pack', 'Herd', 'Pride', 'Flock'], answer: 2, cat: 'wordplay', diff: 1 },
  { q: 'Which word means both "a written record" and "to make a note"?', options: ['Log', 'List', 'Ledger', 'Leaflet'], answer: 0, cat: 'wordplay', diff: 2 },
  { q: 'Complete the palindrome: "Was it a car or a cat I …?"', options: ['met', 'saw', 'hit', 'rode'], answer: 1, cat: 'wordplay', diff: 2 },
  { q: 'What is an eight-sided shape called?', options: ['Hexagon', 'Heptagon', 'Octagon', 'Nonagon'], answer: 2, cat: 'wordplay', diff: 1 },
  { q: 'Which word contains a silent "w"?', options: ['Wave', 'Wrist', 'Water', 'Widen'], answer: 1, cat: 'wordplay', diff: 2 },
  { q: 'The opposite of "benevolent" is…', options: ['Beneficial', 'Malevolent', 'Benevolence', 'Valiant'], answer: 1, cat: 'wordplay', diff: 2 },
  { q: 'What word describes a word spelled the same backwards?', options: ['Anagram', 'Palindrome', 'Homonym', 'Acronym'], answer: 1, cat: 'wordplay', diff: 1 },
  { q: 'Which word has three double letters in a row?', options: ['Bookkeeper', 'Typewriter', 'Keyboarding', 'Notepads'], answer: 0, cat: 'wordplay', diff: 3 },
  { q: '"Ephemeral" means…', options: ['Lasting forever', 'Extremely large', 'Short-lived', 'Deeply hidden'], answer: 2, cat: 'wordplay', diff: 3 },
  { q: 'What is the plural of "mouse" (the animal)?', options: ['Mouses', 'Meese', 'Mousen', 'Mice'], answer: 3, cat: 'wordplay', diff: 1 },
  { q: 'Which word is an anagram of "listen"?', options: ['Silent', 'Linens', 'Lentil', 'Stolen'], answer: 0, cat: 'wordplay', diff: 2 },
  { q: 'What is the opposite of "ancient"?', options: ['Antique', 'Aged', 'Modern', 'Classic'], answer: 2, cat: 'wordplay', diff: 1 },
  { q: 'A word that sounds like another but has a different meaning is a…', options: ['Synonym', 'Homophone', 'Antonym', 'Acronym'], answer: 1, cat: 'wordplay', diff: 2 },
  { q: 'What is a baby swan called?', options: ['Duckling', 'Gosling', 'Fledgling', 'Cygnet'], answer: 3, cat: 'wordplay', diff: 2 },
  { q: 'In the acronym "scuba", what does the "S" stand for?', options: ['Self-contained', 'Submarine', 'Surface', 'Swimming'], answer: 0, cat: 'wordplay', diff: 3 },
  { q: 'What is the word for a fear of spiders?', options: ['Acrophobia', 'Claustrophobia', 'Arachnophobia', 'Agoraphobia'], answer: 2, cat: 'wordplay', diff: 1 },
  { q: 'The prefix "bi-", as in "bicycle", means…', options: ['One', 'Two', 'Three', 'Many'], answer: 1, cat: 'wordplay', diff: 1 },
  { q: 'What do you call a scientist who studies stars and planets?', options: ['Astrologer', 'Astronaut', 'Asteroid', 'Astronomer'], answer: 3, cat: 'wordplay', diff: 2 },
  { q: 'Which is the correct spelling?', options: ['Accommodate', 'Accomodate', 'Acommodate', 'Acomodate'], answer: 0, cat: 'wordplay', diff: 2 },
  { q: 'What is the comparative form of "good"?', options: ['Gooder', 'Best', 'Better', 'More good'], answer: 2, cat: 'wordplay', diff: 1 },
  { q: 'A "nocturnal" animal is one that is…', options: ['Active at night', 'Living underground', 'Only eating plants', 'Asleep all winter'], answer: 0, cat: 'wordplay', diff: 1 },
  { q: 'The word "kindergarten" comes from which language?', options: ['Dutch', 'German', 'Swedish', 'Danish'], answer: 1, cat: 'wordplay', diff: 2 },
  { q: '"Bonjour" means "hello" in which language?', options: ['Spanish', 'Italian', 'Portuguese', 'French'], answer: 3, cat: 'wordplay', diff: 1 },
  { q: 'What does the Spanish word "gracias" mean?', options: ['Please', 'Hello', 'Thank you', 'Goodbye'], answer: 2, cat: 'wordplay', diff: 1 },
  { q: 'Which word is a synonym for "enormous"?', options: ['Tiny', 'Gigantic', 'Narrow', 'Fragile'], answer: 1, cat: 'wordplay', diff: 1 },
  { q: 'How many letters are in the English alphabet?', options: ['24', '25', '26', '28'], answer: 2, cat: 'wordplay', diff: 1 },
  { q: 'A word formed from initials, like "NASA", is called an…', options: ['Anagram', 'Antonym', 'Alliteration', 'Acronym'], answer: 3, cat: 'wordplay', diff: 2 },
  { q: 'Which punctuation mark shows possession, as in "the cat\'s toy"?', options: ['Apostrophe', 'Comma', 'Colon', 'Hyphen'], answer: 0, cat: 'wordplay', diff: 1 },
  { q: 'Which letter is used most often in written English?', options: ['A', 'E', 'I', 'T'], answer: 1, cat: 'wordplay', diff: 2 },
  { q: 'Which letter is silent at the start of "pneumonia"?', options: ['N', 'M', 'P', 'U'], answer: 2, cat: 'wordplay', diff: 2 },
  { q: 'Which word means "happening once every year"?', options: ['Biennial', 'Centennial', 'Millennial', 'Annual'], answer: 3, cat: 'wordplay', diff: 2 },
]

// Sanity guard so a bad edit can't ship a broken deck.
for (const item of TRIVIA_DECK) {
  if (!item.q || !Array.isArray(item.options) || item.options.length !== 4) {
    throw new Error('Bad trivia entry: need exactly 4 options')
  }
  if (!Number.isInteger(item.answer) || item.answer < 0 || item.answer > 3) {
    throw new Error('Bad trivia entry: answer must be 0-3')
  }
}
