// Spectrum pairs for WAVELENGTH. Each pair anchors the two ends of a 0–100 dial:
// `left` lives at 0, `right` lives at 100. The clue-giver sees a hidden target
// somewhere along it and gives a one-word clue; everyone else guesses where.
//
// Pairs must be clear opposites, and unique (wavelengthLogic.test.js checks).
//
// `clueBank` — used by solo/bot play: each entry is a real-world thing/concept a
// clue-giver would plausibly say (not a bare synonym of `left`/`right`) paired with
// where it actually sits on the dial (`pos`, 0–100). Every word must itself be a
// legal clue (one word, no digits, not a dial word — validateClue), because bots
// give these as clues and read them back when guessing.
export const WAVELENGTH_PAIRS = [
  { left: 'COLD', right: 'HOT', clueBank: [
    { word: 'ICEBERG', pos: 3 },
    { word: 'SNOWMAN', pos: 8 },
    { word: 'BATHWATER', pos: 62 },
    { word: 'SAUNA', pos: 88 },
  ] },
  { left: 'CHEAP', right: 'EXPENSIVE', clueBank: [
    { word: 'GUM', pos: 4 },
    { word: 'SANDWICH', pos: 20 },
    { word: 'SMARTPHONE', pos: 65 },
    { word: 'YACHT', pos: 97 },
  ] },
  { left: 'BORING', right: 'EXCITING', clueBank: [
    { word: 'PAPERWORK', pos: 5 },
    { word: 'GOLF', pos: 35 },
    { word: 'CONCERT', pos: 75 },
    { word: 'SKYDIVING', pos: 95 },
  ] },
  { left: 'QUIET', right: 'LOUD', clueBank: [
    { word: 'LIBRARY', pos: 4 },
    { word: 'WHISPER', pos: 10 },
    { word: 'TRAFFIC', pos: 70 },
    { word: 'FIREWORKS', pos: 95 },
  ] },
  { left: 'WEAK', right: 'STRONG', clueBank: [
    { word: 'KITTEN', pos: 8 },
    { word: 'TODDLER', pos: 18 },
    { word: 'GORILLA', pos: 85 },
    { word: 'BULLDOZER', pos: 95 },
  ] },
  { left: 'SMALL', right: 'HUGE', clueBank: [
    { word: 'ANT', pos: 2 },
    { word: 'MOUSE', pos: 10 },
    { word: 'ELEPHANT', pos: 80 },
    { word: 'MOUNTAIN', pos: 96 },
  ] },
  { left: 'SLOW', right: 'FAST', clueBank: [
    { word: 'SNAIL', pos: 3 },
    { word: 'TORTOISE', pos: 8 },
    { word: 'BICYCLE', pos: 45 },
    { word: 'CHEETAH', pos: 92 },
  ] },
  { left: 'UGLY', right: 'BEAUTIFUL', clueBank: [
    { word: 'GARGOYLE', pos: 10 },
    { word: 'POTATO', pos: 35 },
    { word: 'RAINBOW', pos: 88 },
    { word: 'SUNSET', pos: 92 },
  ] },
  { left: 'EVIL', right: 'GOOD', clueBank: [
    { word: 'VILLAIN', pos: 5 },
    { word: 'PIRATE', pos: 30 },
    { word: 'LIBRARIAN', pos: 72 },
    { word: 'SAINT', pos: 97 },
  ] },
  { left: 'SAD', right: 'HAPPY', clueBank: [
    { word: 'FUNERAL', pos: 3 },
    { word: 'MONDAY', pos: 30 },
    { word: 'WEEKEND', pos: 75 },
    { word: 'BIRTHDAY', pos: 88 },
  ] },
  { left: 'OLD', right: 'NEW', clueBank: [
    { word: 'PYRAMID', pos: 3 },
    { word: 'VINYL', pos: 30 },
    { word: 'SMARTPHONE', pos: 85 },
    { word: 'BABY', pos: 95 },
  ] },
  { left: 'DARK', right: 'BRIGHT', clueBank: [
    { word: 'CAVE', pos: 3 },
    { word: 'MOONLIGHT', pos: 25 },
    { word: 'CANDLE', pos: 40 },
    { word: 'SUN', pos: 98 },
  ] },
  { left: 'COMMON', right: 'RARE', clueBank: [
    { word: 'PIGEON', pos: 5 },
    { word: 'PENNY', pos: 8 },
    { word: 'DIAMOND', pos: 80 },
    { word: 'UNICORN', pos: 99 },
  ] },
  { left: 'SOFT', right: 'HARD', clueBank: [
    { word: 'MARSHMALLOW', pos: 3 },
    { word: 'PILLOW', pos: 5 },
    { word: 'BREAD', pos: 25 },
    { word: 'DIAMOND', pos: 98 },
  ] },
  { left: 'USELESS', right: 'USEFUL', clueBank: [
    { word: 'RECEIPT', pos: 15 },
    { word: 'TROPHY', pos: 35 },
    { word: 'SCISSORS', pos: 85 },
    { word: 'PHONE', pos: 92 },
  ] },
  { left: 'SIMPLE', right: 'COMPLEX', clueBank: [
    { word: 'SPOON', pos: 5 },
    { word: 'BICYCLE', pos: 40 },
    { word: 'CHESS', pos: 75 },
    { word: 'BRAIN', pos: 97 },
  ] },
  { left: 'SAFE', right: 'DANGEROUS', clueBank: [
    { word: 'BLANKET', pos: 5 },
    { word: 'LADDER', pos: 45 },
    { word: 'MOTORCYCLE', pos: 75 },
    { word: 'VOLCANO', pos: 95 },
  ] },
  { left: 'CASUAL', right: 'FORMAL', clueBank: [
    { word: 'PAJAMAS', pos: 3 },
    { word: 'JEANS', pos: 20 },
    { word: 'BLAZER', pos: 70 },
    { word: 'TUXEDO', pos: 95 },
  ] },
  { left: 'EMPTY', right: 'FULL', clueBank: [
    { word: 'VACUUM', pos: 3 },
    { word: 'DESERT', pos: 15 },
    { word: 'SUBWAY', pos: 80 },
    { word: 'STADIUM', pos: 90 },
  ] },
  { left: 'DIRTY', right: 'CLEAN', clueBank: [
    { word: 'SWAMP', pos: 3 },
    { word: 'SOCKS', pos: 20 },
    { word: 'KITCHEN', pos: 50 },
    { word: 'HOSPITAL', pos: 90 },
  ] },
  { left: 'TEMPORARY', right: 'PERMANENT', clueBank: [
    { word: 'SNOWFLAKE', pos: 3 },
    { word: 'HAIRCUT', pos: 30 },
    { word: 'TATTOO', pos: 90 },
    { word: 'PYRAMID', pos: 96 },
  ] },
  { left: 'UNDERRATED', right: 'OVERRATED', clueBank: [
    { word: 'SLEEP', pos: 10 },
    { word: 'TEA', pos: 30 },
    { word: 'BRUNCH', pos: 80 },
    { word: 'SELFIES', pos: 90 },
  ] },
  { left: 'GUILTY PLEASURE', right: 'OPENLY LOVED', clueBank: [
    { word: 'GOSSIP', pos: 10 },
    { word: 'KARAOKE', pos: 35 },
    { word: 'PIZZA', pos: 85 },
    { word: 'PUPPIES', pos: 97 },
  ] },
  { left: 'FORGETTABLE', right: 'ICONIC', clueBank: [
    { word: 'STAPLER', pos: 10 },
    { word: 'TOAST', pos: 25 },
    { word: 'MOONWALK', pos: 90 },
    { word: 'EIFFEL', pos: 95 },
  ] },
  { left: 'INTROVERT', right: 'EXTROVERT', clueBank: [
    { word: 'HERMIT', pos: 3 },
    { word: 'BOOKWORM', pos: 12 },
    { word: 'COMEDIAN', pos: 80 },
    { word: 'CHEERLEADER', pos: 90 },
  ] },
  { left: 'SOUR', right: 'SWEET', clueBank: [
    { word: 'LEMON', pos: 3 },
    { word: 'GRAPEFRUIT', pos: 30 },
    { word: 'APPLE', pos: 60 },
    { word: 'CANDY', pos: 97 },
  ] },
  { left: 'MESSY', right: 'TIDY', clueBank: [
    { word: 'TORNADO', pos: 2 },
    { word: 'TEENAGER', pos: 15 },
    { word: 'LIBRARY', pos: 80 },
    { word: 'MUSEUM', pos: 90 },
  ] },
  { left: 'LAZY', right: 'HARD-WORKING', clueBank: [
    { word: 'SLOTH', pos: 3 },
    { word: 'CAT', pos: 15 },
    { word: 'BEAVER', pos: 88 },
    { word: 'ANT', pos: 92 },
  ] },
  { left: 'SERIOUS', right: 'SILLY', clueBank: [
    { word: 'FUNERAL', pos: 3 },
    { word: 'COURTROOM', pos: 5 },
    { word: 'PICNIC', pos: 60 },
    { word: 'CLOWN', pos: 97 },
  ] },
  { left: 'FICTION', right: 'NON-FICTION', clueBank: [
    { word: 'UNICORN', pos: 2 },
    { word: 'LEGEND', pos: 25 },
    { word: 'MEMOIR', pos: 85 },
    { word: 'DICTIONARY', pos: 99 },
  ] },
  { left: 'BASIC', right: 'FANCY', clueBank: [
    { word: 'TOAST', pos: 8 },
    { word: 'SANDWICH', pos: 25 },
    { word: 'SUSHI', pos: 70 },
    { word: 'CAVIAR', pos: 97 },
  ] },
  { left: 'LOW TECH', right: 'HIGH TECH', clueBank: [
    { word: 'PENCIL', pos: 3 },
    { word: 'ABACUS', pos: 5 },
    { word: 'TYPEWRITER', pos: 35 },
    { word: 'ROBOT', pos: 93 },
  ] },
  { left: 'DRY', right: 'WET', clueBank: [
    { word: 'DESERT', pos: 3 },
    { word: 'CRACKER', pos: 10 },
    { word: 'SPONGE', pos: 70 },
    { word: 'OCEAN', pos: 99 },
  ] },
  { left: 'LIGHT', right: 'HEAVY', clueBank: [
    { word: 'FEATHER', pos: 2 },
    { word: 'BALLOON', pos: 3 },
    { word: 'BRICK', pos: 70 },
    { word: 'ANVIL', pos: 95 },
  ] },
  { left: 'SHORT', right: 'TALL', clueBank: [
    { word: 'MOUSE', pos: 3 },
    { word: 'TODDLER', pos: 15 },
    { word: 'GIRAFFE', pos: 90 },
    { word: 'SKYSCRAPER', pos: 98 },
  ] },
  { left: 'NARROW', right: 'WIDE', clueBank: [
    { word: 'NEEDLE', pos: 3 },
    { word: 'HALLWAY', pos: 20 },
    { word: 'HIGHWAY', pos: 70 },
    { word: 'OCEAN', pos: 97 },
  ] },
  { left: 'SHALLOW', right: 'DEEP', clueBank: [
    { word: 'PUDDLE', pos: 3 },
    { word: 'BATHTUB', pos: 12 },
    { word: 'WELL', pos: 70 },
    { word: 'TRENCH', pos: 99 },
  ] },
  { left: 'SMOOTH', right: 'ROUGH', clueBank: [
    { word: 'SILK', pos: 3 },
    { word: 'GLASS', pos: 5 },
    { word: 'BARK', pos: 80 },
    { word: 'SANDPAPER', pos: 95 },
  ] },
  { left: 'BLUNT', right: 'SHARP', clueBank: [
    { word: 'SPOON', pos: 5 },
    { word: 'CRAYON', pos: 15 },
    { word: 'SCISSORS', pos: 70 },
    { word: 'RAZOR', pos: 97 },
  ] },
  { left: 'MILD', right: 'SPICY', clueBank: [
    { word: 'RICE', pos: 3 },
    { word: 'KETCHUP', pos: 10 },
    { word: 'SALSA', pos: 60 },
    { word: 'HABANERO', pos: 97 },
  ] },
  { left: 'HEALTHY FOOD', right: 'JUNK FOOD', clueBank: [
    { word: 'BROCCOLI', pos: 3 },
    { word: 'SALAD', pos: 8 },
    { word: 'PIZZA', pos: 75 },
    { word: 'DONUT', pos: 92 },
  ] },
  { left: 'CALM', right: 'CHAOTIC', clueBank: [
    { word: 'MEDITATION', pos: 3 },
    { word: 'LIBRARY', pos: 10 },
    { word: 'AIRPORT', pos: 70 },
    { word: 'BATTLEFIELD', pos: 97 },
  ] },
  { left: 'CUTE', right: 'SCARY', clueBank: [
    { word: 'PUPPY', pos: 3 },
    { word: 'KOALA', pos: 8 },
    { word: 'CLOWN', pos: 60 },
    { word: 'ZOMBIE', pos: 95 },
  ] },
  { left: 'NATURAL', right: 'ARTIFICIAL', clueBank: [
    { word: 'FOREST', pos: 3 },
    { word: 'HONEY', pos: 10 },
    { word: 'CHEESE', pos: 40 },
    { word: 'PLASTIC', pos: 92 },
  ] },
  { left: 'RURAL', right: 'URBAN', clueBank: [
    { word: 'FARM', pos: 3 },
    { word: 'VILLAGE', pos: 20 },
    { word: 'SUBURB', pos: 55 },
    { word: 'SKYSCRAPER', pos: 95 },
  ] },
  { left: 'GROSS', right: 'DELICIOUS', clueBank: [
    { word: 'MOLD', pos: 2 },
    { word: 'SLIME', pos: 5 },
    { word: 'CEREAL', pos: 60 },
    { word: 'CHOCOLATE', pos: 92 },
  ] },
  { left: 'PAST', right: 'FUTURE', clueBank: [
    { word: 'DINOSAUR', pos: 2 },
    { word: 'KNIGHT', pos: 15 },
    { word: 'TELEGRAM', pos: 35 },
    { word: 'HOVERBOARD', pos: 88 },
  ] },
  { left: 'SOLID', right: 'LIQUID', clueBank: [
    { word: 'ROCK', pos: 2 },
    { word: 'CHEESE', pos: 20 },
    { word: 'JELLY', pos: 50 },
    { word: 'WATER', pos: 98 },
  ] },
  { left: 'TIMID', right: 'BRAVE', clueBank: [
    { word: 'MOUSE', pos: 5 },
    { word: 'RABBIT', pos: 10 },
    { word: 'FIREFIGHTER', pos: 88 },
    { word: 'LION', pos: 90 },
  ] },
  { left: 'RELAXING', right: 'STRESSFUL', clueBank: [
    { word: 'HAMMOCK', pos: 3 },
    { word: 'BATH', pos: 8 },
    { word: 'WEDDING', pos: 65 },
    { word: 'DEADLINE', pos: 92 },
  ] },
  { left: 'EASY', right: 'DIFFICULT', clueBank: [
    { word: 'BREATHING', pos: 2 },
    { word: 'ORIGAMI', pos: 55 },
    { word: 'CALCULUS', pos: 90 },
    { word: 'SURGERY', pos: 95 },
  ] },
  { left: 'SECRET', right: 'PUBLIC', clueBank: [
    { word: 'DIARY', pos: 3 },
    { word: 'PASSWORD', pos: 5 },
    { word: 'GOSSIP', pos: 45 },
    { word: 'BILLBOARD', pos: 95 },
  ] },
  { left: 'HARMLESS', right: 'DEADLY', clueBank: [
    { word: 'BUTTERFLY', pos: 3 },
    { word: 'HAMSTER', pos: 5 },
    { word: 'BEE', pos: 40 },
    { word: 'COBRA', pos: 92 },
  ] },
  { left: 'SWEET-SMELLING', right: 'STINKY', clueBank: [
    { word: 'ROSE', pos: 3 },
    { word: 'PERFUME', pos: 5 },
    { word: 'SOCKS', pos: 80 },
    { word: 'SKUNK', pos: 97 },
  ] },
  { left: 'BAD HABIT', right: 'GOOD HABIT', clueBank: [
    { word: 'SMOKING', pos: 3 },
    { word: 'NAILBITING', pos: 10 },
    { word: 'SNACKING', pos: 40 },
    { word: 'FLOSSING', pos: 92 },
  ] },
  { left: 'ROUND', right: 'POINTY', clueBank: [
    { word: 'BALL', pos: 2 },
    { word: 'APPLE', pos: 8 },
    { word: 'PEAR', pos: 30 },
    { word: 'NEEDLE', pos: 98 },
  ] },
  { left: 'TRADITIONAL', right: 'TRENDY', clueBank: [
    { word: 'QUILT', pos: 5 },
    { word: 'KNITTING', pos: 10 },
    { word: 'PODCAST', pos: 80 },
    { word: 'SELFIE', pos: 90 },
  ] },
  { left: 'DULL', right: 'SHINY', clueBank: [
    { word: 'CARDBOARD', pos: 5 },
    { word: 'CONCRETE', pos: 8 },
    { word: 'COIN', pos: 75 },
    { word: 'MIRROR', pos: 95 },
  ] },
  { left: 'INDOOR', right: 'OUTDOOR', clueBank: [
    { word: 'BOWLING', pos: 5 },
    { word: 'CHESS', pos: 8 },
    { word: 'TENNIS', pos: 60 },
    { word: 'CAMPING', pos: 97 },
  ] },
  { left: 'SUMMER', right: 'WINTER', clueBank: [
    { word: 'BEACH', pos: 3 },
    { word: 'LEMONADE', pos: 8 },
    { word: 'PUMPKIN', pos: 60 },
    { word: 'MITTENS', pos: 95 },
  ] },
  { left: 'MORNING', right: 'NIGHT', clueBank: [
    { word: 'SUNRISE', pos: 3 },
    { word: 'BREAKFAST', pos: 8 },
    { word: 'LUNCH', pos: 45 },
    { word: 'MOON', pos: 97 },
  ] },
  { left: 'CHILDISH', right: 'MATURE', clueBank: [
    { word: 'TANTRUM', pos: 3 },
    { word: 'CARTOON', pos: 15 },
    { word: 'CROSSWORD', pos: 70 },
    { word: 'MORTGAGE', pos: 95 },
  ] },
  { left: 'FRAGILE', right: 'STURDY', clueBank: [
    { word: 'SNOWFLAKE', pos: 2 },
    { word: 'EGGSHELL', pos: 3 },
    { word: 'TABLE', pos: 70 },
    { word: 'ANVIL', pos: 97 },
  ] },
  { left: 'SLIPPERY', right: 'STICKY', clueBank: [
    { word: 'ICE', pos: 3 },
    { word: 'SOAP', pos: 5 },
    { word: 'HONEY', pos: 88 },
    { word: 'GLUE', pos: 97 },
  ] },
  { left: 'ORDINARY', right: 'WEIRD', clueBank: [
    { word: 'SPOON', pos: 3 },
    { word: 'TOAST', pos: 5 },
    { word: 'UNICYCLE', pos: 70 },
    { word: 'PLATYPUS', pos: 88 },
  ] },
  { left: 'UNKNOWN', right: 'FAMOUS', clueBank: [
    { word: 'STRANGER', pos: 3 },
    { word: 'NEIGHBOR', pos: 20 },
    { word: 'MAYOR', pos: 50 },
    { word: 'POPSTAR', pos: 92 },
  ] },
  { left: 'FLEXIBLE', right: 'RIGID', clueBank: [
    { word: 'GYMNAST', pos: 3 },
    { word: 'RUBBER', pos: 5 },
    { word: 'PENCIL', pos: 80 },
    { word: 'STEEL', pos: 95 },
  ] },
]
