// Spectrum pairs for WAVELENGTH. Each pair anchors the two ends of a 0–100 dial:
// `left` lives at 0, `right` lives at 100. The clue-giver picks a hidden target
// somewhere along it and gives a one-word clue; everyone else guesses where.
export const WAVELENGTH_PAIRS = [
  { left: 'COLD', right: 'HOT' },
  { left: 'CHEAP', right: 'EXPENSIVE' },
  { left: 'BORING', right: 'EXCITING' },
  { left: 'QUIET', right: 'LOUD' },
  { left: 'WEAK', right: 'STRONG' },
  { left: 'SMALL', right: 'HUGE' },
  { left: 'SLOW', right: 'FAST' },
  { left: 'UGLY', right: 'BEAUTIFUL' },
  { left: 'EVIL', right: 'GOOD' },
  { left: 'SAD', right: 'HAPPY' },
  { left: 'OLD', right: 'NEW' },
  { left: 'DARK', right: 'BRIGHT' },
  { left: 'COMMON', right: 'RARE' },
  { left: 'SOFT', right: 'HARD' },
  { left: 'USELESS', right: 'USEFUL' },
  { left: 'SIMPLE', right: 'COMPLEX' },
  { left: 'SAFE', right: 'DANGEROUS' },
  { left: 'CASUAL', right: 'FORMAL' },
  { left: 'EMPTY', right: 'FULL' },
  { left: 'DIRTY', right: 'CLEAN' },
  { left: 'TEMPORARY', right: 'PERMANENT' },
  { left: 'UNDERRATED', right: 'OVERRATED' },
  { left: 'GUILTY PLEASURE', right: 'OPENLY LOVED' },
  { left: 'FORGETTABLE', right: 'ICONIC' },
  { left: 'INTROVERT', right: 'EXTROVERT' },
  { left: 'SOUR', right: 'SWEET' },
  { left: 'MESSY', right: 'TIDY' },
  { left: 'LAZY', right: 'HARD-WORKING' },
  { left: 'SERIOUS', right: 'SILLY' },
  { left: 'FICTION', right: 'NON-FICTION' },
  { left: 'BASIC', right: 'FANCY' },
  { left: 'LOW TECH', right: 'HIGH TECH' },
]
