// Game art — two routes, full catalog (Option A PNG default, Option B soft
// SVG via Settings → LOOK & FEEL → GAME ART). Variants + same-family games
// resolve through ART_ALIAS (mirrors the icon fallback); <GameArt/> returns
// null for unknown types so callers need no per-game branches.
//
// Option A: static PNGs in public/game-art/ (256×256, fixed bright palette,
// generated by scripts/make-game-art.mjs — `npm run art`). Punchy, identical
// in every theme, ~3 KB each.
// Option B: soft theme-aware SVGs below. Theming rule: NO hex in src/ — only
// semantic fill-retro-*/stroke-retro-* tokens, tint washes, thin strokes.
import { useGameArtStyle } from '../lib/gameArtStyle'

const ART_TYPES = new Set([
  'tictactoe', 'sim', 'chomp', 'breakthrough', 'ataxx', 'kamisado', 'onitama', 'quarto',
  'santorini', 'loa', 'yavalath', 'connectfour', 'hangwoman', 'dotsandboxes', 'sos',
  'simon', 'chimp', 'numbermemory', 'reaction', 'aim', 'typing', 'math', 'arrows', 'updraft',
  'pong', 'snake', 'tron', 'sumo', 'spaceduel', 'paint', 'pacmac', 'visualmemory', 'gomoku',
  'reversi', 'chainreaction', 'blockade', 'orderchaos', 'dice', 'hex', 'minesweeper', 'herd',
  'trivia', 'battleship', 'mancala', 'checkers', 'airhockey', 'artillery', 'animalstack',
  'wirecrossed', 'twotruths', 'bluff', 'lanterns', 'docking', 'wavelength', 'fibbage',
  'spyfair', 'headsup', 'chameleon', 'wordduel', 'wordcoop', 'converge', 'wordrace',
  'wordhunt', 'password', 'anagrams', 'hunch', 'pairs', 'sketch', 'codewords', 'justone',
])

const ART_ALIAS = { chainreaction4: 'chainreaction' }

const resolveArt = (type) => ART_ALIAS[type] || type

export function GameArtImg({ type, className }) {
  const t = resolveArt(type)
  if (!ART_TYPES.has(t)) return null
  return (
    <img
      src={`/game-art/${t}.png`}
      alt=""
      aria-hidden="true"
      draggable={false}
      loading="lazy"
      className={className}
    />
  )
}

function TttSoft({ className }) {
  const xs = [29, 48, 67]
  return (
    <svg viewBox="0 0 96 96" className={className} role="img" aria-label="Tic tac toe art">
      <rect x="0" y="0" width="96" height="96" className="fill-retro-card" />
      {/* soft wash behind the winning row */}
      <rect x="14" y="19" width="68" height="19" rx="9.5" className="fill-retro-tint-cta" />
      <g className="stroke-retro-dim" strokeWidth="2.5" strokeLinecap="round">
        <line x1="38" y1="20" x2="38" y2="76" />
        <line x1="58" y1="20" x2="58" y2="76" />
        <line x1="20" y1="38" x2="76" y2="38" />
        <line x1="20" y1="58" x2="76" y2="58" />
      </g>
      <g className="stroke-retro-p1" strokeWidth="4" strokeLinecap="round">
        {xs.map(cx => (
          <g key={cx}>
            <line x1={cx - 5} y1="24" x2={cx + 5} y2="34" />
            <line x1={cx + 5} y1="24" x2={cx - 5} y2="34" />
          </g>
        ))}
      </g>
      <g fill="none" className="stroke-retro-p2" strokeWidth="4">
        <circle cx="29" cy="67" r="6" />
        <circle cx="67" cy="67" r="6" />
      </g>
    </svg>
  )
}

function ConnectFourSoft({ className }) {
  const xs = [28, 42, 56, 70]
  const ys = [40, 54, 68]
  const connected = new Set(['0,2', '1,2', '2,2', '3,2'])
  const soft = new Set(['1,1', '3,1', '2,0'])
  return (
    <svg viewBox="0 0 96 96" className={className} role="img" aria-label="Connect four art">
      <rect x="0" y="0" width="96" height="96" className="fill-retro-card" />
      <rect x="16" y="28" width="64" height="48" rx="12" className="fill-retro-tint-p1" />
      {ys.map((y, r) =>
        xs.map((x, c) => {
          const k = `${c},${r}`
          if (connected.has(k)) {
            return <circle key={k} cx={x} cy={y} r="6" className="fill-retro-cta" />
          }
          if (soft.has(k)) {
            return <circle key={k} cx={x} cy={y} r="6" className="fill-retro-p2" opacity="0.55" />
          }
          return <circle key={k} cx={x} cy={y} r="6" className="fill-retro-card" opacity="0.85" />
        }),
      )}
      <circle cx="60" cy="16" r="5" className="fill-retro-cta" opacity="0.6" />
    </svg>
  )
}

function PongSoft({ className }) {
  return (
    <svg viewBox="0 0 96 96" className={className} role="img" aria-label="Pong art">
      <rect x="0" y="0" width="96" height="96" className="fill-retro-card" />
      <rect x="14" y="28" width="68" height="40" rx="10"
        className="fill-retro-card stroke-retro-border" strokeWidth="2" />
      <line x1="48" y1="33" x2="48" y2="63" className="stroke-retro-dim"
        strokeWidth="2" strokeDasharray="3 4" strokeLinecap="round" />
      <rect x="20" y="40" width="4.5" height="16" rx="2.25" className="fill-retro-p1" />
      <rect x="71.5" y="40" width="4.5" height="16" rx="2.25" className="fill-retro-p2" />
      <circle cx="58" cy="48" r="8" className="fill-retro-cta" opacity="0.2" />
      <circle cx="58" cy="48" r="4" className="fill-retro-cta" />
    </svg>
  )
}

const SOFT_COMP = {
  tictactoe: TttSoft,
  connectfour: ConnectFourSoft,
  pong: PongSoft,
}

// Fragment helpers for the rest of the catalog (module-private).
const BG = (c) => <rect x="0" y="0" width="96" height="96" className={c} />
const DT = (x, y, r, c, o = 1) => <circle cx={x} cy={y} r={r} className={c} opacity={o} />
const BX = (x, y, w, h, r, c, o = 1) => <rect x={x} y={y} width={w} height={h} rx={r} className={c} opacity={o} />
const LN = (x1, y1, x2, y2, c, w = 3, dash) => (
  <line x1={x1} y1={y1} x2={x2} y2={y2} className={c} strokeWidth={w}
    strokeLinecap="round" {...(dash ? { strokeDasharray: dash } : {})} />
)
const PG = (points, c) => <polygon points={points} className={c} />

const SOFT_FRAG = {
  sim: (<>
    {BG('fill-retro-tint-p2')}
    {LN(48, 24, 30, 66, 'stroke-retro-dim', 3)}
    {LN(30, 66, 66, 66, 'stroke-retro-dim', 3)}
    {LN(66, 66, 48, 24, 'stroke-retro-p1', 3.5)}
    {DT(48, 24, 4, 'fill-retro-p2')}{DT(30, 66, 4, 'fill-retro-p2')}{DT(66, 66, 4, 'fill-retro-p2')}
  </>),
  chomp: (<>
    {BG('fill-retro-tint-cta')}
    {BX(24, 32, 12, 12, 2.5, 'fill-retro-card')}{BX(39, 32, 12, 12, 2.5, 'fill-retro-card')}
    {BX(54, 32, 12, 12, 2.5, 'fill-retro-card')}{BX(69, 32, 12, 12, 2.5, 'fill-retro-card')}
    {BX(24, 47, 12, 12, 2.5, 'fill-retro-card')}{BX(39, 47, 12, 12, 2.5, 'fill-retro-card')}
    {BX(54, 47, 12, 12, 2.5, 'fill-retro-card')}{BX(24, 62, 12, 12, 2.5, 'fill-retro-card')}
    {DT(30, 38, 4, 'fill-retro-p1')}
  </>),
  breakthrough: (<>
    {BG('fill-retro-tint-p1')}
    {LN(34, 16, 62, 16, 'stroke-retro-win', 4)}
    {LN(48, 24, 48, 62, 'stroke-retro-dim', 2.5, '4 4')}
    {DT(60, 32, 6, 'fill-retro-p2', 0.7)}{DT(48, 62, 8, 'fill-retro-p1')}{DT(48, 44, 8, 'fill-retro-p1')}
  </>),
  ataxx: (<>
    {BG('fill-retro-tint-p2')}
    {DT(32, 52, 11, 'fill-retro-p1')}{DT(59, 42, 7, 'fill-retro-p1')}{DT(61, 63, 7, 'fill-retro-p1')}
    {DT(75, 52, 7, 'fill-retro-p2', 0.8)}
  </>),
  kamisado: (<>
    {BG('fill-retro-card')}
    {BX(24, 38, 10, 26, 2.5, 'fill-retro-p1', 0.55)}{BX(38, 38, 10, 26, 2.5, 'fill-retro-p2', 0.55)}
    {BX(52, 36, 10, 28, 2.5, 'fill-retro-cta')}{BX(66, 38, 10, 26, 2.5, 'fill-retro-win', 0.55)}
  </>),
  onitama: (<>
    {BG('fill-retro-tint-p1')}
    {BX(16, 20, 28, 20, 4, 'fill-retro-card')}{BX(52, 20, 28, 20, 4, 'fill-retro-card')}
    {DT(30, 30, 3.5, 'fill-retro-p1')}{DT(66, 30, 3.5, 'fill-retro-p2')}
    {DT(32, 62, 8, 'fill-retro-p1')}
  </>),
  quarto: (<>
    {BG('fill-retro-card')}
    {BX(26, 18, 9, 24, 2, 'fill-retro-p1', 0.85)}{BX(42, 28, 9, 14, 2, 'fill-retro-p2', 0.85)}
    {DT(60, 30, 7, 'fill-retro-cta', 0.85)}{BX(70, 28, 10, 10, 2, 'fill-retro-win', 0.85)}
    {DT(48, 60, 7, 'fill-retro-cta')}
  </>),
  santorini: (<>
    {BG('fill-retro-tint-p1')}
    {BX(28, 62, 40, 11, 2, 'fill-retro-card')}{BX(34, 52, 28, 10, 2, 'fill-retro-card')}
    {BX(40, 42, 16, 10, 2, 'fill-retro-card')}{DT(48, 36, 6, 'fill-retro-p2')}{DT(36, 47, 4, 'fill-retro-p1')}
  </>),
  loa: (<>
    {BG('fill-retro-tint-p2')}
    {LN(24, 68, 40, 52, 'stroke-retro-dim', 3)}{LN(40, 52, 56, 52, 'stroke-retro-dim', 3)}{LN(56, 52, 72, 36, 'stroke-retro-dim', 3)}
    {DT(24, 68, 6, 'fill-retro-p1')}{DT(40, 52, 6, 'fill-retro-p1')}{DT(56, 52, 6, 'fill-retro-p1')}{DT(72, 36, 6, 'fill-retro-p1')}
  </>),
  yavalath: (<>
    {BG('fill-retro-card')}
    {DT(24, 40, 6, 'fill-retro-cta')}{DT(38, 40, 6, 'fill-retro-cta')}{DT(52, 40, 6, 'fill-retro-cta')}{DT(66, 40, 6, 'fill-retro-cta')}
    {DT(30, 62, 5, 'fill-retro-p2', 0.55)}{DT(44, 62, 5, 'fill-retro-p2', 0.55)}{DT(66, 62, 5, 'fill-retro-p2', 0.55)}
  </>),
  hangwoman: (<>
    {BG('fill-retro-card')}
    {LN(28, 78, 28, 20, 'stroke-retro-text', 3.5)}{LN(28, 20, 58, 20, 'stroke-retro-text', 3.5)}{LN(58, 20, 58, 30, 'stroke-retro-text', 3)}
    {DT(58, 37, 7, 'fill-retro-win')}
    {BX(24, 66, 10, 3.5, 1.5, 'fill-retro-dim')}{BX(38, 66, 10, 3.5, 1.5, 'fill-retro-dim')}{BX(52, 66, 10, 3.5, 1.5, 'fill-retro-dim')}
  </>),
  dotsandboxes: (<>
    {BG('fill-retro-card')}
    {BX(32, 40, 32, 18, 2, 'fill-retro-tint-cta')}
    {DT(30, 38, 2.5, 'fill-retro-text')}{DT(48, 38, 2.5, 'fill-retro-text')}{DT(66, 38, 2.5, 'fill-retro-text')}
    {DT(30, 49, 2.5, 'fill-retro-text')}{DT(48, 49, 2.5, 'fill-retro-text')}{DT(66, 49, 2.5, 'fill-retro-text')}
    {DT(30, 60, 2.5, 'fill-retro-text')}{DT(48, 60, 2.5, 'fill-retro-text')}{DT(66, 60, 2.5, 'fill-retro-text')}
  </>),
  sos: (<>
    {BG('fill-retro-tint-p2')}
    {BX(20, 22, 18, 18, 4, 'fill-retro-card')}{BX(39, 39, 18, 18, 4, 'fill-retro-card')}{BX(58, 56, 18, 18, 4, 'fill-retro-card')}
    {LN(34, 27, 26, 27, 'stroke-retro-text', 2.5)}{LN(26, 27, 26, 31, 'stroke-retro-text', 2.5)}{LN(26, 31, 34, 31, 'stroke-retro-text', 2.5)}{LN(34, 31, 34, 35, 'stroke-retro-text', 2.5)}
    {DT(48, 48, 5, 'fill-none stroke-retro-p2')}
    {LN(72, 61, 64, 61, 'stroke-retro-text', 2.5)}{LN(64, 61, 64, 65, 'stroke-retro-text', 2.5)}{LN(64, 65, 72, 65, 'stroke-retro-text', 2.5)}{LN(72, 65, 72, 69, 'stroke-retro-text', 2.5)}
  </>),
  simon: (<>
    {BG('fill-retro-card')}
    {BX(22, 22, 24, 24, 6, 'fill-retro-p1', 0.85)}{BX(50, 22, 24, 24, 6, 'fill-retro-p2', 0.55)}
    {BX(22, 50, 24, 24, 6, 'fill-retro-win', 0.55)}{BX(50, 50, 24, 24, 6, 'fill-retro-cta', 0.85)}
  </>),
  chimp: (<>
    {BG('fill-retro-tint-p2')}
    {BX(20, 24, 17, 17, 4, 'fill-retro-card')}{BX(41, 32, 17, 17, 4, 'fill-retro-card')}{BX(60, 24, 17, 17, 4, 'fill-retro-card')}
    {DT(28.5, 32.5, 3, 'fill-retro-text')}{DT(46, 38, 3, 'fill-retro-text')}{DT(54, 38, 3, 'fill-retro-text')}{DT(68.5, 32.5, 3, 'fill-retro-text')}
  </>),
  numbermemory: (<>
    {BG('fill-retro-card')}
    {LN(30, 22, 30, 74, 'stroke-retro-dim', 2.5)}{LN(48, 22, 48, 74, 'stroke-retro-dim', 2.5)}{LN(66, 22, 66, 74, 'stroke-retro-dim', 2.5)}
    {DT(30, 36, 4.5, 'fill-retro-p1')}{DT(30, 56, 4.5, 'fill-retro-win')}{DT(48, 46, 4.5, 'fill-retro-cta')}{DT(66, 34, 4.5, 'fill-retro-p2')}
  </>),
  reaction: (<>
    {BG('fill-retro-tint-cta')}
    {PG('56,18 40,52 50,52 42,78 62,46 51,46', 'fill-retro-text')}
    {DT(26, 26, 4, 'fill-retro-card')}{DT(72, 66, 4, 'fill-retro-card')}
  </>),
  aim: (<>
    {BG('fill-retro-tint-p1')}
    {DT(48, 48, 26, 'fill-retro-card')}{DT(48, 48, 18, 'fill-retro-p1')}{DT(48, 48, 10, 'fill-retro-card')}{DT(48, 48, 5, 'fill-retro-p1')}
    {LN(48, 14, 48, 26, 'stroke-retro-text', 2.5)}{LN(48, 70, 48, 82, 'stroke-retro-text', 2.5)}
  </>),
  typing: (<>
    {BG('fill-retro-card')}
    {BX(20, 28, 16, 16, 3, 'fill-retro-tint-p1')}{BX(39, 28, 16, 16, 3, 'fill-retro-tint-p1')}{BX(58, 28, 16, 16, 3, 'fill-retro-win')}
    {BX(20, 47, 16, 16, 3, 'fill-retro-tint-p1')}{BX(39, 47, 16, 16, 3, 'fill-retro-tint-p1')}{BX(58, 47, 16, 16, 3, 'fill-retro-tint-p1')}
    {BX(28, 66, 40, 10, 3, 'fill-retro-cta')}
  </>),
  math: (<>
    {BG('fill-retro-tint-p1')}
    {BX(26, 30, 7, 24, 2, 'fill-retro-card')}{BX(18.5, 37.5, 22, 7, 2, 'fill-retro-card')}
    {LN(56, 60, 70, 74, 'stroke-retro-win', 5)}{LN(70, 60, 56, 74, 'stroke-retro-win', 5)}
    {LN(30, 66, 52, 66, 'stroke-retro-card', 4)}
  </>),
  arrows: (<>
    {BG('fill-retro-card')}
    {LN(48, 70, 48, 36, 'stroke-retro-p1', 6)}{PG('48,22 38,38 58,38', 'fill-retro-p1')}
    {LN(24, 48, 44, 48, 'stroke-retro-p2', 5)}{PG('52,48 40,40 40,56', 'fill-retro-p2')}
    {DT(68, 62, 9, 'fill-none stroke-retro-cta')}
  </>),
  updraft: (<>
    {BG('fill-retro-tint-p1')}
    {LN(34, 62, 48, 48, 'stroke-retro-card', 4)}{LN(48, 48, 62, 62, 'stroke-retro-card', 4)}
    {LN(34, 46, 48, 32, 'stroke-retro-card', 4)}{LN(48, 32, 62, 46, 'stroke-retro-card', 4)}
    {LN(34, 30, 48, 16, 'stroke-retro-card', 4)}{LN(48, 16, 62, 30, 'stroke-retro-card', 4)}
  </>),
  snake: (<>
    {BG('fill-retro-tint-p1')}
    {DT(28, 64, 7, 'fill-retro-win')}{DT(41, 61, 7, 'fill-retro-win')}{DT(53, 55, 7, 'fill-retro-win')}{DT(63, 46, 8, 'fill-retro-win')}
    {DT(66, 44, 2, 'fill-retro-text')}{DT(60, 44, 2, 'fill-retro-text')}
    {DT(30, 30, 7, 'fill-retro-p1')}
  </>),
  tron: (<>
    {BG('fill-retro-card')}
    {LN(20, 72, 20, 36, 'stroke-retro-p1', 3.5)}{LN(20, 36, 52, 36, 'stroke-retro-p1', 3.5)}
    {LN(76, 72, 76, 48, 'stroke-retro-p2', 3.5)}{LN(76, 48, 56, 48, 'stroke-retro-p2', 3.5)}
    {PG('54,32 56,38 62,38 57,42 59,48 54,44 49,48 51,42 46,38 52,38', 'fill-retro-win')}
  </>),
  sumo: (<>
    {BG('fill-retro-tint-cta')}
    {DT(48, 48, 30, 'fill-none stroke-retro-text')}
    {DT(37, 48, 10, 'fill-retro-p1')}{DT(59, 48, 10, 'fill-retro-p2')}
  </>),
  spaceduel: (<>
    {BG('fill-retro-card')}
    {DT(22, 22, 1.8, 'fill-retro-dim')}{DT(74, 18, 1.8, 'fill-retro-dim')}{DT(66, 74, 1.8, 'fill-retro-dim')}{DT(28, 70, 1.8, 'fill-retro-dim')}
    {PG('26,44 26,62 40,53', 'fill-retro-p1')}{PG('70,44 70,62 56,53', 'fill-retro-p2')}
    {DT(44, 53, 2, 'fill-retro-win')}{DT(49, 53, 2, 'fill-retro-win')}{DT(54, 53, 2, 'fill-retro-win', 0.5)}
  </>),
  paint: (<>
    {BG('fill-retro-card')}
    {BX(20, 56, 56, 18, 4, 'fill-retro-p1')}
    {BX(44, 22, 36, 12, 3, 'fill-retro-cta')}{LN(62, 34, 62, 50, 'stroke-retro-text', 3.5)}
    {DT(26, 28, 3.5, 'fill-retro-p1')}{DT(76, 70, 2.5, 'fill-retro-cta')}
  </>),
  pacmac: (<>
    {BG('fill-retro-tint-p1')}
    {DT(40, 48, 15, 'fill-retro-win')}
    {PG('40,48 55,40 55,56', 'fill-retro-tint-p1')}
    {DT(26, 42, 2.5, 'fill-retro-card')}
    {DT(62, 48, 2.5, 'fill-retro-card')}{DT(70, 48, 2.5, 'fill-retro-card')}
    {BX(24, 62, 12, 14, 5, 'fill-retro-p1')}{DT(28, 67, 1.8, 'fill-retro-card')}{DT(32, 67, 1.8, 'fill-retro-card')}
  </>),
  visualmemory: (<>
    {BG('fill-retro-card')}
    {BX(24, 24, 13, 13, 3, 'fill-retro-win')}{BX(41, 24, 13, 13, 3, 'fill-retro-dim', 0.5)}{BX(58, 24, 13, 13, 3, 'fill-retro-dim', 0.5)}
    {BX(24, 41, 13, 13, 3, 'fill-retro-dim', 0.5)}{BX(41, 41, 13, 13, 3, 'fill-retro-dim', 0.5)}{BX(58, 41, 13, 13, 3, 'fill-retro-win')}
    {BX(24, 58, 13, 13, 3, 'fill-retro-dim', 0.5)}{BX(41, 58, 13, 13, 3, 'fill-retro-win')}{BX(58, 58, 13, 13, 3, 'fill-retro-dim', 0.5)}
  </>),
  gomoku: (<>
    {BG('fill-retro-tint-cta')}
    {LN(24, 24, 24, 72, 'stroke-retro-dim', 1.5)}{LN(36, 24, 36, 72, 'stroke-retro-dim', 1.5)}{LN(48, 24, 48, 72, 'stroke-retro-dim', 1.5)}{LN(60, 24, 60, 72, 'stroke-retro-dim', 1.5)}{LN(72, 24, 72, 72, 'stroke-retro-dim', 1.5)}
    {LN(24, 48, 72, 48, 'stroke-retro-dim', 1.5)}
    {DT(30, 48, 4.5, 'fill-retro-text')}{DT(39, 48, 4.5, 'fill-retro-text')}{DT(48, 48, 4.5, 'fill-retro-text')}{DT(57, 48, 4.5, 'fill-retro-text')}{DT(66, 48, 4.5, 'fill-retro-text')}
  </>),
  reversi: (<>
    {BG('fill-retro-tint-p1')}
    {DT(40, 48, 15, 'fill-retro-text')}{DT(56, 48, 15, 'fill-retro-card')}
    {DT(68, 28, 8, 'fill-retro-text')}{DT(28, 68, 8, 'fill-retro-card')}
  </>),
  chainreaction: (<>
    {BG('fill-retro-card')}
    {BX(22, 22, 24, 24, 5, 'fill-none stroke-retro-dim')}{BX(50, 22, 24, 24, 5, 'fill-none stroke-retro-dim')}
    {BX(22, 50, 24, 24, 5, 'fill-none stroke-retro-dim')}{BX(50, 50, 24, 24, 5, 'fill-none stroke-retro-cta')}
    {DT(34, 34, 4, 'fill-retro-p1')}{DT(57, 34, 3, 'fill-retro-win')}{DT(67, 34, 3, 'fill-retro-win')}
    {DT(30, 62, 3, 'fill-retro-p2')}{DT(38, 62, 3, 'fill-retro-p2')}{DT(34, 68, 3, 'fill-retro-p2')}
  </>),
  blockade: (<>
    {BG('fill-retro-tint-cta')}
    {LN(24, 18, 72, 18, 'stroke-retro-win', 3.5)}
    {BX(44, 30, 7, 16, 1.5, 'fill-retro-card')}{BX(44, 50, 7, 16, 1.5, 'fill-retro-card')}
    {DT(30, 66, 7, 'fill-retro-p1')}{DT(66, 66, 7, 'fill-retro-p2')}
  </>),
  orderchaos: (<>
    {BG('fill-retro-card')}
    {LN(28, 30, 40, 42, 'stroke-retro-p1', 5)}{LN(40, 30, 28, 42, 'stroke-retro-p1', 5)}
    {DT(60, 36, 9, 'fill-none stroke-retro-p2')}
    {LN(28, 56, 68, 56, 'stroke-retro-win', 3.5)}
  </>),
  dice: (<>
    {BG('fill-retro-tint-p1')}
    {BX(22, 26, 34, 34, 7, 'fill-retro-card')}
    {DT(30, 34, 3.5, 'fill-retro-text')}{DT(48, 34, 3.5, 'fill-retro-text')}{DT(39, 43, 3.5, 'fill-retro-text')}{DT(30, 52, 3.5, 'fill-retro-text')}{DT(48, 52, 3.5, 'fill-retro-text')}
    {BX(60, 46, 22, 22, 5, 'fill-retro-card')}{DT(66, 52, 3, 'fill-retro-text')}{DT(74, 62, 3, 'fill-retro-text')}
  </>),
  hex: (<>
    {BG('fill-retro-tint-p1')}
    {PG('72,48 60,68 36,68 24,48 36,28 60,28', 'fill-none stroke-retro-card')}
    {DT(40, 48, 5, 'fill-retro-p1')}{DT(50, 52, 5, 'fill-retro-p1')}{DT(60, 48, 5, 'fill-retro-p1')}
  </>),
  minesweeper: (<>
    {BG('fill-retro-tint-p1')}
    {BX(24, 24, 15, 15, 3, 'fill-retro-card')}{BX(41, 24, 15, 15, 3, 'fill-retro-card')}{BX(58, 24, 15, 15, 3, 'fill-retro-card')}
    {BX(24, 41, 15, 15, 3, 'fill-retro-card')}{BX(41, 41, 15, 15, 3, 'fill-retro-tint-cta')}{BX(58, 41, 15, 15, 3, 'fill-retro-card')}
    {BX(24, 58, 15, 15, 3, 'fill-retro-card')}{BX(41, 58, 15, 15, 3, 'fill-retro-card')}{BX(58, 58, 15, 15, 3, 'fill-retro-card')}
    {LN(66, 22, 66, 34, 'stroke-retro-text', 2.5)}{PG('66,22 74,26 66,30', 'fill-retro-p1')}
  </>),
  herd: (<>
    {BG('fill-retro-tint-p2')}
    {DT(28, 36, 8, 'fill-retro-card')}{DT(48, 32, 8, 'fill-retro-win')}{DT(68, 36, 8, 'fill-retro-card')}
    {DT(36, 56, 8, 'fill-retro-card')}{DT(56, 56, 8, 'fill-retro-card')}{DT(70, 60, 8, 'fill-retro-card')}{DT(46, 72, 8, 'fill-retro-card')}
    {DT(48, 32, 11, 'fill-none stroke-retro-cta')}
  </>),
  trivia: (<>
    {BG('fill-retro-tint-p2')}
    {BX(22, 24, 52, 32, 8, 'fill-retro-card')}{PG('32,56 32,68 42,56', 'fill-retro-card')}
    {PG('48,30 50,36 56,36.5 51.5,40 53,46 48,42.5 43,46 44.5,40 40,36.5 46,36', 'fill-retro-win')}
    {DT(66, 62, 6, 'fill-retro-cta')}
  </>),
  battleship: (<>
    {BG('fill-retro-tint-p1')}
    {BX(20, 46, 38, 12, 6, 'fill-retro-text')}{BX(30, 38, 12, 10, 2, 'fill-retro-card')}
    {LN(18, 66, 40, 66, 'stroke-retro-card', 2.5)}{LN(44, 72, 66, 72, 'stroke-retro-card', 2.5)}{LN(62, 64, 78, 64, 'stroke-retro-card', 2.5)}
    {PG('68,26 70,32 76,32 71,36 73,42 68,38 63,42 65,36 60,32 66,32', 'fill-retro-win')}
  </>),
  mancala: (<>
    {BG('fill-retro-tint-cta')}
    {DT(26, 48, 9, 'fill-none stroke-retro-text')}{DT(44, 48, 9, 'fill-none stroke-retro-text')}{DT(62, 48, 9, 'fill-none stroke-retro-text')}
    {BX(72, 30, 12, 36, 6, 'fill-retro-p1')}
    {DT(23, 46, 2.5, 'fill-retro-card')}{DT(29, 50, 2.5, 'fill-retro-card')}{DT(44, 48, 2.5, 'fill-retro-card')}{DT(78, 44, 2.5, 'fill-retro-card')}{DT(78, 52, 2.5, 'fill-retro-card')}
  </>),
  checkers: (<>
    {BG('fill-retro-tint-p1')}
    {BX(24, 24, 48, 48, 5, 'fill-retro-card')}
    {BX(30, 30, 9, 9, 1.5, 'fill-retro-text', 0.8)}{BX(48, 30, 9, 9, 1.5, 'fill-retro-text', 0.8)}{BX(39, 39, 9, 9, 1.5, 'fill-retro-text', 0.8)}{BX(57, 39, 9, 9, 1.5, 'fill-retro-text', 0.8)}
    {BX(30, 48, 9, 9, 1.5, 'fill-retro-text', 0.8)}{BX(48, 48, 9, 9, 1.5, 'fill-retro-text', 0.8)}{BX(39, 57, 9, 9, 1.5, 'fill-retro-text', 0.8)}{BX(57, 57, 9, 9, 1.5, 'fill-retro-text', 0.8)}
    {DT(35, 35, 4, 'fill-retro-p2')}{DT(61, 61, 4, 'fill-retro-p1')}
    {DT(61, 61, 6.5, 'fill-none stroke-retro-win')}
  </>),
  airhockey: (<>
    {BG('fill-retro-card')}
    {BX(20, 24, 56, 48, 14, 'fill-none stroke-retro-p1')}
    {LN(48, 28, 48, 68, 'stroke-retro-p1', 2)}
    {DT(48, 48, 7, 'fill-retro-p1')}
    {DT(30, 34, 9, 'fill-none stroke-retro-p2')}{DT(30, 34, 2.5, 'fill-retro-text')}
  </>),
  artillery: (<>
    {BG('fill-retro-tint-p1')}
    {LN(16, 74, 80, 74, 'stroke-retro-win', 3)}
    {DT(30, 66, 8, 'fill-retro-text')}{LN(30, 66, 52, 44, 'stroke-retro-text', 6)}
    {DT(56, 40, 2, 'fill-retro-dim')}{DT(62, 34, 2, 'fill-retro-dim')}{DT(68, 30, 2, 'fill-retro-dim')}
    {DT(74, 28, 6, 'fill-retro-card')}{DT(74, 28, 3.5, 'fill-retro-p1')}
  </>),
  animalstack: (<>
    {BG('fill-retro-tint-p1')}
    {LN(20, 76, 76, 76, 'stroke-retro-text', 2.5)}
    {BX(28, 60, 40, 16, 8, 'fill-retro-win')}{BX(33, 44, 30, 16, 8, 'fill-retro-cta')}{BX(38, 28, 20, 16, 8, 'fill-retro-p1')}
    {DT(44, 35, 1.8, 'fill-retro-card')}{DT(52, 35, 1.8, 'fill-retro-card')}
    {DT(42, 51, 1.8, 'fill-retro-card')}{DT(54, 51, 1.8, 'fill-retro-card')}
  </>),
  wirecrossed: (<>
    {BG('fill-retro-card')}
    {LN(20, 26, 48, 44, 'stroke-retro-p1', 3)}{LN(20, 48, 48, 52, 'stroke-retro-p1', 3)}{LN(20, 70, 48, 60, 'stroke-retro-win', 3)}
    {DT(64, 52, 15, 'fill-retro-text')}{BX(58, 48, 12, 7, 2, 'fill-retro-p1')}
    {LN(64, 37, 70, 28, 'stroke-retro-dim', 2.5)}
    {PG('70,22 71.5,27 76,27 72.5,30 74,35 70,32 66,35 67.5,30 64,27 68.5,27', 'fill-retro-win')}
  </>),
  twotruths: (<>
    {BG('fill-retro-card')}
    {DT(30, 36, 11, 'fill-none stroke-retro-win')}{LN(25, 36, 29, 40, 'stroke-retro-win', 3)}{LN(29, 40, 36, 31, 'stroke-retro-win', 3)}
    {DT(66, 36, 11, 'fill-none stroke-retro-win')}{LN(61, 36, 65, 40, 'stroke-retro-win', 3)}{LN(65, 40, 72, 31, 'stroke-retro-win', 3)}
    {DT(48, 64, 11, 'fill-none stroke-retro-p1')}{LN(43, 59, 53, 69, 'stroke-retro-p1', 3.5)}{LN(53, 59, 43, 69, 'stroke-retro-p1', 3.5)}
  </>),
  bluff: (<>
    {BG('fill-retro-tint-p2')}
    {DT(48, 48, 23, 'fill-retro-card')}{DT(48, 48, 15, 'fill-retro-tint-p2')}
    {DT(48, 26, 3.5, 'fill-retro-tint-p2')}{DT(48, 70, 3.5, 'fill-retro-tint-p2')}{DT(26, 48, 3.5, 'fill-retro-tint-p2')}{DT(70, 48, 3.5, 'fill-retro-tint-p2')}
    {DT(48, 48, 8, 'fill-retro-win')}
  </>),
  lanterns: (<>
    {BG('fill-retro-card')}
    {LN(16, 24, 80, 24, 'stroke-retro-dim', 2)}
    {LN(32, 24, 32, 32, 'stroke-retro-dim', 2)}{LN(48, 24, 48, 32, 'stroke-retro-dim', 2)}{LN(64, 24, 64, 32, 'stroke-retro-dim', 2)}
    {DT(32, 42, 11, 'fill-retro-p1', 0.25)}{BX(26, 32, 12, 20, 6, 'fill-retro-p1')}{BX(29, 38, 6, 8, 3, 'fill-retro-card')}
    {DT(48, 42, 11, 'fill-retro-p2', 0.25)}{BX(42, 32, 12, 20, 6, 'fill-retro-p2')}{BX(45, 38, 6, 8, 3, 'fill-retro-card')}
    {DT(64, 42, 11, 'fill-retro-cta', 0.25)}{BX(58, 32, 12, 20, 6, 'fill-retro-cta')}{BX(61, 38, 6, 8, 3, 'fill-retro-card')}
  </>),
  docking: (<>
    {BG('fill-retro-card')}
    {DT(48, 52, 23, 'fill-none stroke-retro-card')}
    {BX(40, 18, 16, 24, 7, 'fill-retro-p1')}{DT(48, 26, 4, 'fill-retro-cta')}
    {DT(24, 52, 1.8, 'fill-retro-dim')}{DT(24, 62, 1.8, 'fill-retro-dim')}{DT(72, 52, 1.8, 'fill-retro-dim')}{DT(72, 62, 1.8, 'fill-retro-dim')}
  </>),
  wavelength: (<>
    {BG('fill-retro-tint-p2')}
    {BX(20, 34, 56, 8, 3, 'fill-retro-p1')}{BX(20, 44, 56, 8, 3, 'fill-retro-win')}{BX(20, 54, 56, 8, 3, 'fill-retro-cta')}
    {LN(48, 34, 62, 62, 'stroke-retro-card', 3)}{PG('62,62 56,70 68,70', 'fill-retro-win')}
    {DT(48, 34, 4, 'fill-retro-card')}
  </>),
  fibbage: (<>
    {BG('fill-retro-tint-cta')}
    {BX(20, 24, 56, 30, 8, 'fill-retro-card')}{PG('30,54 30,64 38,54', 'fill-retro-card')}
    {LN(30, 36, 42, 36, 'stroke-retro-text', 2.5)}{LN(42, 36, 38, 44, 'stroke-retro-text', 2.5)}{LN(38, 44, 52, 44, 'stroke-retro-text', 2.5)}
    {DT(66, 62, 6, 'fill-retro-cta')}
  </>),
  spyfair: (<>
    {BG('fill-retro-card')}
    {DT(40, 40, 17, 'fill-none stroke-retro-cta')}
    {DT(40, 40, 11, 'fill-retro-card')}{DT(40, 40, 7, 'fill-retro-p1')}{DT(40, 40, 3, 'fill-retro-text')}
    {LN(52, 52, 68, 68, 'stroke-retro-cta', 5)}
    {BX(62, 20, 18, 18, 4, 'fill-retro-tint-p2')}{DT(71, 29, 3, 'fill-retro-win')}
  </>),
  headsup: (<>
    {BG('fill-retro-tint-p1')}
    {BX(30, 22, 36, 22, 5, 'fill-retro-card')}
    {PG('48,26 49.5,31 55,31.5 50.8,34.5 52,40 48,36.8 44,40 45.2,34.5 41,31.5 46.5,31', 'fill-retro-win')}
    {DT(48, 62, 15, 'fill-retro-cta')}
    {DT(42, 60, 2, 'fill-retro-card')}{DT(54, 60, 2, 'fill-retro-card')}
  </>),
  chameleon: (<>
    {BG('fill-retro-tint-p1')}
    {DT(48, 42, 17, 'fill-retro-card')}{DT(48, 42, 10, 'fill-retro-p1')}{DT(48, 42, 5, 'fill-retro-text')}{DT(45, 39, 2, 'fill-retro-card')}
    {DT(26, 68, 9, 'fill-retro-cta', 0.7)}{DT(68, 70, 7, 'fill-retro-win', 0.7)}
  </>),
  wordduel: (<>
    {BG('fill-retro-tint-p1')}
    {LN(28, 24, 68, 68, 'stroke-retro-win', 6)}{PG('68,68 72,58 62,62', 'fill-retro-text')}
    {LN(68, 24, 28, 68, 'stroke-retro-cta', 6)}{PG('28,68 24,58 34,62', 'fill-retro-text')}
    {BX(20, 70, 16, 16, 3, 'fill-retro-card')}{BX(60, 70, 16, 16, 3, 'fill-retro-card')}
  </>),
  wordcoop: (<>
    {BG('fill-retro-tint-p1')}
    {BX(20, 26, 22, 22, 4, 'fill-retro-card')}{BX(54, 26, 22, 22, 4, 'fill-retro-card')}
    {DT(48, 60, 10, 'fill-none stroke-retro-win')}{DT(48, 72, 10, 'fill-none stroke-retro-win')}
  </>),
  converge: (<>
    {BG('fill-retro-tint-p1')}
    {LN(48, 76, 48, 58, 'stroke-retro-card', 5)}{PG('48,50 40,60 56,60', 'fill-retro-card')}
    {LN(48, 20, 48, 34, 'stroke-retro-win', 5)}{PG('48,42 40,32 56,32', 'fill-retro-win')}
    {LN(22, 48, 36, 48, 'stroke-retro-cta', 5)}{PG('44,48 34,40 34,56', 'fill-retro-cta')}
    {LN(74, 48, 60, 48, 'stroke-retro-p1', 5)}{PG('52,48 62,40 62,56', 'fill-retro-p1')}
    {DT(48, 48, 4, 'fill-retro-card')}
  </>),
  wordrace: (<>
    {BG('fill-retro-tint-cta')}
    {LN(28, 20, 28, 66, 'stroke-retro-text', 3)}
    {BX(28, 20, 32, 22, 2, 'fill-retro-card')}
    {BX(28, 20, 8, 5.5, 1, 'fill-retro-text')}{BX(44, 20, 8, 5.5, 1, 'fill-retro-text')}{BX(36, 25.5, 8, 5.5, 1, 'fill-retro-text')}{BX(52, 25.5, 8, 5.5, 1, 'fill-retro-text')}
    {BX(28, 31, 8, 5.5, 1, 'fill-retro-text')}{BX(44, 31, 8, 5.5, 1, 'fill-retro-text')}{BX(36, 36.5, 8, 5.5, 1, 'fill-retro-text')}{BX(52, 36.5, 8, 5.5, 1, 'fill-retro-text')}
    {LN(64, 48, 80, 48, 'stroke-retro-text', 2.5)}{LN(64, 58, 76, 58, 'stroke-retro-text', 2.5)}
  </>),
  wordhunt: (<>
    {BG('fill-retro-tint-p1')}
    {BX(20, 20, 13, 13, 3, 'fill-retro-card')}{BX(35, 20, 13, 13, 3, 'fill-retro-card')}{BX(50, 20, 13, 13, 3, 'fill-retro-card')}
    {BX(20, 35, 13, 13, 3, 'fill-retro-card')}{BX(35, 35, 13, 13, 3, 'fill-retro-win')}{BX(50, 35, 13, 13, 3, 'fill-retro-card')}
    {BX(20, 50, 13, 13, 3, 'fill-retro-card')}{BX(35, 50, 13, 13, 3, 'fill-retro-card')}{BX(50, 50, 13, 13, 3, 'fill-retro-card')}
    {DT(68, 66, 12, 'fill-none stroke-retro-cta')}{LN(76, 74, 84, 82, 'stroke-retro-cta', 4)}
  </>),
  password: (<>
    {BG('fill-retro-card')}
    {DT(48, 34, 13, 'fill-none stroke-retro-win')}
    {BX(34, 38, 28, 32, 5, 'fill-retro-cta')}
    {DT(48, 50, 4, 'fill-retro-card')}{BX(46, 52, 4, 9, 2, 'fill-retro-card')}
  </>),
  anagrams: (<>
    {BG('fill-retro-tint-cta')}
    {BX(20, 28, 16, 16, 3, 'fill-retro-card')}{BX(38, 28, 16, 16, 3, 'fill-retro-card')}{BX(56, 28, 16, 16, 3, 'fill-retro-win')}
    {DT(48, 62, 13, 'fill-none stroke-retro-text')}
    {PG('48,45 42,53 54,53', 'fill-retro-text')}{PG('61,62 59,54 51,58', 'fill-retro-text')}
  </>),
  hunch: (<>
    {BG('fill-retro-tint-p2')}
    {DT(48, 40, 18, 'fill-retro-card')}{DT(30, 62, 5, 'fill-retro-card')}{DT(38, 70, 3.5, 'fill-retro-card')}
    {DT(43, 38, 2.5, 'fill-retro-text')}{DT(53, 38, 2.5, 'fill-retro-text')}
    {PG('48,48 52,56 44,56', 'fill-retro-text')}
    {PG('70,24 71.5,29 76,29 72.5,32 74,37 70,34 66,37 67.5,32 64,29 68.5,29', 'fill-retro-win')}
  </>),
  pairs: (<>
    {BG('fill-retro-tint-p1')}
    {BX(22, 22, 24, 30, 4, 'fill-retro-win')}{BX(50, 22, 24, 30, 4, 'fill-retro-win')}
    {BX(22, 56, 24, 26, 4, 'fill-retro-p1')}{BX(50, 56, 24, 26, 4, 'fill-retro-p1')}
    {PG('34,30 35.5,35 41,35.5 36.8,38.5 38,44 34,41 30,44 31.2,38.5 27,35.5 32.5,35', 'fill-retro-text')}
    {PG('62,30 63.5,35 69,35.5 64.8,38.5 66,44 62,41 58,44 59.2,38.5 55,35.5 60.5,35', 'fill-retro-text')}
    {DT(34, 69, 4, 'fill-retro-card')}{DT(62, 69, 4, 'fill-retro-card')}
  </>),
  sketch: (<>
    {BG('fill-retro-card')}
    {LN(28, 68, 60, 36, 'stroke-retro-win', 6)}{PG('60,36 66,26 56,28', 'fill-retro-text')}
    {LN(24, 30, 38, 30, 'stroke-retro-text', 2.5)}{LN(38, 30, 34, 42, 'stroke-retro-text', 2.5)}{LN(34, 42, 48, 42, 'stroke-retro-text', 2.5)}
  </>),
  codewords: (<>
    {BG('fill-retro-card')}
    {BX(20, 28, 16, 16, 3, 'fill-retro-tint-p1')}{BX(38, 28, 16, 16, 3, 'fill-retro-tint-p1')}{BX(56, 28, 16, 16, 3, 'fill-retro-tint-p1')}
    {DT(25, 33, 2, 'fill-retro-text')}{DT(31, 39, 2, 'fill-retro-text')}{DT(43, 36, 2, 'fill-retro-text')}{DT(61, 33, 2, 'fill-retro-text')}{DT(67, 39, 2, 'fill-retro-text')}
    {DT(48, 62, 9, 'fill-none stroke-retro-win')}
  </>),
  justone: (<>
    {BG('fill-retro-tint-p2')}
    {BX(20, 28, 15, 15, 3, 'fill-retro-dim', 0.5)}{BX(38, 28, 15, 15, 3, 'fill-retro-dim', 0.5)}{BX(56, 28, 15, 15, 3, 'fill-retro-dim', 0.5)}
    {BX(36, 50, 24, 24, 4, 'fill-retro-win')}
    {PG('48,55 49.5,60 55,60.5 50.8,63.5 52,69 48,66 44,69 45.2,63.5 41,60.5 46.5,60', 'fill-retro-text')}
  </>),
}

export function GameArtSvg({ type, className }) {
  const t = resolveArt(type)
  if (!ART_TYPES.has(t)) return null
  const Comp = SOFT_COMP[t]
  if (Comp) return <Comp className={className} />
  return (
    <svg viewBox="0 0 96 96" className={className} role="img" aria-hidden="true">
      {SOFT_FRAG[t]}
    </svg>
  )
}

export function GameArt({ type, className }) {
  const style = useGameArtStyle()
  // ICONS: the original mono icon underneath is the look — render nothing.
  if (style === 'icons') return null
  const t = resolveArt(type)
  if (!ART_TYPES.has(t)) return null
  return style === 'svg'
    ? <GameArtSvg type={type} className={className} />
    : <GameArtImg type={type} className={className} />
}
