#!/usr/bin/env node
// Regenerates src/lib/vendor/planck-det.js — planck.js (MIT, Box2D port) with
// every Math.sin / Math.cos rewritten to the deterministic Taylor trig in
// src/lib/detMath.js. Native trig differs between JS engines (V8 vs
// JavaScriptCore), and a stacked tower amplifies a last-ulp difference into a
// different tower, so online Animal Stack replays need this patched copy.
//
// Usage (planck is not an app dependency — fetch the pinned release first):
//   npm pack planck@1.4.2 && tar xzf planck-1.4.2.tgz
//   node scripts/vendor-planck.mjs package/dist/planck.mjs
// src/lib/animalStackLogic.test.js fails if the vendored file still calls
// Math.sin / Math.cos.
import { readFileSync, writeFileSync } from 'node:fs'

const src = process.argv[2]
if (!src) {
  console.error('usage: node scripts/vendor-planck.mjs <path/to/planck/dist/planck.mjs>')
  process.exit(1)
}
let code = readFileSync(src, 'utf8')
const version = (code.match(/Planck\.js v([\d.]+)/) || [])[1] || 'unknown'
const before = (code.match(/Math\.(sin|cos)\b/g) || []).length
code = code
  .replace(/Math\.sin\b/g, '__detSin')
  .replace(/Math\.cos\b/g, '__detCos')
  .replace(/\n\/\/# sourceMappingURL=.*\n?$/, '\n')
const header = `// GENERATED by scripts/vendor-planck.mjs from planck.js v${version} — do not edit.
// Math.sin/Math.cos (${before} sites) are replaced by detSin/detCos so the
// simulation is bit-identical across JS engines. License below is unchanged.
/* eslint-disable */
import { detSin as __detSin, detCos as __detCos } from '../detMath'
`
writeFileSync(new URL('../src/lib/vendor/planck-det.js', import.meta.url), header + code)
console.log(`planck v${version}: rewrote ${before} Math.sin/cos sites → src/lib/vendor/planck-det.js`)
